//! Generating `docs/FEATURES.md` from the GNU compatibility matrix.
//!
//! The matrix lives in `crates/rucc-gnu/features.toml` and the compiler reads it through
//! `rucc_gnu::features()`. This is the same table counted, so that how much of the GNU surface is
//! missing is a number somebody can quote rather than an impression. It is here rather than in
//! `xtask` for the reason everything else in this crate is: `xtask` has no dependencies, and a
//! report produced from a second parser of the same file is a report that can disagree with the
//! compiler about it.

use std::fmt::Write as _;
use std::path::Path;
use std::process::ExitCode;

use rucc_gnu::{Answer, Feature, Kind, Status, features};

/// Whether to write the file or only to compare.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Mode {
    Write,
    Check,
}

/// Write the file, or check that the one on disk matches.
pub(crate) fn run(root: &Path, mode: Mode) -> ExitCode {
    let path = root.join("docs").join("FEATURES.md");
    let wanted = render(features());

    if mode == Mode::Check {
        let found = std::fs::read_to_string(&path).unwrap_or_default();
        if found == wanted {
            println!("features: docs/FEATURES.md is up to date");
            return ExitCode::SUCCESS;
        }
        println!("docs/FEATURES.md is out of date, run `cargo xtask features`");
        return ExitCode::FAILURE;
    }

    match std::fs::write(&path, wanted) {
        Ok(()) => {
            println!("features: wrote docs/FEATURES.md");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("error: {error}");
            ExitCode::FAILURE
        }
    }
}

const KINDS: [Kind; 5] =
    [Kind::Attribute, Kind::CAttribute, Kind::Builtin, Kind::Feature, Kind::Extension];

const STATUSES: [Status; 4] =
    [Status::Implemented, Status::Partial, Status::Unimplemented, Status::Rejected];

fn kind_name(kind: Kind) -> &'static str {
    match kind {
        Kind::Attribute => "attribute",
        Kind::CAttribute => "c-attribute",
        Kind::Builtin => "builtin",
        Kind::Feature => "feature",
        Kind::Extension => "extension",
    }
}

fn status_name(status: Status) -> &'static str {
    match status {
        Status::Implemented => "implemented",
        Status::Partial => "partial",
        Status::Unimplemented => "unimplemented",
        Status::Rejected => "rejected",
    }
}

fn answer_name(answer: Answer) -> &'static str {
    match answer {
        Answer::Warn => "warn",
        Answer::Error => "error",
    }
}

/// A share as a whole percentage, rounded down so that 99.6 does not read as done.
fn percent(part: usize, whole: usize) -> usize {
    (part * 100).checked_div(whole).unwrap_or(0)
}

/// The whole file, as text.
fn render(rows: &[Feature]) -> String {
    let mut out = String::new();
    out.push_str("# GNU features\n\n");
    out.push_str(
        "Generated by `cargo xtask features` from `crates/rucc-gnu/features.toml`. Do not edit \
         this file, edit the table.\n\n",
    );
    out.push_str(
        "The table is what `__has_attribute`, `__has_builtin`, `__has_feature`, \
         `__has_extension` and `__has_c_attribute` answer, so the counts below are the \
         compiler's own claims about itself. Only `implemented` answers yes, and every \
         implemented row names the tests that prove it. The exception is a row gcc 16 \
         answers 0 for, such as the clang names for GNU extensions: it answers 0 like gcc \
         and is still counted by what the compiler does. The design is \
         `spec/13-gnu-compat.md` section 13.2.\n\n",
    );

    let count = |kind: Option<Kind>, status: Option<Status>| {
        rows.iter()
            .filter(|row| kind.is_none_or(|k| row.kind == k))
            .filter(|row| status.is_none_or(|s| row.status == s))
            .count()
    };

    let total = rows.len();
    let done = count(None, Some(Status::Implemented));
    let _ = writeln!(
        out,
        "{done} of {total} rows are implemented, which is {}%.\n",
        percent(done, total)
    );

    out.push_str("| kind |");
    for status in STATUSES {
        let _ = write!(out, " {} |", status_name(status));
    }
    out.push_str(" total | done |\n|---|");
    for _ in STATUSES {
        out.push_str("---:|");
    }
    out.push_str("---:|---:|\n");
    let mut line = |label: &str, kind: Option<Kind>| {
        let _ = write!(out, "| {label} |");
        for status in STATUSES {
            let _ = write!(out, " {} |", count(kind, Some(status)));
        }
        let all = count(kind, None);
        let _ =
            writeln!(out, " {all} | {}% |", percent(count(kind, Some(Status::Implemented)), all));
    };
    for kind in KINDS {
        line(kind_name(kind), Some(kind));
    }
    line("**all**", None);

    out.push_str("\n## The gap\n\n");
    out.push_str(
        "Every row that does not answer yes, sorted by kind and then by name. `answer` is what \
         the compiler does when it meets one: `warn` ignores it and says so, `error` refuses, \
         because ignoring it would produce wrong code rather than slow code.\n\n",
    );
    out.push_str("| name | kind | status | answer | used by |\n|---|---|---|---|---|\n");
    let mut gap: Vec<&Feature> =
        rows.iter().filter(|row| row.status != Status::Implemented).collect();
    gap.sort_by_key(|row| (row.kind, row.name));
    for row in gap {
        let used_by = row.used_by.join(", ");
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            row.name,
            kind_name(row.kind),
            status_name(row.status),
            answer_name(row.answer),
            used_by,
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{percent, render};
    use rucc_gnu::features;

    #[test]
    fn a_share_rounds_down_so_nearly_done_is_not_done() {
        assert_eq!(percent(996, 1000), 99);
        assert_eq!(percent(0, 0), 0);
    }

    #[test]
    fn every_row_that_answers_no_is_listed_in_the_gap() {
        let text = render(features());
        for row in features().iter().filter(|row| !row.status.is_available()) {
            assert!(text.contains(&format!("| `{}` |", row.name)), "{} is missing", row.name);
        }
    }
}
