PRAGMA temp_store=MEMORY;
CREATE TABLE t(id INTEGER PRIMARY KEY, k INTEGER, v REAL, s TEXT);
BEGIN;
WITH RECURSIVE c(i) AS (SELECT 1 UNION ALL SELECT i + 1 FROM c WHERE i < 200000)
INSERT INTO t SELECT i, (i * 7919) % 97, i * 0.5, 'row ' || i FROM c;
COMMIT;
CREATE INDEX t_k ON t(k);
CREATE INDEX t_s ON t(s);
SELECT count(*), sum(k), total(v) FROM t;
SELECT count(*) FROM t WHERE id BETWEEN 50000 AND 99999;
SELECT k, count(*), sum(id) FROM t GROUP BY k ORDER BY k LIMIT 5;
SELECT s FROM t ORDER BY s LIMIT 3;
SELECT s FROM t WHERE id = 123457;
SELECT count(*) FROM t WHERE s LIKE 'row 1%';
SELECT printf('%.3f|%e|%10.2f|%x', 3.14159265, 1234567.0, -2.5, 255);
SELECT round(avg(v), 4), min(v), max(v) FROM t WHERE k = 13;
SELECT id, sum(id) OVER (ORDER BY id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) FROM t WHERE id <= 5;
SELECT json_object('a', 1, 'b', json_array(2.5, 'x', NULL));
SELECT json_extract('{"p":{"q":[10,20,30]}}', '$.p.q[1]');
SELECT date('2026-10-06', '+1 month', 'start of month'), julianday('2000-01-01 12:00:00');
SELECT upper('wasm'), length('rucc'), substr('compiler', 4, 3), replace('a-b-c', '-', '+'), hex('AB');
SELECT a.k, count(*) FROM t AS a JOIN t AS b ON a.id = b.id + 1 WHERE a.k < 3 GROUP BY a.k;
SELECT 9223372036854775807 + 0, -9223372036854775808 / -1.0, 7 / 2, 7 % -3, 1e308 * 10;
SELECT quote(x'00ff'), typeof(1), typeof(1.0), typeof('1'), typeof(NULL);
SELECT group_concat(id, ',') FROM (SELECT id FROM t WHERE k = 0 ORDER BY id LIMIT 6);
CREATE TABLE u AS SELECT k, sum(v) AS sv FROM t GROUP BY k;
DELETE FROM t WHERE k % 2 = 0;
UPDATE t SET v = v * 2 WHERE k = 1;
SELECT count(*), total(v) FROM t;
SELECT count(*), total(sv) FROM u;
PRAGMA integrity_check;
