PRAGMA temp_store=MEMORY;
CREATE TABLE t(a INTEGER PRIMARY KEY, b INTEGER, c TEXT);
BEGIN;
WITH RECURSIVE s(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM s WHERE x < 2000000)
INSERT INTO t(b, c) SELECT (x * 7919) % 1000003, 'row ' || x FROM s;
COMMIT;
CREATE INDEX tb ON t(b);
SELECT count(*), sum(b), total(a) / 2 FROM t;
SELECT count(*) FROM t WHERE b BETWEEN 250000 AND 750000;
SELECT sum(n) FROM (SELECT b % 97 AS k, count(*) AS n FROM t GROUP BY k);
SELECT c FROM t WHERE a = 1;
SELECT c FROM t WHERE b = (SELECT b FROM t WHERE a = 1000004);
