#!/usr/bin/env python3
"""Writes crates/rucc-target/src/aarch64/system.rs from LLVM's AArch64SystemOperands.td.

Run from the repository root with the path to that file, and llvm-tblgen on the PATH or named by
LLVM_TBLGEN:

    python3 crates/rucc-target/src/aarch64/system.py AArch64SystemOperands.td <llvm commit>

The file says which features each name needs, and nothing here reads that: GNU as takes every
name whatever the CPU, and so does rucc. The predicate definitions at the top need the rest of the
target's records, so they are left out before tblgen reads it.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

OUT = "crates/rucc-target/src/aarch64/system.rs"


def records(td):
    text = open(td).read()
    text = re.sub(r"^def Has\w+\s*:.*?;\n", "", text, flags=re.M | re.S)
    tblgen = os.environ.get("LLVM_TBLGEN", "llvm-tblgen")
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "operands.td")
        open(path, "w").write(text)
        include = os.path.join(os.path.dirname(os.path.dirname(subprocess.check_output(
            ["sh", "-c", f"command -v {tblgen}"], text=True).strip())), "include")
        dump = subprocess.check_output([tblgen, "--dump-json", "-I", include, path], text=True)
    return json.loads(dump)


def value(record):
    return sum(1 << at for at, bit in enumerate(record["Encoding"]) if bit == 1)


def main():
    td, commit = sys.argv[1], sys.argv[2]
    d = records(td)
    every = lambda kind: [d[name] for name in d["!instanceof"].get(kind, [])]

    registers = sorted((r["Name"].lower(), value(r) & 0x7FFF) for r in every("SysReg"))
    pstate = []
    for r in every("PStateImm0_15"):
        pstate.append((r["Name"].lower(), value(r), "None"))
    for r in every("PStateImm0_1"):
        pstate.append((r["Name"].lower(), value(r) & 0o77, f"Some({value(r) >> 6})"))
    pstate.sort()
    uses = {"REG_NONE": "None", "REG_OPTIONAL": "Optional", "REG_REQUIRED": "Required"}
    operations = []
    for r in every("TLBIEntry"):
        operations.append(("tlbi", r["Name"].lower(), value(r), uses[r["RegUse"]["def"]]))
    for r in every("IC"):
        operations.append(("ic", r["Name"].lower(), value(r), "Required" if r["NeedsReg"] else "None"))
    for r in every("DC"):
        operations.append(("dc", r["Name"].lower(), value(r), "Required"))
    for r in every("AT"):
        operations.append(("at", r["Name"].lower(), value(r), "Required"))
    operations.sort()

    out = []
    w = out.append
    w(f"//! Generated by system.py from LLVM's AArch64SystemOperands.td at {commit[:12]}. Do not edit.")
    w("")
    w("/// Whether an operation of `tlbi`, `ic`, `dc` or `at` takes a register.")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    w("pub(super) enum Use {")
    w("    None,")
    w("    Optional,")
    w("    Required,")
    w("}")
    w("")
    w("/// The system registers `mrs` and `msr` name, sorted, each with the fifteen bits it is.")
    w(f"pub(super) static REGISTERS: [(&str, u16); {len(registers)}] = [")
    for name, field in registers:
        w(f'    ("{name}", 0x{field:04x}),')
    w("];")
    w("")
    w("/// The fields `msr` writes an immediate to, sorted, each with its `op1` and `op2` together and")
    w("/// the top of `CRm` for the ones that take a single bit.")
    w(f"pub(super) static PSTATE: [(&str, u8, Option<u8>); {len(pstate)}] = [")
    for name, field, high in pstate:
        w(f'    ("{name}", 0o{field:02o}, {high}),')
    w("];")
    w("")
    w("/// The operations of `tlbi`, `ic`, `dc` and `at`, sorted, each with the fourteen bits of `sys` it")
    w("/// is, `op1`, `CRn`, `CRm` and `op2`.")
    w(f"pub(super) static OPERATIONS: [(&str, &str, u16, Use); {len(operations)}] = [")
    for mnemonic, name, field, use in operations:
        w(f'    ("{mnemonic}", "{name}", 0x{field:04x}, Use::{use}),')
    w("];")
    open(OUT, "w").write("\n".join(out) + "\n")


main()
