/* The types and the prototypes both sides of the differential agree on.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-signatures --write`. Do not edit
 * this file, edit the grammar in `build-tools/rucc-targets/src/signatures.rs`.
 *
 * This is the differential ABI harness of `spec/cross-compile/14-testing.md` section
 * 14.3. `callee.c` is compiled by one compiler and `caller.c` by the other, the two are
 * linked together and the program is run, so a value that arrives wrong is the two
 * compilers disagreeing about a calling convention rather than about a layout.
 *
 * The program prints nothing and exits zero when the two agree. Every disagreement
 * prints the function and the parameter it is about, and the exit status is one.
 */

#ifndef RUCC_ABI_SIGNATURES_H
#define RUCC_ABI_SIGNATURES_H

/* One byte in a struct, which is a register on every ABI here and a different register from the
 * one a bare char would use on none of them. */
struct one_char {
	char a;
};

/* Three bytes, so the size is not a power of two and the last byte of the register it travels in
 * is nobody's. */
struct three_char {
	char a;
	char b;
	char c;
};

/* Eight bytes of integer, which is one register everywhere and the smallest aggregate that fills
 * one. */
struct two_int {
	int a;
	int b;
};

/* An int and a float in one eightbyte. SysV classifies the eightbyte by what is in it, so this
 * is an integer register and two floats in the same space are not. */
struct int_float {
	int a;
	float b;
};

/* Two floats, which is a homogeneous aggregate in two vector registers under AAPCS64 and one SSE
 * register holding both under SysV. */
struct two_float {
	float a;
	float b;
};

/* Four floats, which is the largest homogeneous aggregate AAPCS64 will put in registers and
 * sixteen bytes of SSE under SysV. */
struct four_float {
	float a;
	float b;
	float c;
	float d;
};

/* Sixteen bytes of floating point, which is two registers under both rules and a hidden pointer
 * under Windows x64. */
struct two_double {
	double a;
	double b;
};

/* A long double in a struct, which is the x87 eighty bit type on two rows, an IEEE quad on
 * several, a double double on ppc64le and a plain double on MSVC. */
struct long_double_one {
	long double a;
};

/* An int and a pointer, so the size and the padding both move with the pointer width and the
 * member after the padding is what says whether they moved together. */
struct int_pointer {
	int a;
	void *b;
};

/* Twenty four bytes, which is past the threshold on every ABI here, so it travels as a copy the
 * callee is given the address of rather than in registers. */
struct six_int {
	int a;
	int b;
	int c;
	int d;
	int e;
	int f;
};

/* A struct inside a struct with a float after it. Flattening is what every classification rule
 * does first, so a rule that stops at the outer members gets this one wrong and gets nothing
 * else wrong. */
struct nested {
	struct two_int a;
	float b;
};

/* A union of an int and a float, which is one eightbyte with two classifications and is why
 * SysV's rule is a merge rather than a lookup. */
union int_or_float {
	int a;
	float b;
};

/* The bytes a pointer argument points into, defined in report.c. Nothing reads them:
 * what travels is the address, and an address inside a known object is one both
 * sides can name without either of them having to agree about a number. */
extern char anchor[64];

/* How many disagreements have been seen, and how one is recorded. Both live in
 * report.c, which is the only file here that includes a libc header and is always
 * built by the reference compiler. Two `const char *` and a `void` return is the one
 * signature every ABI in the table agrees about, so calling this is not itself a
 * thing the corpus can get wrong. */
extern int abi_failures;
void abi_fail(const char *fn, const char *slot);

/* Ten integers, which is more than any ABI here has argument registers, so the tail is on the
 * stack and the boundary between the two is what this is about. */
long long h_ints_past_the_registers(long long a0, long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, long long a8, long long a9);

/* Ten doubles, for the same reason and the other register file. SysV has eight of these and
 * Windows x64 has four, so the two disagree about where the fifth one is. */
double h_doubles_past_the_registers(double a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9);

/* Integers and doubles alternating past the end of both files, which is where an ABI that counts
 * one register file decides differently from one that counts a slot per argument. */
int h_mixed_past_the_registers(int a0, double a1, int a2, double a3, int a4, double a5, int a6, double a7, int a8, double a9, int a10, double a11);

/* The aggregates that fit in registers, in one call, so the classification of each one is
 * checked with the register file already partly spent. */
struct two_int h_small_aggregates(struct one_char a0, struct three_char a1, struct two_int a2, struct int_float a3);

/* The homogeneous floating point aggregates, which are the ones AAPCS64 puts in vector registers
 * and SysV packs into SSE eightbytes. */
struct four_float h_float_aggregates(struct two_float a0, struct four_float a1, struct two_double a2);

/* The aggregate that is too large for registers, with an integer either side of it, so a caller
 * that forgets it left a copy behind puts the next argument in the wrong place. */
struct six_int h_memory_aggregate(int a0, struct six_int a1, int a2);

/* A large aggregate returned, which every ABI here does by giving the callee the address to
 * write it to. That address is an argument nobody wrote, so it moves every other one. */
struct six_int h_returns_by_hidden_pointer(int a0, double a1);

/* A function returning void with arguments that fill the registers, because the return value is
 * what an ABI spends a register on before the arguments and this is the case where it does not. */
void h_returns_nothing(struct two_int a0, double a1, long double a2, void *a3);

/* A long double between two integers, which is the type whose size, alignment and format all
 * move between rows of the table. */
long double h_long_double_and_friends(int a0, long double a1, int a2);

/* The nested aggregate and the union, which are the two shapes a classification rule has to
 * flatten before it can decide anything. */
union int_or_float h_nested_and_union(struct nested a0, union int_or_float a1, struct int_pointer a2);

unsigned char g00(unsigned short a0, long double a1, int a2);
unsigned short g01(float a0, long double a1, struct long_double_one a2, char a3, struct one_char a4, struct three_char a5);
float g02(struct two_double a0, long a1, unsigned int a2, long a3, void *a4, struct two_double a5, long double a6, unsigned int a7);
unsigned short g03(struct long_double_one a0, char a1, char a2, struct two_double a3, unsigned int a4, void *a5);
void g04(char a0, short a1);
short g05(double a0, float a1, long double a2, long a3, struct two_int a4, struct two_double a5);
unsigned int g06(void);
struct three_char g07(long double a0, struct int_pointer a1, unsigned short a2, void *a3);
struct long_double_one g08(unsigned long a0, int a1, long double a2, unsigned char a3);
void g09(struct int_pointer a0, unsigned int a1, char a2);
unsigned short g10(struct nested a0, struct two_int a1, long double a2, long long a3);
struct two_float g11(unsigned short a0, unsigned int a1, struct nested a2, char a3);
short g12(double a0, struct two_int a1, struct six_int a2, long a3, struct int_pointer a4);
struct int_pointer g13(signed char a0, long a1, long long a2, int a3, signed char a4, struct two_int a5, unsigned int a6, unsigned char a7);
unsigned long long g14(void);
void g15(unsigned long long a0, double a1, long a2, double a3);
struct nested g16(struct long_double_one a0, signed char a1, unsigned char a2, long double a3, void *a4, long long a5);
long long g17(unsigned char a0, struct nested a1, struct two_int a2, struct one_char a3, double a4, unsigned int a5, struct two_float a6);
struct two_float g18(unsigned int a0, struct two_int a1, unsigned int a2);
unsigned short g19(struct two_double a0, unsigned long long a1, struct two_int a2, short a3);
unsigned long g20(void);
signed char g21(long double a0, long a1, struct two_double a2, void *a3);
struct long_double_one g22(float a0, char a1);
long g23(unsigned long a0, union int_or_float a1, unsigned long long a2, char a3, signed char a4, unsigned long a5, struct three_char a6, unsigned long long a7);
signed char g24(void *a0, unsigned short a1);
signed char g25(double a0, float a1, double a2, unsigned long long a3, unsigned long long a4, char a5);
char g26(struct int_float a0, struct three_char a1, double a2, int a3, long a4);
struct int_pointer g27(unsigned long a0, float a1, unsigned int a2, long double a3, struct three_char a4, struct int_pointer a5);
int g28(long long a0, struct nested a1, long long a2, double a3, short a4, signed char a5);
long long g29(void *a0, unsigned char a1);
struct nested g30(struct two_double a0, unsigned long long a1, unsigned short a2, union int_or_float a3, unsigned int a4, char a5);
void *g31(struct six_int a0, short a1, unsigned short a2, int a3, float a4);
unsigned long g32(long a0, struct four_float a1, char a2, double a3, unsigned char a4, struct int_float a5, struct long_double_one a6, struct int_float a7);
struct one_char g33(unsigned short a0, void *a1, int a2, unsigned long a3);
unsigned char g34(unsigned int a0, struct int_pointer a1, double a2, union int_or_float a3, short a4, struct int_pointer a5, short a6);
long g35(void);
unsigned int g36(unsigned long a0, float a1, struct nested a2, long double a3, long double a4, void *a5, void *a6);
void g37(void);
struct two_int g38(short a0, unsigned long a1, unsigned int a2);
long g39(struct int_pointer a0, void *a1, signed char a2, long a3, struct one_char a4, struct int_float a5);
unsigned short g40(double a0, struct six_int a1, struct one_char a2);
void g41(struct two_int a0, union int_or_float a1, double a2, struct two_int a3, struct four_float a4);
struct int_pointer g42(struct two_double a0, void *a1, signed char a2);
unsigned long long g43(void *a0, unsigned long a1, struct three_char a2, int a3, unsigned int a4, double a5);
void g44(struct two_double a0, struct six_int a1);
double g45(float a0, unsigned long long a1, unsigned long long a2);
int g46(signed char a0, signed char a1, struct nested a2, long a3, short a4, long double a5, double a6, short a7);
unsigned short g47(long double a0, struct six_int a1, char a2, unsigned int a3, unsigned short a4, struct int_float a5, float a6, struct int_pointer a7);

#endif
