/* The calls, which pass what the callee expects and check what came back.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-signatures --write`. Do not edit
 * this file, edit the grammar in `build-tools/rucc-targets/src/signatures.rs`.
 *
 * This is the differential ABI harness of `spec/cross-compile/14-testing.md` section
 * 14.3. `callee.c` is compiled by one compiler and `caller.c` by the other, the two are
 * linked together and the program is run, so a value that arrives wrong is the two
 * compilers disagreeing about a calling convention rather than about a layout.
 *
 * The program prints nothing and exits zero when the two agree. Every disagreement
 * prints the function and the parameter it is about, and the exit status is one.
 */

#include "abi.h"

int main(void)
{
	{
		long long r = h_ints_past_the_registers(298157658234721LL, 596315316469441LL, 894472974704161LL, 1192630632938881LL, 1490788291173601LL, 1788945949408321LL, 2087103607643041LL, 2385261265877761LL, 2683418924112481LL, 2981576582347201LL);
		if (r != 3279734240581921LL)
			abi_fail("h_ints_past_the_registers", "return");
	}
	{
		double r = h_doubles_past_the_registers(13.25, 14.25, 15.25, 16.25, 17.25, 18.25, 19.25, 20.25, 21.25, 22.25);
		if (r != 23.25)
			abi_fail("h_doubles_past_the_registers", "return");
	}
	{
		int r = h_mixed_past_the_registers(182138, 25.25, 197976, 27.25, 213814, 29.25, 229652, 31.25, 245490, 33.25, 261328, 35.25);
		if (r != 277166)
			abi_fail("h_mixed_past_the_registers", "return");
	}
	{
		struct one_char a0 = { (char)(37) };
		struct three_char a1 = { (char)(38), (char)(39), (char)(40) };
		struct two_int a2 = { 316761, 324680 };
		struct int_float a3 = { 332599, 44.25f };
		struct two_int r = h_small_aggregates(a0, a1, a2, a3);
		if (r.a != 348437)
			abi_fail("h_small_aggregates", "return.a");
		if (r.b != 356356)
			abi_fail("h_small_aggregates", "return.b");
	}
	{
		struct two_float a0 = { 47.25f, 48.25f };
		struct four_float a1 = { 49.25f, 50.25f, 51.25f, 52.25f };
		struct two_double a2 = { 53.25, 54.25 };
		struct four_float r = h_float_aggregates(a0, a1, a2);
		if (r.a != 55.25f)
			abi_fail("h_float_aggregates", "return.a");
		if (r.b != 56.25f)
			abi_fail("h_float_aggregates", "return.b");
		if (r.c != 57.25f)
			abi_fail("h_float_aggregates", "return.c");
		if (r.d != 58.25f)
			abi_fail("h_float_aggregates", "return.d");
	}
	{
		struct six_int a1 = { 467222, 475141, 483060, 490979, 498898, 506817 };
		struct six_int r = h_memory_aggregate(459303, a1, 514736);
		if (r.a != 522655)
			abi_fail("h_memory_aggregate", "return.a");
		if (r.b != 530574)
			abi_fail("h_memory_aggregate", "return.b");
		if (r.c != 538493)
			abi_fail("h_memory_aggregate", "return.c");
		if (r.d != 546412)
			abi_fail("h_memory_aggregate", "return.d");
		if (r.e != 554331)
			abi_fail("h_memory_aggregate", "return.e");
		if (r.f != 562250)
			abi_fail("h_memory_aggregate", "return.f");
	}
	{
		struct six_int r = h_returns_by_hidden_pointer(570169, 74.25);
		if (r.a != 586007)
			abi_fail("h_returns_by_hidden_pointer", "return.a");
		if (r.b != 593926)
			abi_fail("h_returns_by_hidden_pointer", "return.b");
		if (r.c != 601845)
			abi_fail("h_returns_by_hidden_pointer", "return.c");
		if (r.d != 609764)
			abi_fail("h_returns_by_hidden_pointer", "return.d");
		if (r.e != 617683)
			abi_fail("h_returns_by_hidden_pointer", "return.e");
		if (r.f != 625602)
			abi_fail("h_returns_by_hidden_pointer", "return.f");
	}
	{
		struct two_int a0 = { 633521, 641440 };
		h_returns_nothing(a0, 83.25, 84.25L, (void *)&anchor[20]);
	}
	{
		long double r = h_long_double_and_friends(673116, 87.25L, 688954);
		if (r != 89.25L)
			abi_fail("h_long_double_and_friends", "return");
	}
	{
		struct nested a0 = { { 704792, 712711 }, 92.25f };
		union int_or_float a1 = { 728549 };
		struct int_pointer a2 = { 736468, (void *)&anchor[30] };
		union int_or_float r = h_nested_and_union(a0, a1, a2);
		if (r.a != 752306)
			abi_fail("h_nested_and_union", "return.a");
	}
	{
		unsigned char r = g00((unsigned short)(97), 98.25L, 776063);
		if (r != (unsigned char)(100))
			abi_fail("g00", "return");
	}
	{
		struct long_double_one a2 = { 103.25L };
		struct one_char a4 = { (char)(5) };
		struct three_char a5 = { (char)(6), (char)(7), (char)(8) };
		unsigned short r = g01(101.25f, 102.25L, a2, (char)(4), a4, a5);
		if (r != (unsigned short)(109))
			abi_fail("g01", "return");
	}
	{
		struct two_double a0 = { 110.25, 111.25 };
		struct two_double a5 = { 116.25, 117.25 };
		float r = g02(a0, 879010L, 886929u, 894848L, (void *)&anchor[50], a5, 118.25L, 934443u);
		if (r != 120.25f)
			abi_fail("g02", "return");
	}
	{
		struct long_double_one a0 = { 121.25L };
		struct two_double a3 = { 124.25, 125.25 };
		unsigned short r = g03(a0, (char)(22), (char)(23), a3, 989876u, (void *)&anchor[62]);
		if (r != (unsigned short)(128))
			abi_fail("g03", "return");
	}
	{
		g04((char)(29), (short)(130));
	}
	{
		struct two_int a4 = { 1061147, 1069066 };
		struct two_double a5 = { 137.25, 138.25 };
		short r = g05(131.25, 132.25f, 133.25L, 1053228L, a4, a5);
		if (r != (short)(139))
			abi_fail("g05", "return");
	}
	{
		unsigned int r = g06();
		if (r != 1100742u)
			abi_fail("g06", "return");
	}
	{
		struct int_pointer a1 = { 1116580, (void *)&anchor[14] };
		struct three_char r = g07(141.25L, a1, (unsigned short)(144), (void *)&anchor[16]);
		if (r.a != (char)(46))
			abi_fail("g07", "return.a");
		if (r.b != (char)(47))
			abi_fail("g07", "return.b");
		if (r.c != (char)(48))
			abi_fail("g07", "return.c");
	}
	{
		struct long_double_one r = g08(1172013UL, 1179932, 151.25L, (unsigned char)(152));
		if (r.a != 153.25L)
			abi_fail("g08", "return.a");
	}
	{
		struct int_pointer a0 = { 1211608, (void *)&anchor[26] };
		g09(a0, 1227446u, (char)(57));
	}
	{
		struct nested a0 = { { 1243284, 1251203 }, 160.25f };
		struct two_int a1 = { 1267041, 1274960 };
		unsigned short r = g10(a0, a1, 163.25L, 3599698292259361LL);
		if (r != (unsigned short)(165))
			abi_fail("g10", "return");
	}
	{
		struct nested a2 = { { 1322474, 1330393 }, 170.25f };
		struct two_float r = g11((unsigned short)(166), 1314555u, a2, (char)(71));
		if (r.a != 172.25f)
			abi_fail("g11", "return.a");
		if (r.b != 173.25f)
			abi_fail("g11", "return.b");
	}
	{
		struct two_int a1 = { 1377907, 1385826 };
		struct six_int a2 = { 1393745, 1401664, 1409583, 1417502, 1425421, 1433340 };
		struct int_pointer a4 = { 1449178, (void *)&anchor[56] };
		short r = g12(174.25, a1, a2, 1441259L, a4);
		if (r != (short)(186))
			abi_fail("g12", "return");
	}
	{
		struct two_int a5 = { 1512530, 1520449 };
		struct int_pointer r = g13((signed char)(87), 1480854L, 2053639748127361LL, 1496692, (signed char)(91), a5, 1528368u, (unsigned char)(195));
		if (r.a != 1544206)
			abi_fail("g13", "return.a");
		if (r.b != (void *)&anchor[4])
			abi_fail("g13", "return.b");
	}
	{
		unsigned long long r = g14();
		if (r != 4737058672239841ULL)
			abi_fail("g14", "return");
	}
	{
		g15(5035216330474561ULL, 200.25, 1583801L, 202.25);
	}
	{
		struct long_double_one a0 = { 203.25L };
		struct nested r = g16(a0, (signed char)(4), (unsigned char)(205), 206.25L, (void *)&anchor[14], 7718635254587041LL);
		if (r.a.a != 1647153)
			abi_fail("g16", "return.a.a");
		if (r.a.b != 1655072)
			abi_fail("g16", "return.a.b");
		if (r.b != 211.25f)
			abi_fail("g16", "return.b");
	}
	{
		struct nested a1 = { { 1678829, 1686748 }, 215.25f };
		struct two_int a2 = { 1702586, 1710505 };
		struct one_char a3 = { (char)(18) };
		struct two_float a6 = { 221.25f, 222.25f };
		long long r = g17((unsigned char)(212), a1, a2, a3, 219.25, 1734262u, a6);
		if (r != 3191000128107841LL)
			abi_fail("g17", "return");
	}
	{
		struct two_int a1 = { 1773857, 1781776 };
		struct two_float r = g18(1765938u, a1, 1789695u);
		if (r.a != 228.25f)
			abi_fail("g18", "return.a");
		if (r.b != 229.25f)
			abi_fail("g18", "return.b");
	}
	{
		struct two_double a0 = { 230.25, 231.25 };
		struct two_int a2 = { 1837209, 1845128 };
		unsigned short r = g19(a0, 14874419052220321ULL, a2, (short)(235));
		if (r != (unsigned short)(236))
			abi_fail("g19", "return");
	}
	{
		unsigned long r = g20();
		if (r != 1868885UL)
			abi_fail("g20", "return");
	}
	{
		struct two_double a2 = { 240.25, 241.25 };
		signed char r = g21(238.25L, 1884723L, a2, (void *)&anchor[49]);
		if (r != (signed char)(43))
			abi_fail("g21", "return");
	}
	{
		struct long_double_one r = g22(244.25f, (char)(45));
		if (r.a != 246.25L)
			abi_fail("g22", "return.a");
	}
	{
		union int_or_float a1 = { 1955994 };
		struct three_char a6 = { (char)(53), (char)(54), (char)(55) };
		long r = g23(1948075UL, a1, 1943099242210561ULL, (char)(50), (signed char)(51), 1987670UL, a6, 4030202849853601ULL);
		if (r != 2027265L)
			abi_fail("g23", "return");
	}
	{
		signed char r = g24((void *)&anchor[1], (unsigned short)(259));
		if (r != (signed char)(60))
			abi_fail("g24", "return");
	}
	{
		signed char r = g25(261.25, 262.25f, 263.25, 6415464115731361ULL, 6713621773966081ULL, (char)(66));
		if (r != (signed char)(67))
			abi_fail("g25", "return");
	}
	{
		struct int_float a0 = { 2114374, 269.25f };
		struct three_char a1 = { (char)(70), (char)(71), (char)(72) };
		char r = g26(a0, a1, 273.25, 2161888, 2169807L);
		if (r != (char)(76))
			abi_fail("g26", "return");
	}
	{
		struct three_char a4 = { (char)(81), (char)(82), (char)(83) };
		struct int_pointer a5 = { 2241078, (void *)&anchor[28] };
		struct int_pointer r = g27(2185645UL, 278.25f, 2201483u, 280.25L, a4, a5);
		if (r.a != 2256916)
			abi_fail("g27", "return.a");
		if (r.b != (void *)&anchor[30])
			abi_fail("g27", "return.b");
	}
	{
		struct nested a1 = { { 2280673, 2288592 }, 291.25f };
		int r = g28(4571247913364641LL, a1, 5763878546303521LL, 293.25, (short)(294), (signed char)(95));
		if (r != 2336106)
			abi_fail("g28", "return");
	}
	{
		long long r = g29((void *)&anchor[40], (unsigned char)(58));
		if (r != 7850982153946561LL)
			abi_fail("g29", "return");
	}
	{
		struct two_double a0 = { 300.25, 301.25 };
		union int_or_float a3 = { 2399458 };
		struct nested r = g30(a0, 17745455128650721ULL, (unsigned short)(303), a3, 2407377u, (char)(6));
		if (r.a.a != 2423215)
			abi_fail("g30", "return.a.a");
		if (r.a.b != 2431134)
			abi_fail("g30", "return.a.b");
		if (r.b != 309.25f)
			abi_fail("g30", "return.b");
	}
	{
		struct six_int a0 = { 2446972, 2454891, 2462810, 2470729, 2478648, 2486567 };
		void *r = g31(a0, (short)(316), (unsigned short)(317), 2510324, 319.25f);
		if (r != (void *)&anchor[63])
			abi_fail("g31", "return");
	}
	{
		struct four_float a1 = { 322.25f, 323.25f, 324.25f, 325.25f };
		struct int_float a5 = { 2597433, 330.25f };
		struct long_double_one a6 = { 331.25L };
		struct int_float a7 = { 2621190, 333.25f };
		unsigned long r = g32(2534081L, a1, (char)(26), 327.25, (unsigned char)(88), a5, a6, a7);
		if (r != 2637028UL)
			abi_fail("g32", "return");
	}
	{
		struct one_char r = g33((unsigned short)(335), (void *)&anchor[15], 2660785, 2668704UL);
		if (r.a != (char)(39))
			abi_fail("g33", "return.a");
	}
	{
		struct int_pointer a1 = { 2692461, (void *)&anchor[21] };
		union int_or_float a3 = { 2716218 };
		struct int_pointer a5 = { 2732056, (void *)&anchor[26] };
		unsigned char r = g34(2684542u, a1, 343.25, a3, (short)(345), a5, (short)(348));
		if (r != (unsigned char)(109))
			abi_fail("g34", "return");
	}
	{
		long r = g35();
		if (r != 2763732L)
			abi_fail("g35", "return");
	}
	{
		struct nested a2 = { { 2787489, 2795408 }, 355.25f };
		unsigned int r = g36(2771651UL, 352.25f, a2, 356.25L, 357.25L, (void *)&anchor[37], (void *)&anchor[38]);
		if (r != 2842922u)
			abi_fail("g36", "return");
	}
	{
		g37();
	}
	{
		struct two_int r = g38((short)(361), 2858760UL, 2866679u);
		if (r.a != 2874598)
			abi_fail("g38", "return.a");
		if (r.b != 2882517)
			abi_fail("g38", "return.b");
	}
	{
		struct int_pointer a0 = { 2890436, (void *)&anchor[46] };
		struct one_char a4 = { (char)(71) };
		struct int_float a5 = { 2937950, 373.25f };
		long r = g39(a0, (void *)&anchor[47], (signed char)(69), 2922112L, a4, a5);
		if (r != 2953788L)
			abi_fail("g39", "return");
	}
	{
		struct six_int a1 = { 2969626, 2977545, 2985464, 2993383, 3001302, 3009221 };
		struct one_char a2 = { (char)(82) };
		unsigned short r = g40(375.25, a1, a2);
		if (r != (unsigned short)(383))
			abi_fail("g40", "return");
	}
	{
		struct two_int a0 = { 3032978, 3040897 };
		union int_or_float a1 = { 3048816 };
		struct two_int a3 = { 3064654, 3072573 };
		struct four_float a4 = { 390.25f, 391.25f, 392.25f, 393.25f };
		g41(a0, a1, 387.25, a3, a4);
	}
	{
		struct two_double a0 = { 394.25, 395.25 };
		struct int_pointer r = g42(a0, (void *)&anchor[11], (signed char)(97));
		if (r.a != 3143844)
			abi_fail("g42", "return.a");
		if (r.b != (void *)&anchor[14])
			abi_fail("g42", "return.b");
	}
	{
		struct three_char a2 = { (char)(2), (char)(3), (char)(4) };
		unsigned long long r = g43((void *)&anchor[15], 3167601UL, a2, 3199277, 3207196u, 407.25);
		if (r != 13350166901531041ULL)
			abi_fail("g43", "return");
	}
	{
		struct two_double a0 = { 409.25, 410.25 };
		struct six_int a1 = { 3246791, 3254710, 3262629, 3270548, 3278467, 3286386 };
		g44(a0, a1);
	}
	{
		double r = g45(417.25f, 16331743483878241ULL, 16629901142112961ULL);
		if (r != 420.25)
			abi_fail("g45", "return");
	}
	{
		struct nested a2 = { { 3341819, 3349738 }, 425.25f };
		int r = g46((signed char)(21), (signed char)(22), a2, 3365576L, (short)(427), 428.25L, 429.25, (short)(430));
		if (r != 3405171)
			abi_fail("g46", "return");
	}
	{
		struct six_int a1 = { 3421009, 3428928, 3436847, 3444766, 3452685, 3460604 };
		struct int_float a5 = { 3492280, 443.25f };
		struct int_pointer a7 = { 3516037, (void *)&anchor[61] };
		unsigned short r = g47(432.25L, a1, (char)(39), 3476442u, (unsigned short)(441), a5, 444.25f, a7);
		if (r != (unsigned short)(447))
			abi_fail("g47", "return");
	}
	{
		long long r = hv_ints_past_the_registers(3539794, 7574630889154561LL, 7872788547389281LL, 8170946205624001LL, 8469103863858721LL, 8767261522093441LL, 65419180328161LL, 363576838562881LL, 661734496797601LL, 959892155032321LL, 1258049813267041LL);
		if (r != 1556207471501761LL)
			abi_fail("hv_ints_past_the_registers", "return");
	}
	{
		double r = hv_doubles_past_the_registers(3634822, 461.25, 462.25, 463.25, 464.25, 465.25, 466.25, 467.25, 468.25, 469.25, 470.25);
		if (r != 471.25)
			abi_fail("hv_doubles_past_the_registers", "return");
	}
	{
		int r = hv_mixed_past_the_registers(3729850, 3737769, 474.25, 3753607, 476.25, 3769445, 478.25, 3785283, 480.25, 3801121, 482.25, 3816959, 484.25);
		if (r != 3832797)
			abi_fail("hv_mixed_past_the_registers", "return");
	}
	{
		int r = hv_promotions(3840716, (char)(87), (signed char)(88), (unsigned char)(9), (short)(490), (unsigned short)(491), 492.25f);
		if (r != 3896149)
			abi_fail("hv_promotions", "return");
	}
	{
		struct two_float v0 = { 495.25f, 496.25f };
		struct four_float v1 = { 497.25f, 498.25f, 499.25f, 500.25f };
		struct two_double v2 = { 501.25, 502.25 };
		struct four_float r = hv_float_aggregates(3904068, v0, v1, v2);
		if (r.a != 503.25f)
			abi_fail("hv_float_aggregates", "return.a");
		if (r.b != 504.25f)
			abi_fail("hv_float_aggregates", "return.b");
		if (r.c != 505.25f)
			abi_fail("hv_float_aggregates", "return.c");
		if (r.d != 506.25f)
			abi_fail("hv_float_aggregates", "return.d");
	}
	{
		struct one_char v0 = { (char)(8) };
		struct three_char v1 = { (char)(9), (char)(10), (char)(11) };
		struct two_int v2 = { 4046610, 4054529 };
		struct int_float v3 = { 4062448, 515.25f };
		struct two_int r = hv_small_aggregates(4007015, v0, v1, v2, v3);
		if (r.a != 4078286)
			abi_fail("hv_small_aggregates", "return.a");
		if (r.b != 4086205)
			abi_fail("hv_small_aggregates", "return.b");
	}
	{
		struct six_int v1 = { 4109962, 4117881, 4125800, 4133719, 4141638, 4149557 };
		int r = hv_memory_aggregate(4094124, 4102043, v1, 4157476);
		if (r != 4165395)
			abi_fail("hv_memory_aggregate", "return");
	}
	{
		struct six_int r = hv_returns_by_hidden_pointer(4173314, 529.25, 4725401206166881LL);
		if (r.a != 4197071)
			abi_fail("hv_returns_by_hidden_pointer", "return.a");
		if (r.b != 4204990)
			abi_fail("hv_returns_by_hidden_pointer", "return.b");
		if (r.c != 4212909)
			abi_fail("hv_returns_by_hidden_pointer", "return.c");
		if (r.d != 4220828)
			abi_fail("hv_returns_by_hidden_pointer", "return.d");
		if (r.e != 4228747)
			abi_fail("hv_returns_by_hidden_pointer", "return.e");
		if (r.f != 4236666)
			abi_fail("hv_returns_by_hidden_pointer", "return.f");
	}
	{
		hv_long_double_and_friends(4244585, 4252504, 539.25L, 4268342, 541.25L);
	}
	{
		struct two_int v2 = { 4363370, 4371289 };
		int r = hv_registers_already_spent(8303293104983521LL, 8601450763218241LL, 8899608421452961LL, 197766079687681LL, 495923737922401LL, 794081396157121LL, 1092239054391841LL, 1390396712626561LL, 1688554370861281LL, 551.25, v2);
		if (r != 4379208)
			abi_fail("hv_registers_already_spent", "return");
	}
	{
		struct long_double_one v1 = { 558.25L };
		unsigned long r = v00(4387127L, 4395046, 557.25L, v1, (signed char)(59), (void *)&anchor[47]);
		if (r != 4434641UL)
			abi_fail("v00", "return");
	}
	{
		struct four_float a0 = { 562.25f, 563.25f, 564.25f, 565.25f };
		int r = v01(a0, (signed char)(66), (void *)&anchor[54]);
		if (r != 4490074)
			abi_fail("v01", "return");
	}
	{
		struct int_float v0 = { 4505912, 571.25f };
		struct nested v1 = { { 4521750, 4529669 }, 574.25f };
		char r = v02(4497993, v0, v1);
		if (r != (char)(75))
			abi_fail("v02", "return");
	}
	{
		struct three_char v0 = { (char)(78), (char)(79), (char)(80) };
		signed char r = v03((signed char)(76), 577.25, v0, (char)(81));
		if (r != (signed char)(82))
			abi_fail("v03", "return");
	}
	{
		union int_or_float a0 = { 4608859 };
		union int_or_float v0 = { 4616778 };
		v04(a0, v0);
	}
	{
		struct long_double_one a2 = { 587.25L };
		struct one_char v1 = { (char)(89) };
		int r = v05(12124072409076481ULL, 4632616, a2, (unsigned char)(108), v1, 4664292u, 4672211UL);
		if (r != 4680130)
			abi_fail("v05", "return");
	}
	{
		struct int_float a0 = { 4688049, 594.25f };
		struct three_char r = v06(a0, 4703887, (unsigned short)(596), 4719725);
		if (r.a != (char)(98))
			abi_fail("v06", "return.a");
		if (r.b != (char)(99))
			abi_fail("v06", "return.b");
		if (r.c != (char)(100))
			abi_fail("v06", "return.c");
	}
	{
		union int_or_float a1 = { 4759320 };
		struct two_int a2 = { 4767239, 4775158 };
		struct two_int v1 = { 4790996, 4798915 };
		long double r = v07((unsigned char)(121), a1, a2, 4783077UL, v1);
		if (r != 608.25L)
			abi_fail("v07", "return");
	}
	{
		struct two_int a1 = { 4822672, 4830591 };
		struct four_float a2 = { 612.25f, 613.25f, 614.25f, 615.25f };
		double r = v08(609.25L, a1, a2, 4870186L);
		if (r != 617.25)
			abi_fail("v08", "return");
	}
	{
		struct one_char a0 = { (char)(18) };
		struct two_int v0 = { 4893943, 4901862 };
		struct one_char v1 = { (char)(21) };
		unsigned long r = v09(a0, v0, v1, (short)(622), 623.25L, 624.25f, 4941457L);
		if (r != 4949376UL)
			abi_fail("v09", "return");
	}
	{
		struct four_float a2 = { 629.25f, 630.25f, 631.25f, 632.25f };
		struct one_char v2 = { (char)(35) };
		struct four_float r = v10((unsigned char)(147), (void *)&anchor[51], a2, 8435640004343041ULL, 634.25L, v2, 5028566L, 628270637281921LL, (signed char)(38));
		if (r.a != 639.25f)
			abi_fail("v10", "return.a");
		if (r.b != 640.25f)
			abi_fail("v10", "return.b");
		if (r.c != 641.25f)
			abi_fail("v10", "return.c");
		if (r.d != 642.25f)
			abi_fail("v10", "return.d");
	}
	{
		struct int_float a0 = { 5083999, 644.25f };
		int r = v11(a0, (unsigned short)(645), 5107756, 5115675, 12908004877863841ULL);
		if (r != 5131513)
			abi_fail("v11", "return");
	}
	{
		struct int_pointer v1 = { 5163189, (void *)&anchor[13] };
		long double r = v12((void *)&anchor[9], 5147351L, (signed char)(52), v1, 655.25f);
		if (r != 656.25L)
			abi_fail("v12", "return");
	}
	{
		struct four_float r = v13(5194865, 5202784, (char)(59), 16485896776680481ULL, (unsigned char)(181));
		if (r.a != 662.25f)
			abi_fail("v13", "return.a");
		if (r.b != 663.25f)
			abi_fail("v13", "return.b");
		if (r.c != 664.25f)
			abi_fail("v13", "return.c");
		if (r.d != 665.25f)
			abi_fail("v13", "return.d");
	}
	{
		struct three_char a0 = { (char)(66), (char)(67), (char)(68) };
		struct three_char v0 = { (char)(70), (char)(71), (char)(72) };
		struct int_float v3 = { 5337407, 676.25f };
		struct three_char v5 = { (char)(78), (char)(79), (char)(80) };
		v14(a0, 5289893u, v0, 5321569, (char)(74), v3, (unsigned short)(677), v5);
	}
	{
		struct long_double_one a1 = { 682.25L };
		struct four_float v5 = { 689.25f, 690.25f, 691.25f, 692.25f };
		char r = v15(5384921L, a1, (void *)&anchor[42], (unsigned short)(684), 5416597, 686.25, (unsigned short)(687), 5440354L, v5);
		if (r != (char)(93))
			abi_fail("v15", "return");
	}
	{
		struct long_double_one v0 = { 695.25L };
		struct four_float v1 = { 696.25f, 697.25f, 698.25f, 699.25f };
		struct two_double v2 = { 700.25, 701.25 };
		struct long_double_one v3 = { 702.25L };
		union int_or_float v4 = { 5559139 };
		signed char r = v16(5487868, v0, v1, v2, v3, v4, 5567058u);
		if (r != (signed char)(5))
			abi_fail("v16", "return");
	}
	{
		union int_or_float a0 = { 5582896 };
		struct int_pointer v1 = { 5614572, (void *)&anchor[6] };
		struct one_char r = v17(a0, (unsigned char)(227), 5598734u, 709.25, v1);
		if (r.a != (char)(12))
			abi_fail("v17", "return.a");
	}
	{
		struct long_double_one v2 = { 716.25L };
		long long r = v18(5638329L, 14586410321355361ULL, (unsigned short)(715), v2, 5670005u, (unsigned char)(238));
		if (r != 7077198612528961LL)
			abi_fail("v18", "return");
	}
	{
		struct six_int v0 = { 5701681, 5709600, 5717519, 5725438, 5733357, 5741276 };
		unsigned int r = v19(5693762u, v0, 727.25f, (signed char)(28));
		if (r != 5765033u)
			abi_fail("v19", "return");
	}
	{
		struct int_float a0 = { 5772952, 731.25f };
		struct int_float v0 = { 5788790, 733.25f };
		struct one_char v2 = { (char)(35) };
		v20(a0, v0, (signed char)(34), v2);
	}
	{
		struct int_pointer a0 = { 5820466, (void *)&anchor[32] };
		struct int_pointer r = v21(a0, (signed char)(38));
		if (r.a != 5844223)
			abi_fail("v21", "return.a");
		if (r.b != (void *)&anchor[35])
			abi_fail("v21", "return.b");
	}
	{
		struct two_float a0 = { 741.25f, 742.25f };
		struct four_float v2 = { 745.25f, 746.25f, 747.25f, 748.25f };
		struct six_int v3 = { 5923413, 5931332, 5939251, 5947170, 5955089, 5963008 };
		unsigned char r = v22(a0, 743.25, 744.25, v2, v3);
		if (r != (unsigned char)(35))
			abi_fail("v22", "return");
	}
	{
		struct nested a0 = { { 5978846, 5986765 }, 758.25f };
		struct six_int v0 = { 6002603, 6010522, 6018441, 6026360, 6034279, 6042198 };
		struct two_double v1 = { 765.25, 766.25 };
		short r = v23(a0, v0, v1);
		if (r != (short)(767))
			abi_fail("v23", "return");
	}
	return abi_failures == 0 ? 0 : 1;
}
