/* The definitions, which check what arrived and return what is expected.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-signatures --write`. Do not edit
 * this file, edit the grammar in `build-tools/rucc-targets/src/signatures.rs`.
 *
 * This is the differential ABI harness of `spec/cross-compile/14-testing.md` section
 * 14.3. `callee.c` is compiled by one compiler and `caller.c` by the other, the two are
 * linked together and the program is run, so a value that arrives wrong is the two
 * compilers disagreeing about a calling convention rather than about a layout.
 *
 * The program prints nothing and exits zero when the two agree. Every disagreement
 * prints the function and the parameter it is about, and the exit status is one.
 */

#include "abi.h"

long long h_ints_past_the_registers(long long a0, long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, long long a8, long long a9)
{
	if (a0 != 298157658234721LL)
		abi_fail("h_ints_past_the_registers", "a0");
	if (a1 != 596315316469441LL)
		abi_fail("h_ints_past_the_registers", "a1");
	if (a2 != 894472974704161LL)
		abi_fail("h_ints_past_the_registers", "a2");
	if (a3 != 1192630632938881LL)
		abi_fail("h_ints_past_the_registers", "a3");
	if (a4 != 1490788291173601LL)
		abi_fail("h_ints_past_the_registers", "a4");
	if (a5 != 1788945949408321LL)
		abi_fail("h_ints_past_the_registers", "a5");
	if (a6 != 2087103607643041LL)
		abi_fail("h_ints_past_the_registers", "a6");
	if (a7 != 2385261265877761LL)
		abi_fail("h_ints_past_the_registers", "a7");
	if (a8 != 2683418924112481LL)
		abi_fail("h_ints_past_the_registers", "a8");
	if (a9 != 2981576582347201LL)
		abi_fail("h_ints_past_the_registers", "a9");
	return 3279734240581921LL;
}

double h_doubles_past_the_registers(double a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9)
{
	if (a0 != 13.25)
		abi_fail("h_doubles_past_the_registers", "a0");
	if (a1 != 14.25)
		abi_fail("h_doubles_past_the_registers", "a1");
	if (a2 != 15.25)
		abi_fail("h_doubles_past_the_registers", "a2");
	if (a3 != 16.25)
		abi_fail("h_doubles_past_the_registers", "a3");
	if (a4 != 17.25)
		abi_fail("h_doubles_past_the_registers", "a4");
	if (a5 != 18.25)
		abi_fail("h_doubles_past_the_registers", "a5");
	if (a6 != 19.25)
		abi_fail("h_doubles_past_the_registers", "a6");
	if (a7 != 20.25)
		abi_fail("h_doubles_past_the_registers", "a7");
	if (a8 != 21.25)
		abi_fail("h_doubles_past_the_registers", "a8");
	if (a9 != 22.25)
		abi_fail("h_doubles_past_the_registers", "a9");
	return 23.25;
}

int h_mixed_past_the_registers(int a0, double a1, int a2, double a3, int a4, double a5, int a6, double a7, int a8, double a9, int a10, double a11)
{
	if (a0 != 182138)
		abi_fail("h_mixed_past_the_registers", "a0");
	if (a1 != 25.25)
		abi_fail("h_mixed_past_the_registers", "a1");
	if (a2 != 197976)
		abi_fail("h_mixed_past_the_registers", "a2");
	if (a3 != 27.25)
		abi_fail("h_mixed_past_the_registers", "a3");
	if (a4 != 213814)
		abi_fail("h_mixed_past_the_registers", "a4");
	if (a5 != 29.25)
		abi_fail("h_mixed_past_the_registers", "a5");
	if (a6 != 229652)
		abi_fail("h_mixed_past_the_registers", "a6");
	if (a7 != 31.25)
		abi_fail("h_mixed_past_the_registers", "a7");
	if (a8 != 245490)
		abi_fail("h_mixed_past_the_registers", "a8");
	if (a9 != 33.25)
		abi_fail("h_mixed_past_the_registers", "a9");
	if (a10 != 261328)
		abi_fail("h_mixed_past_the_registers", "a10");
	if (a11 != 35.25)
		abi_fail("h_mixed_past_the_registers", "a11");
	return 277166;
}

struct two_int h_small_aggregates(struct one_char a0, struct three_char a1, struct two_int a2, struct int_float a3)
{
	if (a0.a != (char)(37))
		abi_fail("h_small_aggregates", "a0.a");
	if (a1.a != (char)(38))
		abi_fail("h_small_aggregates", "a1.a");
	if (a1.b != (char)(39))
		abi_fail("h_small_aggregates", "a1.b");
	if (a1.c != (char)(40))
		abi_fail("h_small_aggregates", "a1.c");
	if (a2.a != 316761)
		abi_fail("h_small_aggregates", "a2.a");
	if (a2.b != 324680)
		abi_fail("h_small_aggregates", "a2.b");
	if (a3.a != 332599)
		abi_fail("h_small_aggregates", "a3.a");
	if (a3.b != 44.25f)
		abi_fail("h_small_aggregates", "a3.b");
	struct two_int r = { 348437, 356356 };
	return r;
}

struct four_float h_float_aggregates(struct two_float a0, struct four_float a1, struct two_double a2)
{
	if (a0.a != 47.25f)
		abi_fail("h_float_aggregates", "a0.a");
	if (a0.b != 48.25f)
		abi_fail("h_float_aggregates", "a0.b");
	if (a1.a != 49.25f)
		abi_fail("h_float_aggregates", "a1.a");
	if (a1.b != 50.25f)
		abi_fail("h_float_aggregates", "a1.b");
	if (a1.c != 51.25f)
		abi_fail("h_float_aggregates", "a1.c");
	if (a1.d != 52.25f)
		abi_fail("h_float_aggregates", "a1.d");
	if (a2.a != 53.25)
		abi_fail("h_float_aggregates", "a2.a");
	if (a2.b != 54.25)
		abi_fail("h_float_aggregates", "a2.b");
	struct four_float r = { 55.25f, 56.25f, 57.25f, 58.25f };
	return r;
}

struct six_int h_memory_aggregate(int a0, struct six_int a1, int a2)
{
	if (a0 != 459303)
		abi_fail("h_memory_aggregate", "a0");
	if (a1.a != 467222)
		abi_fail("h_memory_aggregate", "a1.a");
	if (a1.b != 475141)
		abi_fail("h_memory_aggregate", "a1.b");
	if (a1.c != 483060)
		abi_fail("h_memory_aggregate", "a1.c");
	if (a1.d != 490979)
		abi_fail("h_memory_aggregate", "a1.d");
	if (a1.e != 498898)
		abi_fail("h_memory_aggregate", "a1.e");
	if (a1.f != 506817)
		abi_fail("h_memory_aggregate", "a1.f");
	if (a2 != 514736)
		abi_fail("h_memory_aggregate", "a2");
	struct six_int r = { 522655, 530574, 538493, 546412, 554331, 562250 };
	return r;
}

struct six_int h_returns_by_hidden_pointer(int a0, double a1)
{
	if (a0 != 570169)
		abi_fail("h_returns_by_hidden_pointer", "a0");
	if (a1 != 74.25)
		abi_fail("h_returns_by_hidden_pointer", "a1");
	struct six_int r = { 586007, 593926, 601845, 609764, 617683, 625602 };
	return r;
}

void h_returns_nothing(struct two_int a0, double a1, long double a2, void *a3)
{
	if (a0.a != 633521)
		abi_fail("h_returns_nothing", "a0.a");
	if (a0.b != 641440)
		abi_fail("h_returns_nothing", "a0.b");
	if (a1 != 83.25)
		abi_fail("h_returns_nothing", "a1");
	if (a2 != 84.25L)
		abi_fail("h_returns_nothing", "a2");
	if (a3 != (void *)&anchor[20])
		abi_fail("h_returns_nothing", "a3");
}

long double h_long_double_and_friends(int a0, long double a1, int a2)
{
	if (a0 != 673116)
		abi_fail("h_long_double_and_friends", "a0");
	if (a1 != 87.25L)
		abi_fail("h_long_double_and_friends", "a1");
	if (a2 != 688954)
		abi_fail("h_long_double_and_friends", "a2");
	return 89.25L;
}

union int_or_float h_nested_and_union(struct nested a0, union int_or_float a1, struct int_pointer a2)
{
	if (a0.a.a != 704792)
		abi_fail("h_nested_and_union", "a0.a.a");
	if (a0.a.b != 712711)
		abi_fail("h_nested_and_union", "a0.a.b");
	if (a0.b != 92.25f)
		abi_fail("h_nested_and_union", "a0.b");
	if (a1.a != 728549)
		abi_fail("h_nested_and_union", "a1.a");
	if (a2.a != 736468)
		abi_fail("h_nested_and_union", "a2.a");
	if (a2.b != (void *)&anchor[30])
		abi_fail("h_nested_and_union", "a2.b");
	union int_or_float r = { 752306 };
	return r;
}

unsigned char g00(unsigned short a0, long double a1, int a2)
{
	if (a0 != (unsigned short)(97))
		abi_fail("g00", "a0");
	if (a1 != 98.25L)
		abi_fail("g00", "a1");
	if (a2 != 776063)
		abi_fail("g00", "a2");
	return (unsigned char)(100);
}

unsigned short g01(float a0, long double a1, struct long_double_one a2, char a3, struct one_char a4, struct three_char a5)
{
	if (a0 != 101.25f)
		abi_fail("g01", "a0");
	if (a1 != 102.25L)
		abi_fail("g01", "a1");
	if (a2.a != 103.25L)
		abi_fail("g01", "a2.a");
	if (a3 != (char)(4))
		abi_fail("g01", "a3");
	if (a4.a != (char)(5))
		abi_fail("g01", "a4.a");
	if (a5.a != (char)(6))
		abi_fail("g01", "a5.a");
	if (a5.b != (char)(7))
		abi_fail("g01", "a5.b");
	if (a5.c != (char)(8))
		abi_fail("g01", "a5.c");
	return (unsigned short)(109);
}

float g02(struct two_double a0, long a1, unsigned int a2, long a3, void *a4, struct two_double a5, long double a6, unsigned int a7)
{
	if (a0.a != 110.25)
		abi_fail("g02", "a0.a");
	if (a0.b != 111.25)
		abi_fail("g02", "a0.b");
	if (a1 != 879010L)
		abi_fail("g02", "a1");
	if (a2 != 886929u)
		abi_fail("g02", "a2");
	if (a3 != 894848L)
		abi_fail("g02", "a3");
	if (a4 != (void *)&anchor[50])
		abi_fail("g02", "a4");
	if (a5.a != 116.25)
		abi_fail("g02", "a5.a");
	if (a5.b != 117.25)
		abi_fail("g02", "a5.b");
	if (a6 != 118.25L)
		abi_fail("g02", "a6");
	if (a7 != 934443u)
		abi_fail("g02", "a7");
	return 120.25f;
}

unsigned short g03(struct long_double_one a0, char a1, char a2, struct two_double a3, unsigned int a4, void *a5)
{
	if (a0.a != 121.25L)
		abi_fail("g03", "a0.a");
	if (a1 != (char)(22))
		abi_fail("g03", "a1");
	if (a2 != (char)(23))
		abi_fail("g03", "a2");
	if (a3.a != 124.25)
		abi_fail("g03", "a3.a");
	if (a3.b != 125.25)
		abi_fail("g03", "a3.b");
	if (a4 != 989876u)
		abi_fail("g03", "a4");
	if (a5 != (void *)&anchor[62])
		abi_fail("g03", "a5");
	return (unsigned short)(128);
}

void g04(char a0, short a1)
{
	if (a0 != (char)(29))
		abi_fail("g04", "a0");
	if (a1 != (short)(130))
		abi_fail("g04", "a1");
}

short g05(double a0, float a1, long double a2, long a3, struct two_int a4, struct two_double a5)
{
	if (a0 != 131.25)
		abi_fail("g05", "a0");
	if (a1 != 132.25f)
		abi_fail("g05", "a1");
	if (a2 != 133.25L)
		abi_fail("g05", "a2");
	if (a3 != 1053228L)
		abi_fail("g05", "a3");
	if (a4.a != 1061147)
		abi_fail("g05", "a4.a");
	if (a4.b != 1069066)
		abi_fail("g05", "a4.b");
	if (a5.a != 137.25)
		abi_fail("g05", "a5.a");
	if (a5.b != 138.25)
		abi_fail("g05", "a5.b");
	return (short)(139);
}

unsigned int g06(void)
{
	return 1100742u;
}

struct three_char g07(long double a0, struct int_pointer a1, unsigned short a2, void *a3)
{
	if (a0 != 141.25L)
		abi_fail("g07", "a0");
	if (a1.a != 1116580)
		abi_fail("g07", "a1.a");
	if (a1.b != (void *)&anchor[14])
		abi_fail("g07", "a1.b");
	if (a2 != (unsigned short)(144))
		abi_fail("g07", "a2");
	if (a3 != (void *)&anchor[16])
		abi_fail("g07", "a3");
	struct three_char r = { (char)(46), (char)(47), (char)(48) };
	return r;
}

struct long_double_one g08(unsigned long a0, int a1, long double a2, unsigned char a3)
{
	if (a0 != 1172013UL)
		abi_fail("g08", "a0");
	if (a1 != 1179932)
		abi_fail("g08", "a1");
	if (a2 != 151.25L)
		abi_fail("g08", "a2");
	if (a3 != (unsigned char)(152))
		abi_fail("g08", "a3");
	struct long_double_one r = { 153.25L };
	return r;
}

void g09(struct int_pointer a0, unsigned int a1, char a2)
{
	if (a0.a != 1211608)
		abi_fail("g09", "a0.a");
	if (a0.b != (void *)&anchor[26])
		abi_fail("g09", "a0.b");
	if (a1 != 1227446u)
		abi_fail("g09", "a1");
	if (a2 != (char)(57))
		abi_fail("g09", "a2");
}

unsigned short g10(struct nested a0, struct two_int a1, long double a2, long long a3)
{
	if (a0.a.a != 1243284)
		abi_fail("g10", "a0.a.a");
	if (a0.a.b != 1251203)
		abi_fail("g10", "a0.a.b");
	if (a0.b != 160.25f)
		abi_fail("g10", "a0.b");
	if (a1.a != 1267041)
		abi_fail("g10", "a1.a");
	if (a1.b != 1274960)
		abi_fail("g10", "a1.b");
	if (a2 != 163.25L)
		abi_fail("g10", "a2");
	if (a3 != 3599698292259361LL)
		abi_fail("g10", "a3");
	return (unsigned short)(165);
}

struct two_float g11(unsigned short a0, unsigned int a1, struct nested a2, char a3)
{
	if (a0 != (unsigned short)(166))
		abi_fail("g11", "a0");
	if (a1 != 1314555u)
		abi_fail("g11", "a1");
	if (a2.a.a != 1322474)
		abi_fail("g11", "a2.a.a");
	if (a2.a.b != 1330393)
		abi_fail("g11", "a2.a.b");
	if (a2.b != 170.25f)
		abi_fail("g11", "a2.b");
	if (a3 != (char)(71))
		abi_fail("g11", "a3");
	struct two_float r = { 172.25f, 173.25f };
	return r;
}

short g12(double a0, struct two_int a1, struct six_int a2, long a3, struct int_pointer a4)
{
	if (a0 != 174.25)
		abi_fail("g12", "a0");
	if (a1.a != 1377907)
		abi_fail("g12", "a1.a");
	if (a1.b != 1385826)
		abi_fail("g12", "a1.b");
	if (a2.a != 1393745)
		abi_fail("g12", "a2.a");
	if (a2.b != 1401664)
		abi_fail("g12", "a2.b");
	if (a2.c != 1409583)
		abi_fail("g12", "a2.c");
	if (a2.d != 1417502)
		abi_fail("g12", "a2.d");
	if (a2.e != 1425421)
		abi_fail("g12", "a2.e");
	if (a2.f != 1433340)
		abi_fail("g12", "a2.f");
	if (a3 != 1441259L)
		abi_fail("g12", "a3");
	if (a4.a != 1449178)
		abi_fail("g12", "a4.a");
	if (a4.b != (void *)&anchor[56])
		abi_fail("g12", "a4.b");
	return (short)(186);
}

struct int_pointer g13(signed char a0, long a1, long long a2, int a3, signed char a4, struct two_int a5, unsigned int a6, unsigned char a7)
{
	if (a0 != (signed char)(87))
		abi_fail("g13", "a0");
	if (a1 != 1480854L)
		abi_fail("g13", "a1");
	if (a2 != 2053639748127361LL)
		abi_fail("g13", "a2");
	if (a3 != 1496692)
		abi_fail("g13", "a3");
	if (a4 != (signed char)(91))
		abi_fail("g13", "a4");
	if (a5.a != 1512530)
		abi_fail("g13", "a5.a");
	if (a5.b != 1520449)
		abi_fail("g13", "a5.b");
	if (a6 != 1528368u)
		abi_fail("g13", "a6");
	if (a7 != (unsigned char)(195))
		abi_fail("g13", "a7");
	struct int_pointer r = { 1544206, (void *)&anchor[4] };
	return r;
}

unsigned long long g14(void)
{
	return 4737058672239841ULL;
}

void g15(unsigned long long a0, double a1, long a2, double a3)
{
	if (a0 != 5035216330474561ULL)
		abi_fail("g15", "a0");
	if (a1 != 200.25)
		abi_fail("g15", "a1");
	if (a2 != 1583801L)
		abi_fail("g15", "a2");
	if (a3 != 202.25)
		abi_fail("g15", "a3");
}

struct nested g16(struct long_double_one a0, signed char a1, unsigned char a2, long double a3, void *a4, long long a5)
{
	if (a0.a != 203.25L)
		abi_fail("g16", "a0.a");
	if (a1 != (signed char)(4))
		abi_fail("g16", "a1");
	if (a2 != (unsigned char)(205))
		abi_fail("g16", "a2");
	if (a3 != 206.25L)
		abi_fail("g16", "a3");
	if (a4 != (void *)&anchor[14])
		abi_fail("g16", "a4");
	if (a5 != 7718635254587041LL)
		abi_fail("g16", "a5");
	struct nested r = { { 1647153, 1655072 }, 211.25f };
	return r;
}

long long g17(unsigned char a0, struct nested a1, struct two_int a2, struct one_char a3, double a4, unsigned int a5, struct two_float a6)
{
	if (a0 != (unsigned char)(212))
		abi_fail("g17", "a0");
	if (a1.a.a != 1678829)
		abi_fail("g17", "a1.a.a");
	if (a1.a.b != 1686748)
		abi_fail("g17", "a1.a.b");
	if (a1.b != 215.25f)
		abi_fail("g17", "a1.b");
	if (a2.a != 1702586)
		abi_fail("g17", "a2.a");
	if (a2.b != 1710505)
		abi_fail("g17", "a2.b");
	if (a3.a != (char)(18))
		abi_fail("g17", "a3.a");
	if (a4 != 219.25)
		abi_fail("g17", "a4");
	if (a5 != 1734262u)
		abi_fail("g17", "a5");
	if (a6.a != 221.25f)
		abi_fail("g17", "a6.a");
	if (a6.b != 222.25f)
		abi_fail("g17", "a6.b");
	return 3191000128107841LL;
}

struct two_float g18(unsigned int a0, struct two_int a1, unsigned int a2)
{
	if (a0 != 1765938u)
		abi_fail("g18", "a0");
	if (a1.a != 1773857)
		abi_fail("g18", "a1.a");
	if (a1.b != 1781776)
		abi_fail("g18", "a1.b");
	if (a2 != 1789695u)
		abi_fail("g18", "a2");
	struct two_float r = { 228.25f, 229.25f };
	return r;
}

unsigned short g19(struct two_double a0, unsigned long long a1, struct two_int a2, short a3)
{
	if (a0.a != 230.25)
		abi_fail("g19", "a0.a");
	if (a0.b != 231.25)
		abi_fail("g19", "a0.b");
	if (a1 != 14874419052220321ULL)
		abi_fail("g19", "a1");
	if (a2.a != 1837209)
		abi_fail("g19", "a2.a");
	if (a2.b != 1845128)
		abi_fail("g19", "a2.b");
	if (a3 != (short)(235))
		abi_fail("g19", "a3");
	return (unsigned short)(236);
}

unsigned long g20(void)
{
	return 1868885UL;
}

signed char g21(long double a0, long a1, struct two_double a2, void *a3)
{
	if (a0 != 238.25L)
		abi_fail("g21", "a0");
	if (a1 != 1884723L)
		abi_fail("g21", "a1");
	if (a2.a != 240.25)
		abi_fail("g21", "a2.a");
	if (a2.b != 241.25)
		abi_fail("g21", "a2.b");
	if (a3 != (void *)&anchor[49])
		abi_fail("g21", "a3");
	return (signed char)(43);
}

struct long_double_one g22(float a0, char a1)
{
	if (a0 != 244.25f)
		abi_fail("g22", "a0");
	if (a1 != (char)(45))
		abi_fail("g22", "a1");
	struct long_double_one r = { 246.25L };
	return r;
}

long g23(unsigned long a0, union int_or_float a1, unsigned long long a2, char a3, signed char a4, unsigned long a5, struct three_char a6, unsigned long long a7)
{
	if (a0 != 1948075UL)
		abi_fail("g23", "a0");
	if (a1.a != 1955994)
		abi_fail("g23", "a1.a");
	if (a2 != 1943099242210561ULL)
		abi_fail("g23", "a2");
	if (a3 != (char)(50))
		abi_fail("g23", "a3");
	if (a4 != (signed char)(51))
		abi_fail("g23", "a4");
	if (a5 != 1987670UL)
		abi_fail("g23", "a5");
	if (a6.a != (char)(53))
		abi_fail("g23", "a6.a");
	if (a6.b != (char)(54))
		abi_fail("g23", "a6.b");
	if (a6.c != (char)(55))
		abi_fail("g23", "a6.c");
	if (a7 != 4030202849853601ULL)
		abi_fail("g23", "a7");
	return 2027265L;
}

signed char g24(void *a0, unsigned short a1)
{
	if (a0 != (void *)&anchor[1])
		abi_fail("g24", "a0");
	if (a1 != (unsigned short)(259))
		abi_fail("g24", "a1");
	return (signed char)(60);
}

signed char g25(double a0, float a1, double a2, unsigned long long a3, unsigned long long a4, char a5)
{
	if (a0 != 261.25)
		abi_fail("g25", "a0");
	if (a1 != 262.25f)
		abi_fail("g25", "a1");
	if (a2 != 263.25)
		abi_fail("g25", "a2");
	if (a3 != 6415464115731361ULL)
		abi_fail("g25", "a3");
	if (a4 != 6713621773966081ULL)
		abi_fail("g25", "a4");
	if (a5 != (char)(66))
		abi_fail("g25", "a5");
	return (signed char)(67);
}

char g26(struct int_float a0, struct three_char a1, double a2, int a3, long a4)
{
	if (a0.a != 2114374)
		abi_fail("g26", "a0.a");
	if (a0.b != 269.25f)
		abi_fail("g26", "a0.b");
	if (a1.a != (char)(70))
		abi_fail("g26", "a1.a");
	if (a1.b != (char)(71))
		abi_fail("g26", "a1.b");
	if (a1.c != (char)(72))
		abi_fail("g26", "a1.c");
	if (a2 != 273.25)
		abi_fail("g26", "a2");
	if (a3 != 2161888)
		abi_fail("g26", "a3");
	if (a4 != 2169807L)
		abi_fail("g26", "a4");
	return (char)(76);
}

struct int_pointer g27(unsigned long a0, float a1, unsigned int a2, long double a3, struct three_char a4, struct int_pointer a5)
{
	if (a0 != 2185645UL)
		abi_fail("g27", "a0");
	if (a1 != 278.25f)
		abi_fail("g27", "a1");
	if (a2 != 2201483u)
		abi_fail("g27", "a2");
	if (a3 != 280.25L)
		abi_fail("g27", "a3");
	if (a4.a != (char)(81))
		abi_fail("g27", "a4.a");
	if (a4.b != (char)(82))
		abi_fail("g27", "a4.b");
	if (a4.c != (char)(83))
		abi_fail("g27", "a4.c");
	if (a5.a != 2241078)
		abi_fail("g27", "a5.a");
	if (a5.b != (void *)&anchor[28])
		abi_fail("g27", "a5.b");
	struct int_pointer r = { 2256916, (void *)&anchor[30] };
	return r;
}

int g28(long long a0, struct nested a1, long long a2, double a3, short a4, signed char a5)
{
	if (a0 != 4571247913364641LL)
		abi_fail("g28", "a0");
	if (a1.a.a != 2280673)
		abi_fail("g28", "a1.a.a");
	if (a1.a.b != 2288592)
		abi_fail("g28", "a1.a.b");
	if (a1.b != 291.25f)
		abi_fail("g28", "a1.b");
	if (a2 != 5763878546303521LL)
		abi_fail("g28", "a2");
	if (a3 != 293.25)
		abi_fail("g28", "a3");
	if (a4 != (short)(294))
		abi_fail("g28", "a4");
	if (a5 != (signed char)(95))
		abi_fail("g28", "a5");
	return 2336106;
}

long long g29(void *a0, unsigned char a1)
{
	if (a0 != (void *)&anchor[40])
		abi_fail("g29", "a0");
	if (a1 != (unsigned char)(58))
		abi_fail("g29", "a1");
	return 7850982153946561LL;
}

struct nested g30(struct two_double a0, unsigned long long a1, unsigned short a2, union int_or_float a3, unsigned int a4, char a5)
{
	if (a0.a != 300.25)
		abi_fail("g30", "a0.a");
	if (a0.b != 301.25)
		abi_fail("g30", "a0.b");
	if (a1 != 17745455128650721ULL)
		abi_fail("g30", "a1");
	if (a2 != (unsigned short)(303))
		abi_fail("g30", "a2");
	if (a3.a != 2399458)
		abi_fail("g30", "a3.a");
	if (a4 != 2407377u)
		abi_fail("g30", "a4");
	if (a5 != (char)(6))
		abi_fail("g30", "a5");
	struct nested r = { { 2423215, 2431134 }, 309.25f };
	return r;
}

void *g31(struct six_int a0, short a1, unsigned short a2, int a3, float a4)
{
	if (a0.a != 2446972)
		abi_fail("g31", "a0.a");
	if (a0.b != 2454891)
		abi_fail("g31", "a0.b");
	if (a0.c != 2462810)
		abi_fail("g31", "a0.c");
	if (a0.d != 2470729)
		abi_fail("g31", "a0.d");
	if (a0.e != 2478648)
		abi_fail("g31", "a0.e");
	if (a0.f != 2486567)
		abi_fail("g31", "a0.f");
	if (a1 != (short)(316))
		abi_fail("g31", "a1");
	if (a2 != (unsigned short)(317))
		abi_fail("g31", "a2");
	if (a3 != 2510324)
		abi_fail("g31", "a3");
	if (a4 != 319.25f)
		abi_fail("g31", "a4");
	return (void *)&anchor[63];
}

unsigned long g32(long a0, struct four_float a1, char a2, double a3, unsigned char a4, struct int_float a5, struct long_double_one a6, struct int_float a7)
{
	if (a0 != 2534081L)
		abi_fail("g32", "a0");
	if (a1.a != 322.25f)
		abi_fail("g32", "a1.a");
	if (a1.b != 323.25f)
		abi_fail("g32", "a1.b");
	if (a1.c != 324.25f)
		abi_fail("g32", "a1.c");
	if (a1.d != 325.25f)
		abi_fail("g32", "a1.d");
	if (a2 != (char)(26))
		abi_fail("g32", "a2");
	if (a3 != 327.25)
		abi_fail("g32", "a3");
	if (a4 != (unsigned char)(88))
		abi_fail("g32", "a4");
	if (a5.a != 2597433)
		abi_fail("g32", "a5.a");
	if (a5.b != 330.25f)
		abi_fail("g32", "a5.b");
	if (a6.a != 331.25L)
		abi_fail("g32", "a6.a");
	if (a7.a != 2621190)
		abi_fail("g32", "a7.a");
	if (a7.b != 333.25f)
		abi_fail("g32", "a7.b");
	return 2637028UL;
}

struct one_char g33(unsigned short a0, void *a1, int a2, unsigned long a3)
{
	if (a0 != (unsigned short)(335))
		abi_fail("g33", "a0");
	if (a1 != (void *)&anchor[15])
		abi_fail("g33", "a1");
	if (a2 != 2660785)
		abi_fail("g33", "a2");
	if (a3 != 2668704UL)
		abi_fail("g33", "a3");
	struct one_char r = { (char)(39) };
	return r;
}

unsigned char g34(unsigned int a0, struct int_pointer a1, double a2, union int_or_float a3, short a4, struct int_pointer a5, short a6)
{
	if (a0 != 2684542u)
		abi_fail("g34", "a0");
	if (a1.a != 2692461)
		abi_fail("g34", "a1.a");
	if (a1.b != (void *)&anchor[21])
		abi_fail("g34", "a1.b");
	if (a2 != 343.25)
		abi_fail("g34", "a2");
	if (a3.a != 2716218)
		abi_fail("g34", "a3.a");
	if (a4 != (short)(345))
		abi_fail("g34", "a4");
	if (a5.a != 2732056)
		abi_fail("g34", "a5.a");
	if (a5.b != (void *)&anchor[26])
		abi_fail("g34", "a5.b");
	if (a6 != (short)(348))
		abi_fail("g34", "a6");
	return (unsigned char)(109);
}

long g35(void)
{
	return 2763732L;
}

unsigned int g36(unsigned long a0, float a1, struct nested a2, long double a3, long double a4, void *a5, void *a6)
{
	if (a0 != 2771651UL)
		abi_fail("g36", "a0");
	if (a1 != 352.25f)
		abi_fail("g36", "a1");
	if (a2.a.a != 2787489)
		abi_fail("g36", "a2.a.a");
	if (a2.a.b != 2795408)
		abi_fail("g36", "a2.a.b");
	if (a2.b != 355.25f)
		abi_fail("g36", "a2.b");
	if (a3 != 356.25L)
		abi_fail("g36", "a3");
	if (a4 != 357.25L)
		abi_fail("g36", "a4");
	if (a5 != (void *)&anchor[37])
		abi_fail("g36", "a5");
	if (a6 != (void *)&anchor[38])
		abi_fail("g36", "a6");
	return 2842922u;
}

void g37(void)
{
}

struct two_int g38(short a0, unsigned long a1, unsigned int a2)
{
	if (a0 != (short)(361))
		abi_fail("g38", "a0");
	if (a1 != 2858760UL)
		abi_fail("g38", "a1");
	if (a2 != 2866679u)
		abi_fail("g38", "a2");
	struct two_int r = { 2874598, 2882517 };
	return r;
}

long g39(struct int_pointer a0, void *a1, signed char a2, long a3, struct one_char a4, struct int_float a5)
{
	if (a0.a != 2890436)
		abi_fail("g39", "a0.a");
	if (a0.b != (void *)&anchor[46])
		abi_fail("g39", "a0.b");
	if (a1 != (void *)&anchor[47])
		abi_fail("g39", "a1");
	if (a2 != (signed char)(69))
		abi_fail("g39", "a2");
	if (a3 != 2922112L)
		abi_fail("g39", "a3");
	if (a4.a != (char)(71))
		abi_fail("g39", "a4.a");
	if (a5.a != 2937950)
		abi_fail("g39", "a5.a");
	if (a5.b != 373.25f)
		abi_fail("g39", "a5.b");
	return 2953788L;
}

unsigned short g40(double a0, struct six_int a1, struct one_char a2)
{
	if (a0 != 375.25)
		abi_fail("g40", "a0");
	if (a1.a != 2969626)
		abi_fail("g40", "a1.a");
	if (a1.b != 2977545)
		abi_fail("g40", "a1.b");
	if (a1.c != 2985464)
		abi_fail("g40", "a1.c");
	if (a1.d != 2993383)
		abi_fail("g40", "a1.d");
	if (a1.e != 3001302)
		abi_fail("g40", "a1.e");
	if (a1.f != 3009221)
		abi_fail("g40", "a1.f");
	if (a2.a != (char)(82))
		abi_fail("g40", "a2.a");
	return (unsigned short)(383);
}

void g41(struct two_int a0, union int_or_float a1, double a2, struct two_int a3, struct four_float a4)
{
	if (a0.a != 3032978)
		abi_fail("g41", "a0.a");
	if (a0.b != 3040897)
		abi_fail("g41", "a0.b");
	if (a1.a != 3048816)
		abi_fail("g41", "a1.a");
	if (a2 != 387.25)
		abi_fail("g41", "a2");
	if (a3.a != 3064654)
		abi_fail("g41", "a3.a");
	if (a3.b != 3072573)
		abi_fail("g41", "a3.b");
	if (a4.a != 390.25f)
		abi_fail("g41", "a4.a");
	if (a4.b != 391.25f)
		abi_fail("g41", "a4.b");
	if (a4.c != 392.25f)
		abi_fail("g41", "a4.c");
	if (a4.d != 393.25f)
		abi_fail("g41", "a4.d");
}

struct int_pointer g42(struct two_double a0, void *a1, signed char a2)
{
	if (a0.a != 394.25)
		abi_fail("g42", "a0.a");
	if (a0.b != 395.25)
		abi_fail("g42", "a0.b");
	if (a1 != (void *)&anchor[11])
		abi_fail("g42", "a1");
	if (a2 != (signed char)(97))
		abi_fail("g42", "a2");
	struct int_pointer r = { 3143844, (void *)&anchor[14] };
	return r;
}

unsigned long long g43(void *a0, unsigned long a1, struct three_char a2, int a3, unsigned int a4, double a5)
{
	if (a0 != (void *)&anchor[15])
		abi_fail("g43", "a0");
	if (a1 != 3167601UL)
		abi_fail("g43", "a1");
	if (a2.a != (char)(2))
		abi_fail("g43", "a2.a");
	if (a2.b != (char)(3))
		abi_fail("g43", "a2.b");
	if (a2.c != (char)(4))
		abi_fail("g43", "a2.c");
	if (a3 != 3199277)
		abi_fail("g43", "a3");
	if (a4 != 3207196u)
		abi_fail("g43", "a4");
	if (a5 != 407.25)
		abi_fail("g43", "a5");
	return 13350166901531041ULL;
}

void g44(struct two_double a0, struct six_int a1)
{
	if (a0.a != 409.25)
		abi_fail("g44", "a0.a");
	if (a0.b != 410.25)
		abi_fail("g44", "a0.b");
	if (a1.a != 3246791)
		abi_fail("g44", "a1.a");
	if (a1.b != 3254710)
		abi_fail("g44", "a1.b");
	if (a1.c != 3262629)
		abi_fail("g44", "a1.c");
	if (a1.d != 3270548)
		abi_fail("g44", "a1.d");
	if (a1.e != 3278467)
		abi_fail("g44", "a1.e");
	if (a1.f != 3286386)
		abi_fail("g44", "a1.f");
}

double g45(float a0, unsigned long long a1, unsigned long long a2)
{
	if (a0 != 417.25f)
		abi_fail("g45", "a0");
	if (a1 != 16331743483878241ULL)
		abi_fail("g45", "a1");
	if (a2 != 16629901142112961ULL)
		abi_fail("g45", "a2");
	return 420.25;
}

int g46(signed char a0, signed char a1, struct nested a2, long a3, short a4, long double a5, double a6, short a7)
{
	if (a0 != (signed char)(21))
		abi_fail("g46", "a0");
	if (a1 != (signed char)(22))
		abi_fail("g46", "a1");
	if (a2.a.a != 3341819)
		abi_fail("g46", "a2.a.a");
	if (a2.a.b != 3349738)
		abi_fail("g46", "a2.a.b");
	if (a2.b != 425.25f)
		abi_fail("g46", "a2.b");
	if (a3 != 3365576L)
		abi_fail("g46", "a3");
	if (a4 != (short)(427))
		abi_fail("g46", "a4");
	if (a5 != 428.25L)
		abi_fail("g46", "a5");
	if (a6 != 429.25)
		abi_fail("g46", "a6");
	if (a7 != (short)(430))
		abi_fail("g46", "a7");
	return 3405171;
}

unsigned short g47(long double a0, struct six_int a1, char a2, unsigned int a3, unsigned short a4, struct int_float a5, float a6, struct int_pointer a7)
{
	if (a0 != 432.25L)
		abi_fail("g47", "a0");
	if (a1.a != 3421009)
		abi_fail("g47", "a1.a");
	if (a1.b != 3428928)
		abi_fail("g47", "a1.b");
	if (a1.c != 3436847)
		abi_fail("g47", "a1.c");
	if (a1.d != 3444766)
		abi_fail("g47", "a1.d");
	if (a1.e != 3452685)
		abi_fail("g47", "a1.e");
	if (a1.f != 3460604)
		abi_fail("g47", "a1.f");
	if (a2 != (char)(39))
		abi_fail("g47", "a2");
	if (a3 != 3476442u)
		abi_fail("g47", "a3");
	if (a4 != (unsigned short)(441))
		abi_fail("g47", "a4");
	if (a5.a != 3492280)
		abi_fail("g47", "a5.a");
	if (a5.b != 443.25f)
		abi_fail("g47", "a5.b");
	if (a6 != 444.25f)
		abi_fail("g47", "a6");
	if (a7.a != 3516037)
		abi_fail("g47", "a7.a");
	if (a7.b != (void *)&anchor[61])
		abi_fail("g47", "a7.b");
	return (unsigned short)(447);
}

long long hv_ints_past_the_registers(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 3539794)
		abi_fail("hv_ints_past_the_registers", "a0");

	ABI_VA_START(ap, a0);
	{
		long long v0 = ABI_VA_ARG(ap, long long);
		if (v0 != 7574630889154561LL)
			abi_fail("hv_ints_past_the_registers", "v0");
	}
	{
		long long v1 = ABI_VA_ARG(ap, long long);
		if (v1 != 7872788547389281LL)
			abi_fail("hv_ints_past_the_registers", "v1");
	}
	{
		long long v2 = ABI_VA_ARG(ap, long long);
		if (v2 != 8170946205624001LL)
			abi_fail("hv_ints_past_the_registers", "v2");
	}
	{
		long long v3 = ABI_VA_ARG(ap, long long);
		if (v3 != 8469103863858721LL)
			abi_fail("hv_ints_past_the_registers", "v3");
	}
	{
		long long v4 = ABI_VA_ARG(ap, long long);
		if (v4 != 8767261522093441LL)
			abi_fail("hv_ints_past_the_registers", "v4");
	}
	{
		long long v5 = ABI_VA_ARG(ap, long long);
		if (v5 != 65419180328161LL)
			abi_fail("hv_ints_past_the_registers", "v5");
	}
	{
		long long v6 = ABI_VA_ARG(ap, long long);
		if (v6 != 363576838562881LL)
			abi_fail("hv_ints_past_the_registers", "v6");
	}
	{
		long long v7 = ABI_VA_ARG(ap, long long);
		if (v7 != 661734496797601LL)
			abi_fail("hv_ints_past_the_registers", "v7");
	}
	{
		long long v8 = ABI_VA_ARG(ap, long long);
		if (v8 != 959892155032321LL)
			abi_fail("hv_ints_past_the_registers", "v8");
	}
	{
		long long v9 = ABI_VA_ARG(ap, long long);
		if (v9 != 1258049813267041LL)
			abi_fail("hv_ints_past_the_registers", "v9");
	}
	ABI_VA_END(ap);

	return 1556207471501761LL;
}

double hv_doubles_past_the_registers(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 3634822)
		abi_fail("hv_doubles_past_the_registers", "a0");

	ABI_VA_START(ap, a0);
	{
		double v0 = ABI_VA_ARG(ap, double);
		if (v0 != 461.25)
			abi_fail("hv_doubles_past_the_registers", "v0");
	}
	{
		double v1 = ABI_VA_ARG(ap, double);
		if (v1 != 462.25)
			abi_fail("hv_doubles_past_the_registers", "v1");
	}
	{
		double v2 = ABI_VA_ARG(ap, double);
		if (v2 != 463.25)
			abi_fail("hv_doubles_past_the_registers", "v2");
	}
	{
		double v3 = ABI_VA_ARG(ap, double);
		if (v3 != 464.25)
			abi_fail("hv_doubles_past_the_registers", "v3");
	}
	{
		double v4 = ABI_VA_ARG(ap, double);
		if (v4 != 465.25)
			abi_fail("hv_doubles_past_the_registers", "v4");
	}
	{
		double v5 = ABI_VA_ARG(ap, double);
		if (v5 != 466.25)
			abi_fail("hv_doubles_past_the_registers", "v5");
	}
	{
		double v6 = ABI_VA_ARG(ap, double);
		if (v6 != 467.25)
			abi_fail("hv_doubles_past_the_registers", "v6");
	}
	{
		double v7 = ABI_VA_ARG(ap, double);
		if (v7 != 468.25)
			abi_fail("hv_doubles_past_the_registers", "v7");
	}
	{
		double v8 = ABI_VA_ARG(ap, double);
		if (v8 != 469.25)
			abi_fail("hv_doubles_past_the_registers", "v8");
	}
	{
		double v9 = ABI_VA_ARG(ap, double);
		if (v9 != 470.25)
			abi_fail("hv_doubles_past_the_registers", "v9");
	}
	ABI_VA_END(ap);

	return 471.25;
}

int hv_mixed_past_the_registers(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 3729850)
		abi_fail("hv_mixed_past_the_registers", "a0");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != 3737769)
			abi_fail("hv_mixed_past_the_registers", "v0");
	}
	{
		double v1 = ABI_VA_ARG(ap, double);
		if (v1 != 474.25)
			abi_fail("hv_mixed_past_the_registers", "v1");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != 3753607)
			abi_fail("hv_mixed_past_the_registers", "v2");
	}
	{
		double v3 = ABI_VA_ARG(ap, double);
		if (v3 != 476.25)
			abi_fail("hv_mixed_past_the_registers", "v3");
	}
	{
		int v4 = ABI_VA_ARG(ap, int);
		if (v4 != 3769445)
			abi_fail("hv_mixed_past_the_registers", "v4");
	}
	{
		double v5 = ABI_VA_ARG(ap, double);
		if (v5 != 478.25)
			abi_fail("hv_mixed_past_the_registers", "v5");
	}
	{
		int v6 = ABI_VA_ARG(ap, int);
		if (v6 != 3785283)
			abi_fail("hv_mixed_past_the_registers", "v6");
	}
	{
		double v7 = ABI_VA_ARG(ap, double);
		if (v7 != 480.25)
			abi_fail("hv_mixed_past_the_registers", "v7");
	}
	{
		int v8 = ABI_VA_ARG(ap, int);
		if (v8 != 3801121)
			abi_fail("hv_mixed_past_the_registers", "v8");
	}
	{
		double v9 = ABI_VA_ARG(ap, double);
		if (v9 != 482.25)
			abi_fail("hv_mixed_past_the_registers", "v9");
	}
	{
		int v10 = ABI_VA_ARG(ap, int);
		if (v10 != 3816959)
			abi_fail("hv_mixed_past_the_registers", "v10");
	}
	{
		double v11 = ABI_VA_ARG(ap, double);
		if (v11 != 484.25)
			abi_fail("hv_mixed_past_the_registers", "v11");
	}
	ABI_VA_END(ap);

	return 3832797;
}

int hv_promotions(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 3840716)
		abi_fail("hv_promotions", "a0");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (char)(87))
			abi_fail("hv_promotions", "v0");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != (signed char)(88))
			abi_fail("hv_promotions", "v1");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != (unsigned char)(9))
			abi_fail("hv_promotions", "v2");
	}
	{
		int v3 = ABI_VA_ARG(ap, int);
		if (v3 != (short)(490))
			abi_fail("hv_promotions", "v3");
	}
	{
		int v4 = ABI_VA_ARG(ap, int);
		if (v4 != (unsigned short)(491))
			abi_fail("hv_promotions", "v4");
	}
	{
		double v5 = ABI_VA_ARG(ap, double);
		if (v5 != 492.25f)
			abi_fail("hv_promotions", "v5");
	}
	ABI_VA_END(ap);

	return 3896149;
}

struct four_float hv_float_aggregates(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 3904068)
		abi_fail("hv_float_aggregates", "a0");

	ABI_VA_START(ap, a0);
	{
		struct two_float v0 = ABI_VA_ARG(ap, struct two_float);
		if (v0.a != 495.25f)
			abi_fail("hv_float_aggregates", "v0.a");
		if (v0.b != 496.25f)
			abi_fail("hv_float_aggregates", "v0.b");
	}
	{
		struct four_float v1 = ABI_VA_ARG(ap, struct four_float);
		if (v1.a != 497.25f)
			abi_fail("hv_float_aggregates", "v1.a");
		if (v1.b != 498.25f)
			abi_fail("hv_float_aggregates", "v1.b");
		if (v1.c != 499.25f)
			abi_fail("hv_float_aggregates", "v1.c");
		if (v1.d != 500.25f)
			abi_fail("hv_float_aggregates", "v1.d");
	}
	{
		struct two_double v2 = ABI_VA_ARG(ap, struct two_double);
		if (v2.a != 501.25)
			abi_fail("hv_float_aggregates", "v2.a");
		if (v2.b != 502.25)
			abi_fail("hv_float_aggregates", "v2.b");
	}
	ABI_VA_END(ap);

	struct four_float r = { 503.25f, 504.25f, 505.25f, 506.25f };
	return r;
}

struct two_int hv_small_aggregates(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4007015)
		abi_fail("hv_small_aggregates", "a0");

	ABI_VA_START(ap, a0);
	{
		struct one_char v0 = ABI_VA_ARG(ap, struct one_char);
		if (v0.a != (char)(8))
			abi_fail("hv_small_aggregates", "v0.a");
	}
	{
		struct three_char v1 = ABI_VA_ARG(ap, struct three_char);
		if (v1.a != (char)(9))
			abi_fail("hv_small_aggregates", "v1.a");
		if (v1.b != (char)(10))
			abi_fail("hv_small_aggregates", "v1.b");
		if (v1.c != (char)(11))
			abi_fail("hv_small_aggregates", "v1.c");
	}
	{
		struct two_int v2 = ABI_VA_ARG(ap, struct two_int);
		if (v2.a != 4046610)
			abi_fail("hv_small_aggregates", "v2.a");
		if (v2.b != 4054529)
			abi_fail("hv_small_aggregates", "v2.b");
	}
	{
		struct int_float v3 = ABI_VA_ARG(ap, struct int_float);
		if (v3.a != 4062448)
			abi_fail("hv_small_aggregates", "v3.a");
		if (v3.b != 515.25f)
			abi_fail("hv_small_aggregates", "v3.b");
	}
	ABI_VA_END(ap);

	struct two_int r = { 4078286, 4086205 };
	return r;
}

int hv_memory_aggregate(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4094124)
		abi_fail("hv_memory_aggregate", "a0");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != 4102043)
			abi_fail("hv_memory_aggregate", "v0");
	}
	{
		struct six_int v1 = ABI_VA_ARG(ap, struct six_int);
		if (v1.a != 4109962)
			abi_fail("hv_memory_aggregate", "v1.a");
		if (v1.b != 4117881)
			abi_fail("hv_memory_aggregate", "v1.b");
		if (v1.c != 4125800)
			abi_fail("hv_memory_aggregate", "v1.c");
		if (v1.d != 4133719)
			abi_fail("hv_memory_aggregate", "v1.d");
		if (v1.e != 4141638)
			abi_fail("hv_memory_aggregate", "v1.e");
		if (v1.f != 4149557)
			abi_fail("hv_memory_aggregate", "v1.f");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != 4157476)
			abi_fail("hv_memory_aggregate", "v2");
	}
	ABI_VA_END(ap);

	return 4165395;
}

struct six_int hv_returns_by_hidden_pointer(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4173314)
		abi_fail("hv_returns_by_hidden_pointer", "a0");

	ABI_VA_START(ap, a0);
	{
		double v0 = ABI_VA_ARG(ap, double);
		if (v0 != 529.25)
			abi_fail("hv_returns_by_hidden_pointer", "v0");
	}
	{
		long long v1 = ABI_VA_ARG(ap, long long);
		if (v1 != 4725401206166881LL)
			abi_fail("hv_returns_by_hidden_pointer", "v1");
	}
	ABI_VA_END(ap);

	struct six_int r = { 4197071, 4204990, 4212909, 4220828, 4228747, 4236666 };
	return r;
}

void hv_long_double_and_friends(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4244585)
		abi_fail("hv_long_double_and_friends", "a0");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != 4252504)
			abi_fail("hv_long_double_and_friends", "v0");
	}
	{
		long double v1 = ABI_VA_ARG(ap, long double);
		if (v1 != 539.25L)
			abi_fail("hv_long_double_and_friends", "v1");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != 4268342)
			abi_fail("hv_long_double_and_friends", "v2");
	}
	{
		long double v3 = ABI_VA_ARG(ap, long double);
		if (v3 != 541.25L)
			abi_fail("hv_long_double_and_friends", "v3");
	}
	ABI_VA_END(ap);

}

int hv_registers_already_spent(long long a0, long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 8303293104983521LL)
		abi_fail("hv_registers_already_spent", "a0");
	if (a1 != 8601450763218241LL)
		abi_fail("hv_registers_already_spent", "a1");
	if (a2 != 8899608421452961LL)
		abi_fail("hv_registers_already_spent", "a2");
	if (a3 != 197766079687681LL)
		abi_fail("hv_registers_already_spent", "a3");
	if (a4 != 495923737922401LL)
		abi_fail("hv_registers_already_spent", "a4");
	if (a5 != 794081396157121LL)
		abi_fail("hv_registers_already_spent", "a5");
	if (a6 != 1092239054391841LL)
		abi_fail("hv_registers_already_spent", "a6");
	if (a7 != 1390396712626561LL)
		abi_fail("hv_registers_already_spent", "a7");

	ABI_VA_START(ap, a7);
	{
		long long v0 = ABI_VA_ARG(ap, long long);
		if (v0 != 1688554370861281LL)
			abi_fail("hv_registers_already_spent", "v0");
	}
	{
		double v1 = ABI_VA_ARG(ap, double);
		if (v1 != 551.25)
			abi_fail("hv_registers_already_spent", "v1");
	}
	{
		struct two_int v2 = ABI_VA_ARG(ap, struct two_int);
		if (v2.a != 4363370)
			abi_fail("hv_registers_already_spent", "v2.a");
		if (v2.b != 4371289)
			abi_fail("hv_registers_already_spent", "v2.b");
	}
	ABI_VA_END(ap);

	return 4379208;
}

unsigned long v00(long a0, int a1, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4387127L)
		abi_fail("v00", "a0");
	if (a1 != 4395046)
		abi_fail("v00", "a1");

	ABI_VA_START(ap, a1);
	{
		long double v0 = ABI_VA_ARG(ap, long double);
		if (v0 != 557.25L)
			abi_fail("v00", "v0");
	}
	{
		struct long_double_one v1 = ABI_VA_ARG(ap, struct long_double_one);
		if (v1.a != 558.25L)
			abi_fail("v00", "v1.a");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != (signed char)(59))
			abi_fail("v00", "v2");
	}
	{
		void *v3 = ABI_VA_ARG(ap, void *);
		if (v3 != (void *)&anchor[47])
			abi_fail("v00", "v3");
	}
	ABI_VA_END(ap);

	return 4434641UL;
}

int v01(struct four_float a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 562.25f)
		abi_fail("v01", "a0.a");
	if (a0.b != 563.25f)
		abi_fail("v01", "a0.b");
	if (a0.c != 564.25f)
		abi_fail("v01", "a0.c");
	if (a0.d != 565.25f)
		abi_fail("v01", "a0.d");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (signed char)(66))
			abi_fail("v01", "v0");
	}
	{
		void *v1 = ABI_VA_ARG(ap, void *);
		if (v1 != (void *)&anchor[54])
			abi_fail("v01", "v1");
	}
	ABI_VA_END(ap);

	return 4490074;
}

char v02(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 4497993)
		abi_fail("v02", "a0");

	ABI_VA_START(ap, a0);
	{
		struct int_float v0 = ABI_VA_ARG(ap, struct int_float);
		if (v0.a != 4505912)
			abi_fail("v02", "v0.a");
		if (v0.b != 571.25f)
			abi_fail("v02", "v0.b");
	}
	{
		struct nested v1 = ABI_VA_ARG(ap, struct nested);
		if (v1.a.a != 4521750)
			abi_fail("v02", "v1.a.a");
		if (v1.a.b != 4529669)
			abi_fail("v02", "v1.a.b");
		if (v1.b != 574.25f)
			abi_fail("v02", "v1.b");
	}
	ABI_VA_END(ap);

	return (char)(75);
}

signed char v03(signed char a0, double a1, ...)
{
	ABI_VA_LIST ap;

	if (a0 != (signed char)(76))
		abi_fail("v03", "a0");
	if (a1 != 577.25)
		abi_fail("v03", "a1");

	ABI_VA_START(ap, a1);
	{
		struct three_char v0 = ABI_VA_ARG(ap, struct three_char);
		if (v0.a != (char)(78))
			abi_fail("v03", "v0.a");
		if (v0.b != (char)(79))
			abi_fail("v03", "v0.b");
		if (v0.c != (char)(80))
			abi_fail("v03", "v0.c");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != (char)(81))
			abi_fail("v03", "v1");
	}
	ABI_VA_END(ap);

	return (signed char)(82);
}

void v04(union int_or_float a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 4608859)
		abi_fail("v04", "a0.a");

	ABI_VA_START(ap, a0);
	{
		union int_or_float v0 = ABI_VA_ARG(ap, union int_or_float);
		if (v0.a != 4616778)
			abi_fail("v04", "v0.a");
	}
	ABI_VA_END(ap);

}

int v05(unsigned long long a0, int a1, struct long_double_one a2, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 12124072409076481ULL)
		abi_fail("v05", "a0");
	if (a1 != 4632616)
		abi_fail("v05", "a1");
	if (a2.a != 587.25L)
		abi_fail("v05", "a2.a");

	ABI_VA_START(ap, a2);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (unsigned char)(108))
			abi_fail("v05", "v0");
	}
	{
		struct one_char v1 = ABI_VA_ARG(ap, struct one_char);
		if (v1.a != (char)(89))
			abi_fail("v05", "v1.a");
	}
	{
		unsigned int v2 = ABI_VA_ARG(ap, unsigned int);
		if (v2 != 4664292u)
			abi_fail("v05", "v2");
	}
	{
		unsigned long v3 = ABI_VA_ARG(ap, unsigned long);
		if (v3 != 4672211UL)
			abi_fail("v05", "v3");
	}
	ABI_VA_END(ap);

	return 4680130;
}

struct three_char v06(struct int_float a0, int a1, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 4688049)
		abi_fail("v06", "a0.a");
	if (a0.b != 594.25f)
		abi_fail("v06", "a0.b");
	if (a1 != 4703887)
		abi_fail("v06", "a1");

	ABI_VA_START(ap, a1);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (unsigned short)(596))
			abi_fail("v06", "v0");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != 4719725)
			abi_fail("v06", "v1");
	}
	ABI_VA_END(ap);

	struct three_char r = { (char)(98), (char)(99), (char)(100) };
	return r;
}

long double v07(unsigned char a0, union int_or_float a1, struct two_int a2, ...)
{
	ABI_VA_LIST ap;

	if (a0 != (unsigned char)(121))
		abi_fail("v07", "a0");
	if (a1.a != 4759320)
		abi_fail("v07", "a1.a");
	if (a2.a != 4767239)
		abi_fail("v07", "a2.a");
	if (a2.b != 4775158)
		abi_fail("v07", "a2.b");

	ABI_VA_START(ap, a2);
	{
		unsigned long v0 = ABI_VA_ARG(ap, unsigned long);
		if (v0 != 4783077UL)
			abi_fail("v07", "v0");
	}
	{
		struct two_int v1 = ABI_VA_ARG(ap, struct two_int);
		if (v1.a != 4790996)
			abi_fail("v07", "v1.a");
		if (v1.b != 4798915)
			abi_fail("v07", "v1.b");
	}
	ABI_VA_END(ap);

	return 608.25L;
}

double v08(long double a0, struct two_int a1, struct four_float a2, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 609.25L)
		abi_fail("v08", "a0");
	if (a1.a != 4822672)
		abi_fail("v08", "a1.a");
	if (a1.b != 4830591)
		abi_fail("v08", "a1.b");
	if (a2.a != 612.25f)
		abi_fail("v08", "a2.a");
	if (a2.b != 613.25f)
		abi_fail("v08", "a2.b");
	if (a2.c != 614.25f)
		abi_fail("v08", "a2.c");
	if (a2.d != 615.25f)
		abi_fail("v08", "a2.d");

	ABI_VA_START(ap, a2);
	{
		long v0 = ABI_VA_ARG(ap, long);
		if (v0 != 4870186L)
			abi_fail("v08", "v0");
	}
	ABI_VA_END(ap);

	return 617.25;
}

unsigned long v09(struct one_char a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != (char)(18))
		abi_fail("v09", "a0.a");

	ABI_VA_START(ap, a0);
	{
		struct two_int v0 = ABI_VA_ARG(ap, struct two_int);
		if (v0.a != 4893943)
			abi_fail("v09", "v0.a");
		if (v0.b != 4901862)
			abi_fail("v09", "v0.b");
	}
	{
		struct one_char v1 = ABI_VA_ARG(ap, struct one_char);
		if (v1.a != (char)(21))
			abi_fail("v09", "v1.a");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != (short)(622))
			abi_fail("v09", "v2");
	}
	{
		long double v3 = ABI_VA_ARG(ap, long double);
		if (v3 != 623.25L)
			abi_fail("v09", "v3");
	}
	{
		double v4 = ABI_VA_ARG(ap, double);
		if (v4 != 624.25f)
			abi_fail("v09", "v4");
	}
	{
		long v5 = ABI_VA_ARG(ap, long);
		if (v5 != 4941457L)
			abi_fail("v09", "v5");
	}
	ABI_VA_END(ap);

	return 4949376UL;
}

struct four_float v10(unsigned char a0, void *a1, struct four_float a2, ...)
{
	ABI_VA_LIST ap;

	if (a0 != (unsigned char)(147))
		abi_fail("v10", "a0");
	if (a1 != (void *)&anchor[51])
		abi_fail("v10", "a1");
	if (a2.a != 629.25f)
		abi_fail("v10", "a2.a");
	if (a2.b != 630.25f)
		abi_fail("v10", "a2.b");
	if (a2.c != 631.25f)
		abi_fail("v10", "a2.c");
	if (a2.d != 632.25f)
		abi_fail("v10", "a2.d");

	ABI_VA_START(ap, a2);
	{
		unsigned long long v0 = ABI_VA_ARG(ap, unsigned long long);
		if (v0 != 8435640004343041ULL)
			abi_fail("v10", "v0");
	}
	{
		long double v1 = ABI_VA_ARG(ap, long double);
		if (v1 != 634.25L)
			abi_fail("v10", "v1");
	}
	{
		struct one_char v2 = ABI_VA_ARG(ap, struct one_char);
		if (v2.a != (char)(35))
			abi_fail("v10", "v2.a");
	}
	{
		long v3 = ABI_VA_ARG(ap, long);
		if (v3 != 5028566L)
			abi_fail("v10", "v3");
	}
	{
		long long v4 = ABI_VA_ARG(ap, long long);
		if (v4 != 628270637281921LL)
			abi_fail("v10", "v4");
	}
	{
		int v5 = ABI_VA_ARG(ap, int);
		if (v5 != (signed char)(38))
			abi_fail("v10", "v5");
	}
	ABI_VA_END(ap);

	struct four_float r = { 639.25f, 640.25f, 641.25f, 642.25f };
	return r;
}

int v11(struct int_float a0, unsigned short a1, int a2, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 5083999)
		abi_fail("v11", "a0.a");
	if (a0.b != 644.25f)
		abi_fail("v11", "a0.b");
	if (a1 != (unsigned short)(645))
		abi_fail("v11", "a1");
	if (a2 != 5107756)
		abi_fail("v11", "a2");

	ABI_VA_START(ap, a2);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != 5115675)
			abi_fail("v11", "v0");
	}
	{
		unsigned long long v1 = ABI_VA_ARG(ap, unsigned long long);
		if (v1 != 12908004877863841ULL)
			abi_fail("v11", "v1");
	}
	ABI_VA_END(ap);

	return 5131513;
}

long double v12(void *a0, long a1, ...)
{
	ABI_VA_LIST ap;

	if (a0 != (void *)&anchor[9])
		abi_fail("v12", "a0");
	if (a1 != 5147351L)
		abi_fail("v12", "a1");

	ABI_VA_START(ap, a1);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (signed char)(52))
			abi_fail("v12", "v0");
	}
	{
		struct int_pointer v1 = ABI_VA_ARG(ap, struct int_pointer);
		if (v1.a != 5163189)
			abi_fail("v12", "v1.a");
		if (v1.b != (void *)&anchor[13])
			abi_fail("v12", "v1.b");
	}
	{
		double v2 = ABI_VA_ARG(ap, double);
		if (v2 != 655.25f)
			abi_fail("v12", "v2");
	}
	ABI_VA_END(ap);

	return 656.25L;
}

struct four_float v13(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 5194865)
		abi_fail("v13", "a0");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != 5202784)
			abi_fail("v13", "v0");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != (char)(59))
			abi_fail("v13", "v1");
	}
	{
		unsigned long long v2 = ABI_VA_ARG(ap, unsigned long long);
		if (v2 != 16485896776680481ULL)
			abi_fail("v13", "v2");
	}
	{
		int v3 = ABI_VA_ARG(ap, int);
		if (v3 != (unsigned char)(181))
			abi_fail("v13", "v3");
	}
	ABI_VA_END(ap);

	struct four_float r = { 662.25f, 663.25f, 664.25f, 665.25f };
	return r;
}

void v14(struct three_char a0, unsigned int a1, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != (char)(66))
		abi_fail("v14", "a0.a");
	if (a0.b != (char)(67))
		abi_fail("v14", "a0.b");
	if (a0.c != (char)(68))
		abi_fail("v14", "a0.c");
	if (a1 != 5289893u)
		abi_fail("v14", "a1");

	ABI_VA_START(ap, a1);
	{
		struct three_char v0 = ABI_VA_ARG(ap, struct three_char);
		if (v0.a != (char)(70))
			abi_fail("v14", "v0.a");
		if (v0.b != (char)(71))
			abi_fail("v14", "v0.b");
		if (v0.c != (char)(72))
			abi_fail("v14", "v0.c");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != 5321569)
			abi_fail("v14", "v1");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != (char)(74))
			abi_fail("v14", "v2");
	}
	{
		struct int_float v3 = ABI_VA_ARG(ap, struct int_float);
		if (v3.a != 5337407)
			abi_fail("v14", "v3.a");
		if (v3.b != 676.25f)
			abi_fail("v14", "v3.b");
	}
	{
		int v4 = ABI_VA_ARG(ap, int);
		if (v4 != (unsigned short)(677))
			abi_fail("v14", "v4");
	}
	{
		struct three_char v5 = ABI_VA_ARG(ap, struct three_char);
		if (v5.a != (char)(78))
			abi_fail("v14", "v5.a");
		if (v5.b != (char)(79))
			abi_fail("v14", "v5.b");
		if (v5.c != (char)(80))
			abi_fail("v14", "v5.c");
	}
	ABI_VA_END(ap);

}

char v15(long a0, struct long_double_one a1, void *a2, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 5384921L)
		abi_fail("v15", "a0");
	if (a1.a != 682.25L)
		abi_fail("v15", "a1.a");
	if (a2 != (void *)&anchor[42])
		abi_fail("v15", "a2");

	ABI_VA_START(ap, a2);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (unsigned short)(684))
			abi_fail("v15", "v0");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != 5416597)
			abi_fail("v15", "v1");
	}
	{
		double v2 = ABI_VA_ARG(ap, double);
		if (v2 != 686.25)
			abi_fail("v15", "v2");
	}
	{
		int v3 = ABI_VA_ARG(ap, int);
		if (v3 != (unsigned short)(687))
			abi_fail("v15", "v3");
	}
	{
		long v4 = ABI_VA_ARG(ap, long);
		if (v4 != 5440354L)
			abi_fail("v15", "v4");
	}
	{
		struct four_float v5 = ABI_VA_ARG(ap, struct four_float);
		if (v5.a != 689.25f)
			abi_fail("v15", "v5.a");
		if (v5.b != 690.25f)
			abi_fail("v15", "v5.b");
		if (v5.c != 691.25f)
			abi_fail("v15", "v5.c");
		if (v5.d != 692.25f)
			abi_fail("v15", "v5.d");
	}
	ABI_VA_END(ap);

	return (char)(93);
}

signed char v16(int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 5487868)
		abi_fail("v16", "a0");

	ABI_VA_START(ap, a0);
	{
		struct long_double_one v0 = ABI_VA_ARG(ap, struct long_double_one);
		if (v0.a != 695.25L)
			abi_fail("v16", "v0.a");
	}
	{
		struct four_float v1 = ABI_VA_ARG(ap, struct four_float);
		if (v1.a != 696.25f)
			abi_fail("v16", "v1.a");
		if (v1.b != 697.25f)
			abi_fail("v16", "v1.b");
		if (v1.c != 698.25f)
			abi_fail("v16", "v1.c");
		if (v1.d != 699.25f)
			abi_fail("v16", "v1.d");
	}
	{
		struct two_double v2 = ABI_VA_ARG(ap, struct two_double);
		if (v2.a != 700.25)
			abi_fail("v16", "v2.a");
		if (v2.b != 701.25)
			abi_fail("v16", "v2.b");
	}
	{
		struct long_double_one v3 = ABI_VA_ARG(ap, struct long_double_one);
		if (v3.a != 702.25L)
			abi_fail("v16", "v3.a");
	}
	{
		union int_or_float v4 = ABI_VA_ARG(ap, union int_or_float);
		if (v4.a != 5559139)
			abi_fail("v16", "v4.a");
	}
	{
		unsigned int v5 = ABI_VA_ARG(ap, unsigned int);
		if (v5 != 5567058u)
			abi_fail("v16", "v5");
	}
	ABI_VA_END(ap);

	return (signed char)(5);
}

struct one_char v17(union int_or_float a0, unsigned char a1, unsigned int a2, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 5582896)
		abi_fail("v17", "a0.a");
	if (a1 != (unsigned char)(227))
		abi_fail("v17", "a1");
	if (a2 != 5598734u)
		abi_fail("v17", "a2");

	ABI_VA_START(ap, a2);
	{
		double v0 = ABI_VA_ARG(ap, double);
		if (v0 != 709.25)
			abi_fail("v17", "v0");
	}
	{
		struct int_pointer v1 = ABI_VA_ARG(ap, struct int_pointer);
		if (v1.a != 5614572)
			abi_fail("v17", "v1.a");
		if (v1.b != (void *)&anchor[6])
			abi_fail("v17", "v1.b");
	}
	ABI_VA_END(ap);

	struct one_char r = { (char)(12) };
	return r;
}

long long v18(long a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 5638329L)
		abi_fail("v18", "a0");

	ABI_VA_START(ap, a0);
	{
		unsigned long long v0 = ABI_VA_ARG(ap, unsigned long long);
		if (v0 != 14586410321355361ULL)
			abi_fail("v18", "v0");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != (unsigned short)(715))
			abi_fail("v18", "v1");
	}
	{
		struct long_double_one v2 = ABI_VA_ARG(ap, struct long_double_one);
		if (v2.a != 716.25L)
			abi_fail("v18", "v2.a");
	}
	{
		unsigned int v3 = ABI_VA_ARG(ap, unsigned int);
		if (v3 != 5670005u)
			abi_fail("v18", "v3");
	}
	{
		int v4 = ABI_VA_ARG(ap, int);
		if (v4 != (unsigned char)(238))
			abi_fail("v18", "v4");
	}
	ABI_VA_END(ap);

	return 7077198612528961LL;
}

unsigned int v19(unsigned int a0, ...)
{
	ABI_VA_LIST ap;

	if (a0 != 5693762u)
		abi_fail("v19", "a0");

	ABI_VA_START(ap, a0);
	{
		struct six_int v0 = ABI_VA_ARG(ap, struct six_int);
		if (v0.a != 5701681)
			abi_fail("v19", "v0.a");
		if (v0.b != 5709600)
			abi_fail("v19", "v0.b");
		if (v0.c != 5717519)
			abi_fail("v19", "v0.c");
		if (v0.d != 5725438)
			abi_fail("v19", "v0.d");
		if (v0.e != 5733357)
			abi_fail("v19", "v0.e");
		if (v0.f != 5741276)
			abi_fail("v19", "v0.f");
	}
	{
		double v1 = ABI_VA_ARG(ap, double);
		if (v1 != 727.25f)
			abi_fail("v19", "v1");
	}
	{
		int v2 = ABI_VA_ARG(ap, int);
		if (v2 != (signed char)(28))
			abi_fail("v19", "v2");
	}
	ABI_VA_END(ap);

	return 5765033u;
}

void v20(struct int_float a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 5772952)
		abi_fail("v20", "a0.a");
	if (a0.b != 731.25f)
		abi_fail("v20", "a0.b");

	ABI_VA_START(ap, a0);
	{
		struct int_float v0 = ABI_VA_ARG(ap, struct int_float);
		if (v0.a != 5788790)
			abi_fail("v20", "v0.a");
		if (v0.b != 733.25f)
			abi_fail("v20", "v0.b");
	}
	{
		int v1 = ABI_VA_ARG(ap, int);
		if (v1 != (signed char)(34))
			abi_fail("v20", "v1");
	}
	{
		struct one_char v2 = ABI_VA_ARG(ap, struct one_char);
		if (v2.a != (char)(35))
			abi_fail("v20", "v2.a");
	}
	ABI_VA_END(ap);

}

struct int_pointer v21(struct int_pointer a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 5820466)
		abi_fail("v21", "a0.a");
	if (a0.b != (void *)&anchor[32])
		abi_fail("v21", "a0.b");

	ABI_VA_START(ap, a0);
	{
		int v0 = ABI_VA_ARG(ap, int);
		if (v0 != (signed char)(38))
			abi_fail("v21", "v0");
	}
	ABI_VA_END(ap);

	struct int_pointer r = { 5844223, (void *)&anchor[35] };
	return r;
}

unsigned char v22(struct two_float a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a != 741.25f)
		abi_fail("v22", "a0.a");
	if (a0.b != 742.25f)
		abi_fail("v22", "a0.b");

	ABI_VA_START(ap, a0);
	{
		double v0 = ABI_VA_ARG(ap, double);
		if (v0 != 743.25)
			abi_fail("v22", "v0");
	}
	{
		double v1 = ABI_VA_ARG(ap, double);
		if (v1 != 744.25)
			abi_fail("v22", "v1");
	}
	{
		struct four_float v2 = ABI_VA_ARG(ap, struct four_float);
		if (v2.a != 745.25f)
			abi_fail("v22", "v2.a");
		if (v2.b != 746.25f)
			abi_fail("v22", "v2.b");
		if (v2.c != 747.25f)
			abi_fail("v22", "v2.c");
		if (v2.d != 748.25f)
			abi_fail("v22", "v2.d");
	}
	{
		struct six_int v3 = ABI_VA_ARG(ap, struct six_int);
		if (v3.a != 5923413)
			abi_fail("v22", "v3.a");
		if (v3.b != 5931332)
			abi_fail("v22", "v3.b");
		if (v3.c != 5939251)
			abi_fail("v22", "v3.c");
		if (v3.d != 5947170)
			abi_fail("v22", "v3.d");
		if (v3.e != 5955089)
			abi_fail("v22", "v3.e");
		if (v3.f != 5963008)
			abi_fail("v22", "v3.f");
	}
	ABI_VA_END(ap);

	return (unsigned char)(35);
}

short v23(struct nested a0, ...)
{
	ABI_VA_LIST ap;

	if (a0.a.a != 5978846)
		abi_fail("v23", "a0.a.a");
	if (a0.a.b != 5986765)
		abi_fail("v23", "a0.a.b");
	if (a0.b != 758.25f)
		abi_fail("v23", "a0.b");

	ABI_VA_START(ap, a0);
	{
		struct six_int v0 = ABI_VA_ARG(ap, struct six_int);
		if (v0.a != 6002603)
			abi_fail("v23", "v0.a");
		if (v0.b != 6010522)
			abi_fail("v23", "v0.b");
		if (v0.c != 6018441)
			abi_fail("v23", "v0.c");
		if (v0.d != 6026360)
			abi_fail("v23", "v0.d");
		if (v0.e != 6034279)
			abi_fail("v23", "v0.e");
		if (v0.f != 6042198)
			abi_fail("v23", "v0.f");
	}
	{
		struct two_double v1 = ABI_VA_ARG(ap, struct two_double);
		if (v1.a != 765.25)
			abi_fail("v23", "v1.a");
		if (v1.b != 766.25)
			abi_fail("v23", "v1.b");
	}
	ABI_VA_END(ap);

	return (short)(767);
}

