/* The calls, which pass what the callee expects and check what came back.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-signatures --write`. Do not edit
 * this file, edit the grammar in `build-tools/rucc-targets/src/signatures.rs`.
 *
 * This is the differential ABI harness of `spec/cross-compile/14-testing.md` section
 * 14.3. `callee.c` is compiled by one compiler and `caller.c` by the other, the two are
 * linked together and the program is run, so a value that arrives wrong is the two
 * compilers disagreeing about a calling convention rather than about a layout.
 *
 * The program prints nothing and exits zero when the two agree. Every disagreement
 * prints the function and the parameter it is about, and the exit status is one.
 */

#include "abi.h"

int main(void)
{
	{
		long long r = h_ints_past_the_registers(298157658234721LL, 596315316469441LL, 894472974704161LL, 1192630632938881LL, 1490788291173601LL, 1788945949408321LL, 2087103607643041LL, 2385261265877761LL, 2683418924112481LL, 2981576582347201LL);
		if (r != 3279734240581921LL)
			abi_fail("h_ints_past_the_registers", "return");
	}
	{
		double r = h_doubles_past_the_registers(13.25, 14.25, 15.25, 16.25, 17.25, 18.25, 19.25, 20.25, 21.25, 22.25);
		if (r != 23.25)
			abi_fail("h_doubles_past_the_registers", "return");
	}
	{
		int r = h_mixed_past_the_registers(182138, 25.25, 197976, 27.25, 213814, 29.25, 229652, 31.25, 245490, 33.25, 261328, 35.25);
		if (r != 277166)
			abi_fail("h_mixed_past_the_registers", "return");
	}
	{
		struct one_char a0 = { (char)(37) };
		struct three_char a1 = { (char)(38), (char)(39), (char)(40) };
		struct two_int a2 = { 316761, 324680 };
		struct int_float a3 = { 332599, 44.25f };
		struct two_int r = h_small_aggregates(a0, a1, a2, a3);
		if (r.a != 348437)
			abi_fail("h_small_aggregates", "return.a");
		if (r.b != 356356)
			abi_fail("h_small_aggregates", "return.b");
	}
	{
		struct two_float a0 = { 47.25f, 48.25f };
		struct four_float a1 = { 49.25f, 50.25f, 51.25f, 52.25f };
		struct two_double a2 = { 53.25, 54.25 };
		struct four_float r = h_float_aggregates(a0, a1, a2);
		if (r.a != 55.25f)
			abi_fail("h_float_aggregates", "return.a");
		if (r.b != 56.25f)
			abi_fail("h_float_aggregates", "return.b");
		if (r.c != 57.25f)
			abi_fail("h_float_aggregates", "return.c");
		if (r.d != 58.25f)
			abi_fail("h_float_aggregates", "return.d");
	}
	{
		struct six_int a1 = { 467222, 475141, 483060, 490979, 498898, 506817 };
		struct six_int r = h_memory_aggregate(459303, a1, 514736);
		if (r.a != 522655)
			abi_fail("h_memory_aggregate", "return.a");
		if (r.b != 530574)
			abi_fail("h_memory_aggregate", "return.b");
		if (r.c != 538493)
			abi_fail("h_memory_aggregate", "return.c");
		if (r.d != 546412)
			abi_fail("h_memory_aggregate", "return.d");
		if (r.e != 554331)
			abi_fail("h_memory_aggregate", "return.e");
		if (r.f != 562250)
			abi_fail("h_memory_aggregate", "return.f");
	}
	{
		struct six_int r = h_returns_by_hidden_pointer(570169, 74.25);
		if (r.a != 586007)
			abi_fail("h_returns_by_hidden_pointer", "return.a");
		if (r.b != 593926)
			abi_fail("h_returns_by_hidden_pointer", "return.b");
		if (r.c != 601845)
			abi_fail("h_returns_by_hidden_pointer", "return.c");
		if (r.d != 609764)
			abi_fail("h_returns_by_hidden_pointer", "return.d");
		if (r.e != 617683)
			abi_fail("h_returns_by_hidden_pointer", "return.e");
		if (r.f != 625602)
			abi_fail("h_returns_by_hidden_pointer", "return.f");
	}
	{
		struct two_int a0 = { 633521, 641440 };
		h_returns_nothing(a0, 83.25, 84.25L, (void *)&anchor[20]);
	}
	{
		long double r = h_long_double_and_friends(673116, 87.25L, 688954);
		if (r != 89.25L)
			abi_fail("h_long_double_and_friends", "return");
	}
	{
		struct nested a0 = { { 704792, 712711 }, 92.25f };
		union int_or_float a1 = { 728549 };
		struct int_pointer a2 = { 736468, (void *)&anchor[30] };
		union int_or_float r = h_nested_and_union(a0, a1, a2);
		if (r.a != 752306)
			abi_fail("h_nested_and_union", "return.a");
	}
	{
		unsigned char r = g00((unsigned short)(97), 98.25L, 776063);
		if (r != (unsigned char)(100))
			abi_fail("g00", "return");
	}
	{
		struct long_double_one a2 = { 103.25L };
		struct one_char a4 = { (char)(5) };
		struct three_char a5 = { (char)(6), (char)(7), (char)(8) };
		unsigned short r = g01(101.25f, 102.25L, a2, (char)(4), a4, a5);
		if (r != (unsigned short)(109))
			abi_fail("g01", "return");
	}
	{
		struct two_double a0 = { 110.25, 111.25 };
		struct two_double a5 = { 116.25, 117.25 };
		float r = g02(a0, 879010L, 886929u, 894848L, (void *)&anchor[50], a5, 118.25L, 934443u);
		if (r != 120.25f)
			abi_fail("g02", "return");
	}
	{
		struct long_double_one a0 = { 121.25L };
		struct two_double a3 = { 124.25, 125.25 };
		unsigned short r = g03(a0, (char)(22), (char)(23), a3, 989876u, (void *)&anchor[62]);
		if (r != (unsigned short)(128))
			abi_fail("g03", "return");
	}
	{
		g04((char)(29), (short)(130));
	}
	{
		struct two_int a4 = { 1061147, 1069066 };
		struct two_double a5 = { 137.25, 138.25 };
		short r = g05(131.25, 132.25f, 133.25L, 1053228L, a4, a5);
		if (r != (short)(139))
			abi_fail("g05", "return");
	}
	{
		unsigned int r = g06();
		if (r != 1100742u)
			abi_fail("g06", "return");
	}
	{
		struct int_pointer a1 = { 1116580, (void *)&anchor[14] };
		struct three_char r = g07(141.25L, a1, (unsigned short)(144), (void *)&anchor[16]);
		if (r.a != (char)(46))
			abi_fail("g07", "return.a");
		if (r.b != (char)(47))
			abi_fail("g07", "return.b");
		if (r.c != (char)(48))
			abi_fail("g07", "return.c");
	}
	{
		struct long_double_one r = g08(1172013UL, 1179932, 151.25L, (unsigned char)(152));
		if (r.a != 153.25L)
			abi_fail("g08", "return.a");
	}
	{
		struct int_pointer a0 = { 1211608, (void *)&anchor[26] };
		g09(a0, 1227446u, (char)(57));
	}
	{
		struct nested a0 = { { 1243284, 1251203 }, 160.25f };
		struct two_int a1 = { 1267041, 1274960 };
		unsigned short r = g10(a0, a1, 163.25L, 3599698292259361LL);
		if (r != (unsigned short)(165))
			abi_fail("g10", "return");
	}
	{
		struct nested a2 = { { 1322474, 1330393 }, 170.25f };
		struct two_float r = g11((unsigned short)(166), 1314555u, a2, (char)(71));
		if (r.a != 172.25f)
			abi_fail("g11", "return.a");
		if (r.b != 173.25f)
			abi_fail("g11", "return.b");
	}
	{
		struct two_int a1 = { 1377907, 1385826 };
		struct six_int a2 = { 1393745, 1401664, 1409583, 1417502, 1425421, 1433340 };
		struct int_pointer a4 = { 1449178, (void *)&anchor[56] };
		short r = g12(174.25, a1, a2, 1441259L, a4);
		if (r != (short)(186))
			abi_fail("g12", "return");
	}
	{
		struct two_int a5 = { 1512530, 1520449 };
		struct int_pointer r = g13((signed char)(87), 1480854L, 2053639748127361LL, 1496692, (signed char)(91), a5, 1528368u, (unsigned char)(195));
		if (r.a != 1544206)
			abi_fail("g13", "return.a");
		if (r.b != (void *)&anchor[4])
			abi_fail("g13", "return.b");
	}
	{
		unsigned long long r = g14();
		if (r != 4737058672239841ULL)
			abi_fail("g14", "return");
	}
	{
		g15(5035216330474561ULL, 200.25, 1583801L, 202.25);
	}
	{
		struct long_double_one a0 = { 203.25L };
		struct nested r = g16(a0, (signed char)(4), (unsigned char)(205), 206.25L, (void *)&anchor[14], 7718635254587041LL);
		if (r.a.a != 1647153)
			abi_fail("g16", "return.a.a");
		if (r.a.b != 1655072)
			abi_fail("g16", "return.a.b");
		if (r.b != 211.25f)
			abi_fail("g16", "return.b");
	}
	{
		struct nested a1 = { { 1678829, 1686748 }, 215.25f };
		struct two_int a2 = { 1702586, 1710505 };
		struct one_char a3 = { (char)(18) };
		struct two_float a6 = { 221.25f, 222.25f };
		long long r = g17((unsigned char)(212), a1, a2, a3, 219.25, 1734262u, a6);
		if (r != 3191000128107841LL)
			abi_fail("g17", "return");
	}
	{
		struct two_int a1 = { 1773857, 1781776 };
		struct two_float r = g18(1765938u, a1, 1789695u);
		if (r.a != 228.25f)
			abi_fail("g18", "return.a");
		if (r.b != 229.25f)
			abi_fail("g18", "return.b");
	}
	{
		struct two_double a0 = { 230.25, 231.25 };
		struct two_int a2 = { 1837209, 1845128 };
		unsigned short r = g19(a0, 14874419052220321ULL, a2, (short)(235));
		if (r != (unsigned short)(236))
			abi_fail("g19", "return");
	}
	{
		unsigned long r = g20();
		if (r != 1868885UL)
			abi_fail("g20", "return");
	}
	{
		struct two_double a2 = { 240.25, 241.25 };
		signed char r = g21(238.25L, 1884723L, a2, (void *)&anchor[49]);
		if (r != (signed char)(43))
			abi_fail("g21", "return");
	}
	{
		struct long_double_one r = g22(244.25f, (char)(45));
		if (r.a != 246.25L)
			abi_fail("g22", "return.a");
	}
	{
		union int_or_float a1 = { 1955994 };
		struct three_char a6 = { (char)(53), (char)(54), (char)(55) };
		long r = g23(1948075UL, a1, 1943099242210561ULL, (char)(50), (signed char)(51), 1987670UL, a6, 4030202849853601ULL);
		if (r != 2027265L)
			abi_fail("g23", "return");
	}
	{
		signed char r = g24((void *)&anchor[1], (unsigned short)(259));
		if (r != (signed char)(60))
			abi_fail("g24", "return");
	}
	{
		signed char r = g25(261.25, 262.25f, 263.25, 6415464115731361ULL, 6713621773966081ULL, (char)(66));
		if (r != (signed char)(67))
			abi_fail("g25", "return");
	}
	{
		struct int_float a0 = { 2114374, 269.25f };
		struct three_char a1 = { (char)(70), (char)(71), (char)(72) };
		char r = g26(a0, a1, 273.25, 2161888, 2169807L);
		if (r != (char)(76))
			abi_fail("g26", "return");
	}
	{
		struct three_char a4 = { (char)(81), (char)(82), (char)(83) };
		struct int_pointer a5 = { 2241078, (void *)&anchor[28] };
		struct int_pointer r = g27(2185645UL, 278.25f, 2201483u, 280.25L, a4, a5);
		if (r.a != 2256916)
			abi_fail("g27", "return.a");
		if (r.b != (void *)&anchor[30])
			abi_fail("g27", "return.b");
	}
	{
		struct nested a1 = { { 2280673, 2288592 }, 291.25f };
		int r = g28(4571247913364641LL, a1, 5763878546303521LL, 293.25, (short)(294), (signed char)(95));
		if (r != 2336106)
			abi_fail("g28", "return");
	}
	{
		long long r = g29((void *)&anchor[40], (unsigned char)(58));
		if (r != 7850982153946561LL)
			abi_fail("g29", "return");
	}
	{
		struct two_double a0 = { 300.25, 301.25 };
		union int_or_float a3 = { 2399458 };
		struct nested r = g30(a0, 17745455128650721ULL, (unsigned short)(303), a3, 2407377u, (char)(6));
		if (r.a.a != 2423215)
			abi_fail("g30", "return.a.a");
		if (r.a.b != 2431134)
			abi_fail("g30", "return.a.b");
		if (r.b != 309.25f)
			abi_fail("g30", "return.b");
	}
	{
		struct six_int a0 = { 2446972, 2454891, 2462810, 2470729, 2478648, 2486567 };
		void *r = g31(a0, (short)(316), (unsigned short)(317), 2510324, 319.25f);
		if (r != (void *)&anchor[63])
			abi_fail("g31", "return");
	}
	{
		struct four_float a1 = { 322.25f, 323.25f, 324.25f, 325.25f };
		struct int_float a5 = { 2597433, 330.25f };
		struct long_double_one a6 = { 331.25L };
		struct int_float a7 = { 2621190, 333.25f };
		unsigned long r = g32(2534081L, a1, (char)(26), 327.25, (unsigned char)(88), a5, a6, a7);
		if (r != 2637028UL)
			abi_fail("g32", "return");
	}
	{
		struct one_char r = g33((unsigned short)(335), (void *)&anchor[15], 2660785, 2668704UL);
		if (r.a != (char)(39))
			abi_fail("g33", "return.a");
	}
	{
		struct int_pointer a1 = { 2692461, (void *)&anchor[21] };
		union int_or_float a3 = { 2716218 };
		struct int_pointer a5 = { 2732056, (void *)&anchor[26] };
		unsigned char r = g34(2684542u, a1, 343.25, a3, (short)(345), a5, (short)(348));
		if (r != (unsigned char)(109))
			abi_fail("g34", "return");
	}
	{
		long r = g35();
		if (r != 2763732L)
			abi_fail("g35", "return");
	}
	{
		struct nested a2 = { { 2787489, 2795408 }, 355.25f };
		unsigned int r = g36(2771651UL, 352.25f, a2, 356.25L, 357.25L, (void *)&anchor[37], (void *)&anchor[38]);
		if (r != 2842922u)
			abi_fail("g36", "return");
	}
	{
		g37();
	}
	{
		struct two_int r = g38((short)(361), 2858760UL, 2866679u);
		if (r.a != 2874598)
			abi_fail("g38", "return.a");
		if (r.b != 2882517)
			abi_fail("g38", "return.b");
	}
	{
		struct int_pointer a0 = { 2890436, (void *)&anchor[46] };
		struct one_char a4 = { (char)(71) };
		struct int_float a5 = { 2937950, 373.25f };
		long r = g39(a0, (void *)&anchor[47], (signed char)(69), 2922112L, a4, a5);
		if (r != 2953788L)
			abi_fail("g39", "return");
	}
	{
		struct six_int a1 = { 2969626, 2977545, 2985464, 2993383, 3001302, 3009221 };
		struct one_char a2 = { (char)(82) };
		unsigned short r = g40(375.25, a1, a2);
		if (r != (unsigned short)(383))
			abi_fail("g40", "return");
	}
	{
		struct two_int a0 = { 3032978, 3040897 };
		union int_or_float a1 = { 3048816 };
		struct two_int a3 = { 3064654, 3072573 };
		struct four_float a4 = { 390.25f, 391.25f, 392.25f, 393.25f };
		g41(a0, a1, 387.25, a3, a4);
	}
	{
		struct two_double a0 = { 394.25, 395.25 };
		struct int_pointer r = g42(a0, (void *)&anchor[11], (signed char)(97));
		if (r.a != 3143844)
			abi_fail("g42", "return.a");
		if (r.b != (void *)&anchor[14])
			abi_fail("g42", "return.b");
	}
	{
		struct three_char a2 = { (char)(2), (char)(3), (char)(4) };
		unsigned long long r = g43((void *)&anchor[15], 3167601UL, a2, 3199277, 3207196u, 407.25);
		if (r != 13350166901531041ULL)
			abi_fail("g43", "return");
	}
	{
		struct two_double a0 = { 409.25, 410.25 };
		struct six_int a1 = { 3246791, 3254710, 3262629, 3270548, 3278467, 3286386 };
		g44(a0, a1);
	}
	{
		double r = g45(417.25f, 16331743483878241ULL, 16629901142112961ULL);
		if (r != 420.25)
			abi_fail("g45", "return");
	}
	{
		struct nested a2 = { { 3341819, 3349738 }, 425.25f };
		int r = g46((signed char)(21), (signed char)(22), a2, 3365576L, (short)(427), 428.25L, 429.25, (short)(430));
		if (r != 3405171)
			abi_fail("g46", "return");
	}
	{
		struct six_int a1 = { 3421009, 3428928, 3436847, 3444766, 3452685, 3460604 };
		struct int_float a5 = { 3492280, 443.25f };
		struct int_pointer a7 = { 3516037, (void *)&anchor[61] };
		unsigned short r = g47(432.25L, a1, (char)(39), 3476442u, (unsigned short)(441), a5, 444.25f, a7);
		if (r != (unsigned short)(447))
			abi_fail("g47", "return");
	}
	return abi_failures == 0 ? 0 : 1;
}
