/* The failure counter, and the only libc call in the corpus.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-signatures --write`. Do not edit
 * this file, edit the grammar in `build-tools/rucc-targets/src/signatures.rs`.
 *
 * This is the differential ABI harness of `spec/cross-compile/14-testing.md` section
 * 14.3. `callee.c` is compiled by one compiler and `caller.c` by the other, the two are
 * linked together and the program is run, so a value that arrives wrong is the two
 * compilers disagreeing about a calling convention rather than about a layout.
 *
 * The program prints nothing and exits zero when the two agree. Every disagreement
 * prints the function and the parameter it is about, and the exit status is one.
 */

#include <stdio.h>

#include "abi.h"

char anchor[64];
int abi_failures;

void abi_fail(const char *fn, const char *slot)
{
	abi_failures++;
	fprintf(stderr, "%s: %s did not arrive\n", fn, slot);
}
