/* Record layout for aarch64-ios-macabi, as rucc computes it.
 *
 * Generated by `cargo run -q -p rucc-targets -- abi-corpus --write`. Do not edit this
 * file, edit the grammar in `build-tools/rucc-targets/src/corpus.rs`.
 *
 * Every number below comes from `rucc_types::layout_record`, which is the function the
 * compiler calls when it parses a struct. So this file failing to compile under gcc or
 * clang for this target is a disagreement about layout between rucc and the reference,
 * and the diagnostic names the record and the member it is about.
 *
 * It compiles with `-c -std=c17 -Wall -Wextra -Werror` and no libc, which is what lets
 * the freestanding rows be checked the same way the hosted ones are.
 *
 * The shapes are the same in every target's file and only the numbers differ, so a diff
 * between two of these is the list of layout decisions the two targets make differently.
 */

/* A small struct with an alignment of its own, nested by the shapes below. */
struct nest_small {
	int m0;	/* +0 */
	char m1;	/* +4 */
};
_Static_assert(sizeof(struct nest_small) == 8, "sizeof struct nest_small");
_Static_assert(_Alignof(struct nest_small) == 4, "_Alignof struct nest_small");
_Static_assert(__builtin_offsetof(struct nest_small, m0) == 0, "offsetof struct nest_small.m0");
_Static_assert(__builtin_offsetof(struct nest_small, m1) == 4, "offsetof struct nest_small.m1");

/* A union nested by the shapes below, because a union member's alignment is the largest of its
 * members and not the first one's. */
union nest_union {
	char m0;	/* +0 */
	double m1;	/* +0 */
};
_Static_assert(sizeof(union nest_union) == 8, "sizeof union nest_union");
_Static_assert(_Alignof(union nest_union) == 8, "_Alignof union nest_union");
_Static_assert(__builtin_offsetof(union nest_union, m0) == 0, "offsetof union nest_union.m0");
_Static_assert(__builtin_offsetof(union nest_union, m1) == 0, "offsetof union nest_union.m1");

/* The empty struct, which C does not have and both references do. It is a GNU extension with a
 * size of zero, and C++ gives it a size of one, so this is the one case where being right means
 * disagreeing with the other language. */
struct empty {
};
_Static_assert(sizeof(struct empty) == 0, "sizeof struct empty");
_Static_assert(_Alignof(struct empty) == 1, "_Alignof struct empty");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_char {
	char m0 : 1;	/* bit 0 */
	char m1 : 2;	/* bit 1 */
	char m2 : 3;	/* bit 3 */
	char m3 : 4;	/* bit 8 */
	char m4 : 5;	/* bit 16 */
	char m5 : 6;	/* bit 24 */
	char m6 : 7;	/* bit 32 */
	char m7 : 8;	/* bit 40 */
};
_Static_assert(sizeof(struct bits_ladder_char) == 6, "sizeof struct bits_ladder_char");
_Static_assert(_Alignof(struct bits_ladder_char) == 1, "_Alignof struct bits_ladder_char");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_uchar {
	unsigned char m0 : 1;	/* bit 0 */
	unsigned char m1 : 2;	/* bit 1 */
	unsigned char m2 : 3;	/* bit 3 */
	unsigned char m3 : 4;	/* bit 8 */
	unsigned char m4 : 5;	/* bit 16 */
	unsigned char m5 : 6;	/* bit 24 */
	unsigned char m6 : 7;	/* bit 32 */
	unsigned char m7 : 8;	/* bit 40 */
};
_Static_assert(sizeof(struct bits_ladder_uchar) == 6, "sizeof struct bits_ladder_uchar");
_Static_assert(_Alignof(struct bits_ladder_uchar) == 1, "_Alignof struct bits_ladder_uchar");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_short {
	short m0 : 1;	/* bit 0 */
	short m1 : 2;	/* bit 1 */
	short m2 : 3;	/* bit 3 */
	short m3 : 4;	/* bit 6 */
	short m4 : 5;	/* bit 10 */
	short m5 : 6;	/* bit 16 */
	short m6 : 7;	/* bit 22 */
	short m7 : 8;	/* bit 32 */
	short m8 : 9;	/* bit 48 */
	short m9 : 10;	/* bit 64 */
	short m10 : 11;	/* bit 80 */
	short m11 : 12;	/* bit 96 */
	short m12 : 13;	/* bit 112 */
	short m13 : 14;	/* bit 128 */
	short m14 : 15;	/* bit 144 */
	short m15 : 16;	/* bit 160 */
};
_Static_assert(sizeof(struct bits_ladder_short) == 22, "sizeof struct bits_ladder_short");
_Static_assert(_Alignof(struct bits_ladder_short) == 2, "_Alignof struct bits_ladder_short");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_ushort {
	unsigned short m0 : 1;	/* bit 0 */
	unsigned short m1 : 2;	/* bit 1 */
	unsigned short m2 : 3;	/* bit 3 */
	unsigned short m3 : 4;	/* bit 6 */
	unsigned short m4 : 5;	/* bit 10 */
	unsigned short m5 : 6;	/* bit 16 */
	unsigned short m6 : 7;	/* bit 22 */
	unsigned short m7 : 8;	/* bit 32 */
	unsigned short m8 : 9;	/* bit 48 */
	unsigned short m9 : 10;	/* bit 64 */
	unsigned short m10 : 11;	/* bit 80 */
	unsigned short m11 : 12;	/* bit 96 */
	unsigned short m12 : 13;	/* bit 112 */
	unsigned short m13 : 14;	/* bit 128 */
	unsigned short m14 : 15;	/* bit 144 */
	unsigned short m15 : 16;	/* bit 160 */
};
_Static_assert(sizeof(struct bits_ladder_ushort) == 22, "sizeof struct bits_ladder_ushort");
_Static_assert(_Alignof(struct bits_ladder_ushort) == 2, "_Alignof struct bits_ladder_ushort");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_int {
	int m0 : 1;	/* bit 0 */
	int m1 : 2;	/* bit 1 */
	int m2 : 3;	/* bit 3 */
	int m3 : 4;	/* bit 6 */
	int m4 : 5;	/* bit 10 */
	int m5 : 6;	/* bit 15 */
	int m6 : 7;	/* bit 21 */
	int m7 : 8;	/* bit 32 */
	int m8 : 9;	/* bit 40 */
	int m9 : 10;	/* bit 49 */
	int m10 : 11;	/* bit 64 */
	int m11 : 12;	/* bit 75 */
	int m12 : 13;	/* bit 96 */
	int m13 : 14;	/* bit 109 */
	int m14 : 15;	/* bit 128 */
	int m15 : 16;	/* bit 143 */
	int m16 : 17;	/* bit 160 */
	int m17 : 18;	/* bit 192 */
	int m18 : 19;	/* bit 224 */
	int m19 : 20;	/* bit 256 */
	int m20 : 21;	/* bit 288 */
	int m21 : 22;	/* bit 320 */
	int m22 : 23;	/* bit 352 */
	int m23 : 24;	/* bit 384 */
	int m24 : 25;	/* bit 416 */
	int m25 : 26;	/* bit 448 */
	int m26 : 27;	/* bit 480 */
	int m27 : 28;	/* bit 512 */
	int m28 : 29;	/* bit 544 */
	int m29 : 30;	/* bit 576 */
	int m30 : 31;	/* bit 608 */
	int m31 : 32;	/* bit 640 */
};
_Static_assert(sizeof(struct bits_ladder_int) == 84, "sizeof struct bits_ladder_int");
_Static_assert(_Alignof(struct bits_ladder_int) == 4, "_Alignof struct bits_ladder_int");

/* One bit-field of every width the type has, in order. The size of the whole is the sum rounded
 * up, and a target that allocates into the wrong unit gets a different answer at the first width
 * that does not fit. */
struct bits_ladder_uint {
	unsigned int m0 : 1;	/* bit 0 */
	unsigned int m1 : 2;	/* bit 1 */
	unsigned int m2 : 3;	/* bit 3 */
	unsigned int m3 : 4;	/* bit 6 */
	unsigned int m4 : 5;	/* bit 10 */
	unsigned int m5 : 6;	/* bit 15 */
	unsigned int m6 : 7;	/* bit 21 */
	unsigned int m7 : 8;	/* bit 32 */
	unsigned int m8 : 9;	/* bit 40 */
	unsigned int m9 : 10;	/* bit 49 */
	unsigned int m10 : 11;	/* bit 64 */
	unsigned int m11 : 12;	/* bit 75 */
	unsigned int m12 : 13;	/* bit 96 */
	unsigned int m13 : 14;	/* bit 109 */
	unsigned int m14 : 15;	/* bit 128 */
	unsigned int m15 : 16;	/* bit 143 */
	unsigned int m16 : 17;	/* bit 160 */
	unsigned int m17 : 18;	/* bit 192 */
	unsigned int m18 : 19;	/* bit 224 */
	unsigned int m19 : 20;	/* bit 256 */
	unsigned int m20 : 21;	/* bit 288 */
	unsigned int m21 : 22;	/* bit 320 */
	unsigned int m22 : 23;	/* bit 352 */
	unsigned int m23 : 24;	/* bit 384 */
	unsigned int m24 : 25;	/* bit 416 */
	unsigned int m25 : 26;	/* bit 448 */
	unsigned int m26 : 27;	/* bit 480 */
	unsigned int m27 : 28;	/* bit 512 */
	unsigned int m28 : 29;	/* bit 544 */
	unsigned int m29 : 30;	/* bit 576 */
	unsigned int m30 : 31;	/* bit 608 */
	unsigned int m31 : 32;	/* bit 640 */
};
_Static_assert(sizeof(struct bits_ladder_uint) == 84, "sizeof struct bits_ladder_uint");
_Static_assert(_Alignof(struct bits_ladder_uint) == 4, "_Alignof struct bits_ladder_uint");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_char {
	char m0 : 7;	/* bit 0 */
	char m1 : 8;	/* bit 8 */
	char m2;	/* +2 */
};
_Static_assert(sizeof(struct bits_straddle_char) == 3, "sizeof struct bits_straddle_char");
_Static_assert(_Alignof(struct bits_straddle_char) == 1, "_Alignof struct bits_straddle_char");
_Static_assert(__builtin_offsetof(struct bits_straddle_char, m2) == 2, "offsetof struct bits_straddle_char.m2");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_uchar {
	unsigned char m0 : 7;	/* bit 0 */
	unsigned char m1 : 8;	/* bit 8 */
	char m2;	/* +2 */
};
_Static_assert(sizeof(struct bits_straddle_uchar) == 3, "sizeof struct bits_straddle_uchar");
_Static_assert(_Alignof(struct bits_straddle_uchar) == 1, "_Alignof struct bits_straddle_uchar");
_Static_assert(__builtin_offsetof(struct bits_straddle_uchar, m2) == 2, "offsetof struct bits_straddle_uchar.m2");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_short {
	short m0 : 15;	/* bit 0 */
	short m1 : 16;	/* bit 16 */
	char m2;	/* +4 */
};
_Static_assert(sizeof(struct bits_straddle_short) == 6, "sizeof struct bits_straddle_short");
_Static_assert(_Alignof(struct bits_straddle_short) == 2, "_Alignof struct bits_straddle_short");
_Static_assert(__builtin_offsetof(struct bits_straddle_short, m2) == 4, "offsetof struct bits_straddle_short.m2");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_ushort {
	unsigned short m0 : 15;	/* bit 0 */
	unsigned short m1 : 16;	/* bit 16 */
	char m2;	/* +4 */
};
_Static_assert(sizeof(struct bits_straddle_ushort) == 6, "sizeof struct bits_straddle_ushort");
_Static_assert(_Alignof(struct bits_straddle_ushort) == 2, "_Alignof struct bits_straddle_ushort");
_Static_assert(__builtin_offsetof(struct bits_straddle_ushort, m2) == 4, "offsetof struct bits_straddle_ushort.m2");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_int {
	int m0 : 31;	/* bit 0 */
	int m1 : 32;	/* bit 32 */
	char m2;	/* +8 */
};
_Static_assert(sizeof(struct bits_straddle_int) == 12, "sizeof struct bits_straddle_int");
_Static_assert(_Alignof(struct bits_straddle_int) == 4, "_Alignof struct bits_straddle_int");
_Static_assert(__builtin_offsetof(struct bits_straddle_int, m2) == 8, "offsetof struct bits_straddle_int.m2");

/* A width that fills all but one bit of a unit, followed by one that cannot fit in the bit that
 * is left. Whether the second one starts a new unit or is split across the boundary is the
 * difference this measures. */
struct bits_straddle_uint {
	unsigned int m0 : 31;	/* bit 0 */
	unsigned int m1 : 32;	/* bit 32 */
	char m2;	/* +8 */
};
_Static_assert(sizeof(struct bits_straddle_uint) == 12, "sizeof struct bits_straddle_uint");
_Static_assert(_Alignof(struct bits_straddle_uint) == 4, "_Alignof struct bits_straddle_uint");
_Static_assert(__builtin_offsetof(struct bits_straddle_uint, m2) == 8, "offsetof struct bits_straddle_uint.m2");

/* The zero width bit-field. It holds nothing and occupies no bits, and the member after it
 * starts at the next boundary of its type, so the offset of the char at the end is the whole of
 * what this asserts. */
struct bits_zero_width {
	unsigned int m0 : 3;	/* bit 0 */
	unsigned int : 0;	/* bit 32 */
	unsigned int m2 : 5;	/* bit 32 */
	char m3;	/* +5 */
};
_Static_assert(sizeof(struct bits_zero_width) == 8, "sizeof struct bits_zero_width");
_Static_assert(_Alignof(struct bits_zero_width) == 4, "_Alignof struct bits_zero_width");
_Static_assert(__builtin_offsetof(struct bits_zero_width, m3) == 5, "offsetof struct bits_zero_width.m3");

/* A struct whose only member is a zero width bit-field. It has a size of zero on both references
 * and an alignment that is the base type's, which is the one place a zero width member changes
 * something other than an offset. */
struct bits_zero_width_only {
	unsigned int : 0;	/* bit 0 */
};
_Static_assert(sizeof(struct bits_zero_width_only) == 0, "sizeof struct bits_zero_width_only");
_Static_assert(_Alignof(struct bits_zero_width_only) == 1, "_Alignof struct bits_zero_width_only");

/* A bit-field that does not fill its unit followed by an ordinary member. The ordinary one
 * starts at its own alignment and the bits before it are padding. */
struct bits_then_member {
	unsigned int m0 : 3;	/* bit 0 */
	int m1;	/* +4 */
	unsigned int m2 : 3;	/* bit 64 */
	char m3;	/* +9 */
};
_Static_assert(sizeof(struct bits_then_member) == 12, "sizeof struct bits_then_member");
_Static_assert(_Alignof(struct bits_then_member) == 4, "_Alignof struct bits_then_member");
_Static_assert(__builtin_offsetof(struct bits_then_member, m1) == 4, "offsetof struct bits_then_member.m1");
_Static_assert(__builtin_offsetof(struct bits_then_member, m3) == 9, "offsetof struct bits_then_member.m3");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_1 {
	char m0;	/* +0 */
	_Alignas(1) char m1;	/* +1 */
	char m2;	/* +2 */
};
_Static_assert(sizeof(struct alignas_1) == 3, "sizeof struct alignas_1");
_Static_assert(_Alignof(struct alignas_1) == 1, "_Alignof struct alignas_1");
_Static_assert(__builtin_offsetof(struct alignas_1, m0) == 0, "offsetof struct alignas_1.m0");
_Static_assert(__builtin_offsetof(struct alignas_1, m1) == 1, "offsetof struct alignas_1.m1");
_Static_assert(__builtin_offsetof(struct alignas_1, m2) == 2, "offsetof struct alignas_1.m2");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_2 {
	char m0;	/* +0 */
	_Alignas(2) char m1;	/* +2 */
	char m2;	/* +3 */
};
_Static_assert(sizeof(struct alignas_2) == 4, "sizeof struct alignas_2");
_Static_assert(_Alignof(struct alignas_2) == 2, "_Alignof struct alignas_2");
_Static_assert(__builtin_offsetof(struct alignas_2, m0) == 0, "offsetof struct alignas_2.m0");
_Static_assert(__builtin_offsetof(struct alignas_2, m1) == 2, "offsetof struct alignas_2.m1");
_Static_assert(__builtin_offsetof(struct alignas_2, m2) == 3, "offsetof struct alignas_2.m2");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_4 {
	char m0;	/* +0 */
	_Alignas(4) char m1;	/* +4 */
	char m2;	/* +5 */
};
_Static_assert(sizeof(struct alignas_4) == 8, "sizeof struct alignas_4");
_Static_assert(_Alignof(struct alignas_4) == 4, "_Alignof struct alignas_4");
_Static_assert(__builtin_offsetof(struct alignas_4, m0) == 0, "offsetof struct alignas_4.m0");
_Static_assert(__builtin_offsetof(struct alignas_4, m1) == 4, "offsetof struct alignas_4.m1");
_Static_assert(__builtin_offsetof(struct alignas_4, m2) == 5, "offsetof struct alignas_4.m2");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_8 {
	char m0;	/* +0 */
	_Alignas(8) char m1;	/* +8 */
	char m2;	/* +9 */
};
_Static_assert(sizeof(struct alignas_8) == 16, "sizeof struct alignas_8");
_Static_assert(_Alignof(struct alignas_8) == 8, "_Alignof struct alignas_8");
_Static_assert(__builtin_offsetof(struct alignas_8, m0) == 0, "offsetof struct alignas_8.m0");
_Static_assert(__builtin_offsetof(struct alignas_8, m1) == 8, "offsetof struct alignas_8.m1");
_Static_assert(__builtin_offsetof(struct alignas_8, m2) == 9, "offsetof struct alignas_8.m2");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_16 {
	char m0;	/* +0 */
	_Alignas(16) char m1;	/* +16 */
	char m2;	/* +17 */
};
_Static_assert(sizeof(struct alignas_16) == 32, "sizeof struct alignas_16");
_Static_assert(_Alignof(struct alignas_16) == 16, "_Alignof struct alignas_16");
_Static_assert(__builtin_offsetof(struct alignas_16, m0) == 0, "offsetof struct alignas_16.m0");
_Static_assert(__builtin_offsetof(struct alignas_16, m1) == 16, "offsetof struct alignas_16.m1");
_Static_assert(__builtin_offsetof(struct alignas_16, m2) == 17, "offsetof struct alignas_16.m2");

/* `_Alignas` on a char member. It raises the member's alignment and the record's with it, so the
 * one byte case is a char that stays where it was and the thirty two byte case moves everything
 * after it. */
struct alignas_32 {
	char m0;	/* +0 */
	_Alignas(32) char m1;	/* +32 */
	char m2;	/* +33 */
};
_Static_assert(sizeof(struct alignas_32) == 64, "sizeof struct alignas_32");
_Static_assert(_Alignof(struct alignas_32) == 32, "_Alignof struct alignas_32");
_Static_assert(__builtin_offsetof(struct alignas_32, m0) == 0, "offsetof struct alignas_32.m0");
_Static_assert(__builtin_offsetof(struct alignas_32, m1) == 32, "offsetof struct alignas_32.m1");
_Static_assert(__builtin_offsetof(struct alignas_32, m2) == 33, "offsetof struct alignas_32.m2");

/* `_Alignas(32)` on a member that already has an alignment of its own. Thirty two is above every
 * scalar alignment on every target, so this is the same request everywhere and the answer still
 * differs where the member's size does. */
struct alignas_over_int {
	char m0;	/* +0 */
	_Alignas(32) int m1;	/* +32 */
	char m2;	/* +36 */
};
_Static_assert(sizeof(struct alignas_over_int) == 64, "sizeof struct alignas_over_int");
_Static_assert(_Alignof(struct alignas_over_int) == 32, "_Alignof struct alignas_over_int");
_Static_assert(__builtin_offsetof(struct alignas_over_int, m0) == 0, "offsetof struct alignas_over_int.m0");
_Static_assert(__builtin_offsetof(struct alignas_over_int, m1) == 32, "offsetof struct alignas_over_int.m1");
_Static_assert(__builtin_offsetof(struct alignas_over_int, m2) == 36, "offsetof struct alignas_over_int.m2");

/* `_Alignas(32)` on a member that already has an alignment of its own. Thirty two is above every
 * scalar alignment on every target, so this is the same request everywhere and the answer still
 * differs where the member's size does. */
struct alignas_over_long_double {
	char m0;	/* +0 */
	_Alignas(32) long double m1;	/* +32 */
	char m2;	/* +40 */
};
_Static_assert(sizeof(struct alignas_over_long_double) == 64, "sizeof struct alignas_over_long_double");
_Static_assert(_Alignof(struct alignas_over_long_double) == 32, "_Alignof struct alignas_over_long_double");
_Static_assert(__builtin_offsetof(struct alignas_over_long_double, m0) == 0, "offsetof struct alignas_over_long_double.m0");
_Static_assert(__builtin_offsetof(struct alignas_over_long_double, m1) == 32, "offsetof struct alignas_over_long_double.m1");
_Static_assert(__builtin_offsetof(struct alignas_over_long_double, m2) == 40, "offsetof struct alignas_over_long_double.m2");

/* A char in front of a `long double`, which is the shortest program that tells the four `long
 * double` answers apart. */
struct long_double_pair {
	char m0;	/* +0 */
	long double m1;	/* +8 */
};
_Static_assert(sizeof(struct long_double_pair) == 16, "sizeof struct long_double_pair");
_Static_assert(_Alignof(struct long_double_pair) == 8, "_Alignof struct long_double_pair");
_Static_assert(__builtin_offsetof(struct long_double_pair, m0) == 0, "offsetof struct long_double_pair.m0");
_Static_assert(__builtin_offsetof(struct long_double_pair, m1) == 8, "offsetof struct long_double_pair.m1");

/* Bit-fields of four different declared types in a row, none of them full. The Itanium rule
 * packs them into whatever storage they reach and Microsoft's opens a new unit every time the
 * size changes, so this is four bytes under one and twelve under the other. */
struct bits_mixed_bases {
	unsigned int m0 : 3;	/* bit 0 */
	unsigned short m1 : 5;	/* bit 3 */
	unsigned char m2 : 3;	/* bit 8 */
	unsigned int m3 : 3;	/* bit 11 */
};
_Static_assert(sizeof(struct bits_mixed_bases) == 4, "sizeof struct bits_mixed_bases");
_Static_assert(_Alignof(struct bits_mixed_bases) == 4, "_Alignof struct bits_mixed_bases");

/* An ordinary member in front of a bit-field wider than the space left over. The Itanium rule
 * puts it at the next free bit because it still fits inside one unit of its own type, and
 * Microsoft's opens a unit at the type's alignment, so the two differ by a whole eight bytes
 * here. */
struct bits_after_member {
	char m0;	/* +0 */
	long long m1 : 33;	/* bit 8 */
};
_Static_assert(sizeof(struct bits_after_member) == 8, "sizeof struct bits_after_member");
_Static_assert(_Alignof(struct bits_after_member) == 8, "_Alignof struct bits_after_member");
_Static_assert(__builtin_offsetof(struct bits_after_member, m0) == 0, "offsetof struct bits_after_member.m0");

/* A zero width bit-field as the last member. The padding it opens belongs to the record even
 * with nothing after it to occupy it, except under Microsoft's rule where a zero width member
 * with no run of bit-fields in front of it ends nothing and so does nothing. */
struct bits_trailing_zero_width {
	char m0;	/* +0 */
	unsigned int : 0;	/* bit 32 */
};
_Static_assert(sizeof(struct bits_trailing_zero_width) == 4, "sizeof struct bits_trailing_zero_width");
_Static_assert(_Alignof(struct bits_trailing_zero_width) == 1, "_Alignof struct bits_trailing_zero_width");
_Static_assert(__builtin_offsetof(struct bits_trailing_zero_width, m0) == 0, "offsetof struct bits_trailing_zero_width.m0");

/* A union of a bit-field and a char. Microsoft's rule gives the bit-field its storage and no say
 * in the alignment, so this is four bytes aligned to one there, which is an alignment smaller
 * than either member has on its own. */
union union_of_bits {
	unsigned int m0 : 3;	/* bit 0 */
	char m1;	/* +0 */
};
_Static_assert(sizeof(union union_of_bits) == 4, "sizeof union union_of_bits");
_Static_assert(_Alignof(union union_of_bits) == 4, "_Alignof union union_of_bits");
_Static_assert(__builtin_offsetof(union union_of_bits, m1) == 0, "offsetof union union_of_bits.m1");

/* A char in front of an `__int128`. It is sixteen bytes aligned to sixteen everywhere except
 * s390x, which caps every scalar alignment at eight and so puts it at offset eight instead of
 * sixteen. */
struct int128_pair {
	char m0;	/* +0 */
	__int128 m1;	/* +16 */
};
_Static_assert(sizeof(struct int128_pair) == 32, "sizeof struct int128_pair");
_Static_assert(_Alignof(struct int128_pair) == 16, "_Alignof struct int128_pair");
_Static_assert(__builtin_offsetof(struct int128_pair, m0) == 0, "offsetof struct int128_pair.m0");
_Static_assert(__builtin_offsetof(struct int128_pair, m1) == 16, "offsetof struct int128_pair.m1");

/* A union of the three widest scalars. Its size is the largest member rounded up to the
 * alignment, and both of those move between targets. */
union union_of_the_widest {
	__int128 m0;	/* +0 */
	long double m1;	/* +0 */
	void *m2;	/* +0 */
};
_Static_assert(sizeof(union union_of_the_widest) == 16, "sizeof union union_of_the_widest");
_Static_assert(_Alignof(union union_of_the_widest) == 16, "_Alignof union union_of_the_widest");
_Static_assert(__builtin_offsetof(union union_of_the_widest, m0) == 0, "offsetof union union_of_the_widest.m0");
_Static_assert(__builtin_offsetof(union union_of_the_widest, m1) == 0, "offsetof union union_of_the_widest.m1");
_Static_assert(__builtin_offsetof(union union_of_the_widest, m2) == 0, "offsetof union union_of_the_widest.m2");

/* A flexible array member. It sits where it would have sat and adds nothing to the size, and the
 * tail padding in front of it is what makes the idiom allocate enough. */
struct flexible {
	int m0;	/* +0 */
	char m1;	/* +4 */
	int m2[];	/* +8 */
};
_Static_assert(sizeof(struct flexible) == 8, "sizeof struct flexible");
_Static_assert(_Alignof(struct flexible) == 4, "_Alignof struct flexible");
_Static_assert(__builtin_offsetof(struct flexible, m0) == 0, "offsetof struct flexible.m0");
_Static_assert(__builtin_offsetof(struct flexible, m1) == 4, "offsetof struct flexible.m1");
_Static_assert(__builtin_offsetof(struct flexible, m2) == 8, "offsetof struct flexible.m2");

/* A struct whose only member is a flexible array member, so it holds no storage at all. It has
 * the size of the empty struct and the alignment of the element type, which is the one place
 * those two come from different members. */
struct flexible_only {
	int m0[];	/* +0 */
};
_Static_assert(sizeof(struct flexible_only) == 0, "sizeof struct flexible_only");
_Static_assert(_Alignof(struct flexible_only) == 4, "_Alignof struct flexible_only");
_Static_assert(__builtin_offsetof(struct flexible_only, m0) == 0, "offsetof struct flexible_only.m0");

struct gen_00 {
	short m0[3];	/* +0 */
	unsigned char m1[2];	/* +6 */
	long long m2;	/* +8 */
	long double m3;	/* +16 */
	double m4;	/* +24 */
};
_Static_assert(sizeof(struct gen_00) == 32, "sizeof struct gen_00");
_Static_assert(_Alignof(struct gen_00) == 8, "_Alignof struct gen_00");
_Static_assert(__builtin_offsetof(struct gen_00, m0) == 0, "offsetof struct gen_00.m0");
_Static_assert(__builtin_offsetof(struct gen_00, m1) == 6, "offsetof struct gen_00.m1");
_Static_assert(__builtin_offsetof(struct gen_00, m2) == 8, "offsetof struct gen_00.m2");
_Static_assert(__builtin_offsetof(struct gen_00, m3) == 16, "offsetof struct gen_00.m3");
_Static_assert(__builtin_offsetof(struct gen_00, m4) == 24, "offsetof struct gen_00.m4");

struct gen_01 {
	unsigned short m0 : 5;	/* bit 0 */
	unsigned char m1[2];	/* +1 */
};
_Static_assert(sizeof(struct gen_01) == 4, "sizeof struct gen_01");
_Static_assert(_Alignof(struct gen_01) == 2, "_Alignof struct gen_01");
_Static_assert(__builtin_offsetof(struct gen_01, m1) == 1, "offsetof struct gen_01.m1");

struct gen_02 {
	int m0[3];	/* +0 */
	unsigned char m1;	/* +12 */
	struct long_double_pair m2;	/* +16 */
	double m3;	/* +32 */
	int m4 : 18;	/* bit 320 */
};
_Static_assert(sizeof(struct gen_02) == 48, "sizeof struct gen_02");
_Static_assert(_Alignof(struct gen_02) == 8, "_Alignof struct gen_02");
_Static_assert(__builtin_offsetof(struct gen_02, m0) == 0, "offsetof struct gen_02.m0");
_Static_assert(__builtin_offsetof(struct gen_02, m1) == 12, "offsetof struct gen_02.m1");
_Static_assert(__builtin_offsetof(struct gen_02, m2) == 16, "offsetof struct gen_02.m2");
_Static_assert(__builtin_offsetof(struct gen_02, m3) == 32, "offsetof struct gen_02.m3");

struct gen_03 {
	long double m0;	/* +0 */
};
_Static_assert(sizeof(struct gen_03) == 8, "sizeof struct gen_03");
_Static_assert(_Alignof(struct gen_03) == 8, "_Alignof struct gen_03");
_Static_assert(__builtin_offsetof(struct gen_03, m0) == 0, "offsetof struct gen_03.m0");

struct gen_04 {
	unsigned char m0;	/* +0 */
	unsigned char m1 : 8;	/* bit 8 */
	_Alignas(16) struct bits_straddle_uint m2[2];	/* +16 */
	struct bits_straddle_ushort m3;	/* +40 */
};
_Static_assert(sizeof(struct gen_04) == 48, "sizeof struct gen_04");
_Static_assert(_Alignof(struct gen_04) == 16, "_Alignof struct gen_04");
_Static_assert(__builtin_offsetof(struct gen_04, m0) == 0, "offsetof struct gen_04.m0");
_Static_assert(__builtin_offsetof(struct gen_04, m2) == 16, "offsetof struct gen_04.m2");
_Static_assert(__builtin_offsetof(struct gen_04, m3) == 40, "offsetof struct gen_04.m3");

struct gen_05 {
	signed char m0;	/* +0 */
};
_Static_assert(sizeof(struct gen_05) == 1, "sizeof struct gen_05");
_Static_assert(_Alignof(struct gen_05) == 1, "_Alignof struct gen_05");
_Static_assert(__builtin_offsetof(struct gen_05, m0) == 0, "offsetof struct gen_05.m0");

struct gen_06 {
	_Alignas(16) struct alignas_4 m0;	/* +0 */
	unsigned int m1;	/* +8 */
	unsigned char m2;	/* +12 */
};
_Static_assert(sizeof(struct gen_06) == 16, "sizeof struct gen_06");
_Static_assert(_Alignof(struct gen_06) == 16, "_Alignof struct gen_06");
_Static_assert(__builtin_offsetof(struct gen_06, m0) == 0, "offsetof struct gen_06.m0");
_Static_assert(__builtin_offsetof(struct gen_06, m1) == 8, "offsetof struct gen_06.m1");
_Static_assert(__builtin_offsetof(struct gen_06, m2) == 12, "offsetof struct gen_06.m2");

struct gen_07 {
	long long m0;	/* +0 */
	short m1;	/* +8 */
	double m2;	/* +16 */
	_Alignas(32) long double m3;	/* +32 */
	short m4[3];	/* +40 */
	unsigned long m5[2];	/* +48 */
};
_Static_assert(sizeof(struct gen_07) == 64, "sizeof struct gen_07");
_Static_assert(_Alignof(struct gen_07) == 32, "_Alignof struct gen_07");
_Static_assert(__builtin_offsetof(struct gen_07, m0) == 0, "offsetof struct gen_07.m0");
_Static_assert(__builtin_offsetof(struct gen_07, m1) == 8, "offsetof struct gen_07.m1");
_Static_assert(__builtin_offsetof(struct gen_07, m2) == 16, "offsetof struct gen_07.m2");
_Static_assert(__builtin_offsetof(struct gen_07, m3) == 32, "offsetof struct gen_07.m3");
_Static_assert(__builtin_offsetof(struct gen_07, m4) == 40, "offsetof struct gen_07.m4");
_Static_assert(__builtin_offsetof(struct gen_07, m5) == 48, "offsetof struct gen_07.m5");

struct gen_08 {
	float m0;	/* +0 */
	struct empty m1;	/* +4 */
	signed char m2;	/* +4 */
	_Alignas(16) long m3;	/* +16 */
};
_Static_assert(sizeof(struct gen_08) == 32, "sizeof struct gen_08");
_Static_assert(_Alignof(struct gen_08) == 16, "_Alignof struct gen_08");
_Static_assert(__builtin_offsetof(struct gen_08, m0) == 0, "offsetof struct gen_08.m0");
_Static_assert(__builtin_offsetof(struct gen_08, m1) == 4, "offsetof struct gen_08.m1");
_Static_assert(__builtin_offsetof(struct gen_08, m2) == 4, "offsetof struct gen_08.m2");
_Static_assert(__builtin_offsetof(struct gen_08, m3) == 16, "offsetof struct gen_08.m3");

struct gen_09 {
	double m0[3];	/* +0 */
	char m1[3];	/* +24 */
	_Alignas(32) char m2;	/* +32 */
	unsigned int m3;	/* +36 */
};
_Static_assert(sizeof(struct gen_09) == 64, "sizeof struct gen_09");
_Static_assert(_Alignof(struct gen_09) == 32, "_Alignof struct gen_09");
_Static_assert(__builtin_offsetof(struct gen_09, m0) == 0, "offsetof struct gen_09.m0");
_Static_assert(__builtin_offsetof(struct gen_09, m1) == 24, "offsetof struct gen_09.m1");
_Static_assert(__builtin_offsetof(struct gen_09, m2) == 32, "offsetof struct gen_09.m2");
_Static_assert(__builtin_offsetof(struct gen_09, m3) == 36, "offsetof struct gen_09.m3");

struct gen_10 {
	int m0;	/* +0 */
	struct bits_straddle_int m1;	/* +4 */
	unsigned long m2;	/* +16 */
	struct alignas_4 m3;	/* +24 */
};
_Static_assert(sizeof(struct gen_10) == 32, "sizeof struct gen_10");
_Static_assert(_Alignof(struct gen_10) == 8, "_Alignof struct gen_10");
_Static_assert(__builtin_offsetof(struct gen_10, m0) == 0, "offsetof struct gen_10.m0");
_Static_assert(__builtin_offsetof(struct gen_10, m1) == 4, "offsetof struct gen_10.m1");
_Static_assert(__builtin_offsetof(struct gen_10, m2) == 16, "offsetof struct gen_10.m2");
_Static_assert(__builtin_offsetof(struct gen_10, m3) == 24, "offsetof struct gen_10.m3");

struct gen_11 {
	unsigned long m0;	/* +0 */
	float m1;	/* +8 */
	struct bits_ladder_uchar m2;	/* +12 */
};
_Static_assert(sizeof(struct gen_11) == 24, "sizeof struct gen_11");
_Static_assert(_Alignof(struct gen_11) == 8, "_Alignof struct gen_11");
_Static_assert(__builtin_offsetof(struct gen_11, m0) == 0, "offsetof struct gen_11.m0");
_Static_assert(__builtin_offsetof(struct gen_11, m1) == 8, "offsetof struct gen_11.m1");
_Static_assert(__builtin_offsetof(struct gen_11, m2) == 12, "offsetof struct gen_11.m2");

struct gen_12 {
	unsigned char m0;	/* +0 */
	struct bits_straddle_short m1;	/* +2 */
	void *m2;	/* +8 */
	double m3[2];	/* +16 */
};
_Static_assert(sizeof(struct gen_12) == 32, "sizeof struct gen_12");
_Static_assert(_Alignof(struct gen_12) == 8, "_Alignof struct gen_12");
_Static_assert(__builtin_offsetof(struct gen_12, m0) == 0, "offsetof struct gen_12.m0");
_Static_assert(__builtin_offsetof(struct gen_12, m1) == 2, "offsetof struct gen_12.m1");
_Static_assert(__builtin_offsetof(struct gen_12, m2) == 8, "offsetof struct gen_12.m2");
_Static_assert(__builtin_offsetof(struct gen_12, m3) == 16, "offsetof struct gen_12.m3");

struct gen_13 {
	signed char m0[2];	/* +0 */
	char m1 : 7;	/* bit 16 */
	unsigned int m2;	/* +4 */
};
_Static_assert(sizeof(struct gen_13) == 8, "sizeof struct gen_13");
_Static_assert(_Alignof(struct gen_13) == 4, "_Alignof struct gen_13");
_Static_assert(__builtin_offsetof(struct gen_13, m0) == 0, "offsetof struct gen_13.m0");
_Static_assert(__builtin_offsetof(struct gen_13, m2) == 4, "offsetof struct gen_13.m2");

struct gen_14 {
	void *m0;	/* +0 */
	struct bits_ladder_int m1;	/* +8 */
	unsigned long m2;	/* +96 */
	int m3;	/* +104 */
	short m4 : 2;	/* bit 864 */
	struct bits_straddle_ushort m5;	/* +110 */
};
_Static_assert(sizeof(struct gen_14) == 120, "sizeof struct gen_14");
_Static_assert(_Alignof(struct gen_14) == 8, "_Alignof struct gen_14");
_Static_assert(__builtin_offsetof(struct gen_14, m0) == 0, "offsetof struct gen_14.m0");
_Static_assert(__builtin_offsetof(struct gen_14, m1) == 8, "offsetof struct gen_14.m1");
_Static_assert(__builtin_offsetof(struct gen_14, m2) == 96, "offsetof struct gen_14.m2");
_Static_assert(__builtin_offsetof(struct gen_14, m3) == 104, "offsetof struct gen_14.m3");
_Static_assert(__builtin_offsetof(struct gen_14, m5) == 110, "offsetof struct gen_14.m5");

struct gen_15 {
	int m0 : 8;	/* bit 0 */
};
_Static_assert(sizeof(struct gen_15) == 4, "sizeof struct gen_15");
_Static_assert(_Alignof(struct gen_15) == 4, "_Alignof struct gen_15");

struct gen_16 {
	long m0;	/* +0 */
	long double m1;	/* +8 */
	unsigned long m2;	/* +16 */
	signed char m3;	/* +24 */
};
_Static_assert(sizeof(struct gen_16) == 32, "sizeof struct gen_16");
_Static_assert(_Alignof(struct gen_16) == 8, "_Alignof struct gen_16");
_Static_assert(__builtin_offsetof(struct gen_16, m0) == 0, "offsetof struct gen_16.m0");
_Static_assert(__builtin_offsetof(struct gen_16, m1) == 8, "offsetof struct gen_16.m1");
_Static_assert(__builtin_offsetof(struct gen_16, m2) == 16, "offsetof struct gen_16.m2");
_Static_assert(__builtin_offsetof(struct gen_16, m3) == 24, "offsetof struct gen_16.m3");

struct gen_17 {
	long double m0;	/* +0 */
	_Alignas(32) signed char m1;	/* +32 */
	long double m2;	/* +40 */
	short m3 : 9;	/* bit 384 */
};
_Static_assert(sizeof(struct gen_17) == 64, "sizeof struct gen_17");
_Static_assert(_Alignof(struct gen_17) == 32, "_Alignof struct gen_17");
_Static_assert(__builtin_offsetof(struct gen_17, m0) == 0, "offsetof struct gen_17.m0");
_Static_assert(__builtin_offsetof(struct gen_17, m1) == 32, "offsetof struct gen_17.m1");
_Static_assert(__builtin_offsetof(struct gen_17, m2) == 40, "offsetof struct gen_17.m2");

struct gen_18 {
	float m0;	/* +0 */
};
_Static_assert(sizeof(struct gen_18) == 4, "sizeof struct gen_18");
_Static_assert(_Alignof(struct gen_18) == 4, "_Alignof struct gen_18");
_Static_assert(__builtin_offsetof(struct gen_18, m0) == 0, "offsetof struct gen_18.m0");

struct gen_19 {
	long double m0;	/* +0 */
	long long m1;	/* +8 */
	float m2[3];	/* +16 */
	float m3;	/* +28 */
	int m4[2];	/* +32 */
	double m5;	/* +40 */
};
_Static_assert(sizeof(struct gen_19) == 48, "sizeof struct gen_19");
_Static_assert(_Alignof(struct gen_19) == 8, "_Alignof struct gen_19");
_Static_assert(__builtin_offsetof(struct gen_19, m0) == 0, "offsetof struct gen_19.m0");
_Static_assert(__builtin_offsetof(struct gen_19, m1) == 8, "offsetof struct gen_19.m1");
_Static_assert(__builtin_offsetof(struct gen_19, m2) == 16, "offsetof struct gen_19.m2");
_Static_assert(__builtin_offsetof(struct gen_19, m3) == 28, "offsetof struct gen_19.m3");
_Static_assert(__builtin_offsetof(struct gen_19, m4) == 32, "offsetof struct gen_19.m4");
_Static_assert(__builtin_offsetof(struct gen_19, m5) == 40, "offsetof struct gen_19.m5");

struct gen_20 {
	char m0;	/* +0 */
	long double m1;	/* +8 */
};
_Static_assert(sizeof(struct gen_20) == 16, "sizeof struct gen_20");
_Static_assert(_Alignof(struct gen_20) == 8, "_Alignof struct gen_20");
_Static_assert(__builtin_offsetof(struct gen_20, m0) == 0, "offsetof struct gen_20.m0");
_Static_assert(__builtin_offsetof(struct gen_20, m1) == 8, "offsetof struct gen_20.m1");

struct gen_21 {
	float m0;	/* +0 */
	long long m1;	/* +8 */
	float m2[2];	/* +16 */
	int m3;	/* +24 */
	void *m4;	/* +32 */
	_Alignas(32) long double m5;	/* +64 */
};
_Static_assert(sizeof(struct gen_21) == 96, "sizeof struct gen_21");
_Static_assert(_Alignof(struct gen_21) == 32, "_Alignof struct gen_21");
_Static_assert(__builtin_offsetof(struct gen_21, m0) == 0, "offsetof struct gen_21.m0");
_Static_assert(__builtin_offsetof(struct gen_21, m1) == 8, "offsetof struct gen_21.m1");
_Static_assert(__builtin_offsetof(struct gen_21, m2) == 16, "offsetof struct gen_21.m2");
_Static_assert(__builtin_offsetof(struct gen_21, m3) == 24, "offsetof struct gen_21.m3");
_Static_assert(__builtin_offsetof(struct gen_21, m4) == 32, "offsetof struct gen_21.m4");
_Static_assert(__builtin_offsetof(struct gen_21, m5) == 64, "offsetof struct gen_21.m5");

union gen_22 {
	unsigned char m0[3];	/* +0 */
	void *m1;	/* +0 */
	long long m2;	/* +0 */
};
_Static_assert(sizeof(union gen_22) == 8, "sizeof union gen_22");
_Static_assert(_Alignof(union gen_22) == 8, "_Alignof union gen_22");
_Static_assert(__builtin_offsetof(union gen_22, m0) == 0, "offsetof union gen_22.m0");
_Static_assert(__builtin_offsetof(union gen_22, m1) == 0, "offsetof union gen_22.m1");
_Static_assert(__builtin_offsetof(union gen_22, m2) == 0, "offsetof union gen_22.m2");

struct gen_23 {
	short m0[3];	/* +0 */
	long long m1;	/* +8 */
	long m2;	/* +16 */
	long double m3[2];	/* +24 */
	_Alignas(16) unsigned int m4[2];	/* +48 */
};
_Static_assert(sizeof(struct gen_23) == 64, "sizeof struct gen_23");
_Static_assert(_Alignof(struct gen_23) == 16, "_Alignof struct gen_23");
_Static_assert(__builtin_offsetof(struct gen_23, m0) == 0, "offsetof struct gen_23.m0");
_Static_assert(__builtin_offsetof(struct gen_23, m1) == 8, "offsetof struct gen_23.m1");
_Static_assert(__builtin_offsetof(struct gen_23, m2) == 16, "offsetof struct gen_23.m2");
_Static_assert(__builtin_offsetof(struct gen_23, m3) == 24, "offsetof struct gen_23.m3");
_Static_assert(__builtin_offsetof(struct gen_23, m4) == 48, "offsetof struct gen_23.m4");

struct gen_24 {
	signed char m0[2];	/* +0 */
	struct alignas_over_long_double m1;	/* +32 */
	short m2 : 5;	/* bit 768 */
	long double m3;	/* +104 */
};
_Static_assert(sizeof(struct gen_24) == 128, "sizeof struct gen_24");
_Static_assert(_Alignof(struct gen_24) == 32, "_Alignof struct gen_24");
_Static_assert(__builtin_offsetof(struct gen_24, m0) == 0, "offsetof struct gen_24.m0");
_Static_assert(__builtin_offsetof(struct gen_24, m1) == 32, "offsetof struct gen_24.m1");
_Static_assert(__builtin_offsetof(struct gen_24, m3) == 104, "offsetof struct gen_24.m3");

struct gen_25 {
	_Alignas(32) float m0;	/* +0 */
	signed char m1[3];	/* +4 */
	unsigned short m2[2];	/* +8 */
	unsigned char m3;	/* +12 */
	long double m4[3];	/* +16 */
	_Alignas(16) double m5;	/* +48 */
};
_Static_assert(sizeof(struct gen_25) == 64, "sizeof struct gen_25");
_Static_assert(_Alignof(struct gen_25) == 32, "_Alignof struct gen_25");
_Static_assert(__builtin_offsetof(struct gen_25, m0) == 0, "offsetof struct gen_25.m0");
_Static_assert(__builtin_offsetof(struct gen_25, m1) == 4, "offsetof struct gen_25.m1");
_Static_assert(__builtin_offsetof(struct gen_25, m2) == 8, "offsetof struct gen_25.m2");
_Static_assert(__builtin_offsetof(struct gen_25, m3) == 12, "offsetof struct gen_25.m3");
_Static_assert(__builtin_offsetof(struct gen_25, m4) == 16, "offsetof struct gen_25.m4");
_Static_assert(__builtin_offsetof(struct gen_25, m5) == 48, "offsetof struct gen_25.m5");

union gen_26 {
	long long m0;	/* +0 */
	short m1[3];	/* +0 */
	float m2;	/* +0 */
	unsigned short m3;	/* +0 */
};
_Static_assert(sizeof(union gen_26) == 8, "sizeof union gen_26");
_Static_assert(_Alignof(union gen_26) == 8, "_Alignof union gen_26");
_Static_assert(__builtin_offsetof(union gen_26, m0) == 0, "offsetof union gen_26.m0");
_Static_assert(__builtin_offsetof(union gen_26, m1) == 0, "offsetof union gen_26.m1");
_Static_assert(__builtin_offsetof(union gen_26, m2) == 0, "offsetof union gen_26.m2");
_Static_assert(__builtin_offsetof(union gen_26, m3) == 0, "offsetof union gen_26.m3");

struct gen_27 {
	long m0[2];	/* +0 */
	unsigned int m1;	/* +16 */
	_Alignas(32) struct alignas_over_int m2[3];	/* +32 */
	_Alignas(16) float m3;	/* +224 */
};
_Static_assert(sizeof(struct gen_27) == 256, "sizeof struct gen_27");
_Static_assert(_Alignof(struct gen_27) == 32, "_Alignof struct gen_27");
_Static_assert(__builtin_offsetof(struct gen_27, m0) == 0, "offsetof struct gen_27.m0");
_Static_assert(__builtin_offsetof(struct gen_27, m1) == 16, "offsetof struct gen_27.m1");
_Static_assert(__builtin_offsetof(struct gen_27, m2) == 32, "offsetof struct gen_27.m2");
_Static_assert(__builtin_offsetof(struct gen_27, m3) == 224, "offsetof struct gen_27.m3");

struct gen_28 {
	float m0;	/* +0 */
	double m1;	/* +8 */
	unsigned char m2[3];	/* +16 */
	float m3;	/* +20 */
	unsigned char m4;	/* +24 */
};
_Static_assert(sizeof(struct gen_28) == 32, "sizeof struct gen_28");
_Static_assert(_Alignof(struct gen_28) == 8, "_Alignof struct gen_28");
_Static_assert(__builtin_offsetof(struct gen_28, m0) == 0, "offsetof struct gen_28.m0");
_Static_assert(__builtin_offsetof(struct gen_28, m1) == 8, "offsetof struct gen_28.m1");
_Static_assert(__builtin_offsetof(struct gen_28, m2) == 16, "offsetof struct gen_28.m2");
_Static_assert(__builtin_offsetof(struct gen_28, m3) == 20, "offsetof struct gen_28.m3");
_Static_assert(__builtin_offsetof(struct gen_28, m4) == 24, "offsetof struct gen_28.m4");

union gen_29 {
	int m0[3];	/* +0 */
	_Alignas(32) long long m1;	/* +0 */
	short m2;	/* +0 */
	unsigned long m3;	/* +0 */
};
_Static_assert(sizeof(union gen_29) == 32, "sizeof union gen_29");
_Static_assert(_Alignof(union gen_29) == 32, "_Alignof union gen_29");
_Static_assert(__builtin_offsetof(union gen_29, m0) == 0, "offsetof union gen_29.m0");
_Static_assert(__builtin_offsetof(union gen_29, m1) == 0, "offsetof union gen_29.m1");
_Static_assert(__builtin_offsetof(union gen_29, m2) == 0, "offsetof union gen_29.m2");
_Static_assert(__builtin_offsetof(union gen_29, m3) == 0, "offsetof union gen_29.m3");

struct gen_30 {
	double m0;	/* +0 */
	unsigned char m1;	/* +8 */
	void *m2;	/* +16 */
	long long m3;	/* +24 */
};
_Static_assert(sizeof(struct gen_30) == 32, "sizeof struct gen_30");
_Static_assert(_Alignof(struct gen_30) == 8, "_Alignof struct gen_30");
_Static_assert(__builtin_offsetof(struct gen_30, m0) == 0, "offsetof struct gen_30.m0");
_Static_assert(__builtin_offsetof(struct gen_30, m1) == 8, "offsetof struct gen_30.m1");
_Static_assert(__builtin_offsetof(struct gen_30, m2) == 16, "offsetof struct gen_30.m2");
_Static_assert(__builtin_offsetof(struct gen_30, m3) == 24, "offsetof struct gen_30.m3");

union gen_31 {
	_Alignas(16) long double m0;	/* +0 */
};
_Static_assert(sizeof(union gen_31) == 16, "sizeof union gen_31");
_Static_assert(_Alignof(union gen_31) == 16, "_Alignof union gen_31");
_Static_assert(__builtin_offsetof(union gen_31, m0) == 0, "offsetof union gen_31.m0");

struct gen_32 {
	void *m0;	/* +0 */
	long m1;	/* +8 */
};
_Static_assert(sizeof(struct gen_32) == 16, "sizeof struct gen_32");
_Static_assert(_Alignof(struct gen_32) == 8, "_Alignof struct gen_32");
_Static_assert(__builtin_offsetof(struct gen_32, m0) == 0, "offsetof struct gen_32.m0");
_Static_assert(__builtin_offsetof(struct gen_32, m1) == 8, "offsetof struct gen_32.m1");

union gen_33 {
	char m0;	/* +0 */
};
_Static_assert(sizeof(union gen_33) == 1, "sizeof union gen_33");
_Static_assert(_Alignof(union gen_33) == 1, "_Alignof union gen_33");
_Static_assert(__builtin_offsetof(union gen_33, m0) == 0, "offsetof union gen_33.m0");

struct gen_34 {
	double m0;	/* +0 */
	double m1;	/* +8 */
	struct alignas_16 m2;	/* +16 */
	unsigned long m3;	/* +48 */
	_Alignas(16) unsigned char m4;	/* +64 */
};
_Static_assert(sizeof(struct gen_34) == 80, "sizeof struct gen_34");
_Static_assert(_Alignof(struct gen_34) == 16, "_Alignof struct gen_34");
_Static_assert(__builtin_offsetof(struct gen_34, m0) == 0, "offsetof struct gen_34.m0");
_Static_assert(__builtin_offsetof(struct gen_34, m1) == 8, "offsetof struct gen_34.m1");
_Static_assert(__builtin_offsetof(struct gen_34, m2) == 16, "offsetof struct gen_34.m2");
_Static_assert(__builtin_offsetof(struct gen_34, m3) == 48, "offsetof struct gen_34.m3");
_Static_assert(__builtin_offsetof(struct gen_34, m4) == 64, "offsetof struct gen_34.m4");

struct gen_35 {
	char m0;	/* +0 */
	struct bits_then_member m1[2];	/* +4 */
	long m2[3];	/* +32 */
	void *m3;	/* +56 */
};
_Static_assert(sizeof(struct gen_35) == 64, "sizeof struct gen_35");
_Static_assert(_Alignof(struct gen_35) == 8, "_Alignof struct gen_35");
_Static_assert(__builtin_offsetof(struct gen_35, m0) == 0, "offsetof struct gen_35.m0");
_Static_assert(__builtin_offsetof(struct gen_35, m1) == 4, "offsetof struct gen_35.m1");
_Static_assert(__builtin_offsetof(struct gen_35, m2) == 32, "offsetof struct gen_35.m2");
_Static_assert(__builtin_offsetof(struct gen_35, m3) == 56, "offsetof struct gen_35.m3");

union gen_36 {
	long m0;	/* +0 */
	_Alignas(32) unsigned char m1;	/* +0 */
	_Alignas(16) long double m2[2];	/* +0 */
};
_Static_assert(sizeof(union gen_36) == 32, "sizeof union gen_36");
_Static_assert(_Alignof(union gen_36) == 32, "_Alignof union gen_36");
_Static_assert(__builtin_offsetof(union gen_36, m0) == 0, "offsetof union gen_36.m0");
_Static_assert(__builtin_offsetof(union gen_36, m1) == 0, "offsetof union gen_36.m1");
_Static_assert(__builtin_offsetof(union gen_36, m2) == 0, "offsetof union gen_36.m2");

struct gen_37 {
	long m0;	/* +0 */
};
_Static_assert(sizeof(struct gen_37) == 8, "sizeof struct gen_37");
_Static_assert(_Alignof(struct gen_37) == 8, "_Alignof struct gen_37");
_Static_assert(__builtin_offsetof(struct gen_37, m0) == 0, "offsetof struct gen_37.m0");

union gen_38 {
	double m0[2];	/* +0 */
	unsigned int m1;	/* +0 */
	long double m2[3];	/* +0 */
	_Alignas(16) unsigned int m3;	/* +0 */
	struct alignas_8 m4;	/* +0 */
};
_Static_assert(sizeof(union gen_38) == 32, "sizeof union gen_38");
_Static_assert(_Alignof(union gen_38) == 16, "_Alignof union gen_38");
_Static_assert(__builtin_offsetof(union gen_38, m0) == 0, "offsetof union gen_38.m0");
_Static_assert(__builtin_offsetof(union gen_38, m1) == 0, "offsetof union gen_38.m1");
_Static_assert(__builtin_offsetof(union gen_38, m2) == 0, "offsetof union gen_38.m2");
_Static_assert(__builtin_offsetof(union gen_38, m3) == 0, "offsetof union gen_38.m3");
_Static_assert(__builtin_offsetof(union gen_38, m4) == 0, "offsetof union gen_38.m4");

struct gen_39 {
	float m0;	/* +0 */
	char m1;	/* +4 */
};
_Static_assert(sizeof(struct gen_39) == 8, "sizeof struct gen_39");
_Static_assert(_Alignof(struct gen_39) == 4, "_Alignof struct gen_39");
_Static_assert(__builtin_offsetof(struct gen_39, m0) == 0, "offsetof struct gen_39.m0");
_Static_assert(__builtin_offsetof(struct gen_39, m1) == 4, "offsetof struct gen_39.m1");

struct gen_40 {
	int m0 : 19;	/* bit 0 */
};
_Static_assert(sizeof(struct gen_40) == 4, "sizeof struct gen_40");
_Static_assert(_Alignof(struct gen_40) == 4, "_Alignof struct gen_40");

struct gen_41 {
	_Alignas(16) char m0[2];	/* +0 */
	_Alignas(16) unsigned int m1;	/* +16 */
	struct bits_after_member m2;	/* +24 */
	unsigned long m3;	/* +32 */
	long long m4;	/* +40 */
	long double m5[3];	/* +48 */
};
_Static_assert(sizeof(struct gen_41) == 80, "sizeof struct gen_41");
_Static_assert(_Alignof(struct gen_41) == 16, "_Alignof struct gen_41");
_Static_assert(__builtin_offsetof(struct gen_41, m0) == 0, "offsetof struct gen_41.m0");
_Static_assert(__builtin_offsetof(struct gen_41, m1) == 16, "offsetof struct gen_41.m1");
_Static_assert(__builtin_offsetof(struct gen_41, m2) == 24, "offsetof struct gen_41.m2");
_Static_assert(__builtin_offsetof(struct gen_41, m3) == 32, "offsetof struct gen_41.m3");
_Static_assert(__builtin_offsetof(struct gen_41, m4) == 40, "offsetof struct gen_41.m4");
_Static_assert(__builtin_offsetof(struct gen_41, m5) == 48, "offsetof struct gen_41.m5");

struct gen_42 {
	unsigned short m0[2];	/* +0 */
	long m1[3];	/* +8 */
	long m2;	/* +32 */
};
_Static_assert(sizeof(struct gen_42) == 40, "sizeof struct gen_42");
_Static_assert(_Alignof(struct gen_42) == 8, "_Alignof struct gen_42");
_Static_assert(__builtin_offsetof(struct gen_42, m0) == 0, "offsetof struct gen_42.m0");
_Static_assert(__builtin_offsetof(struct gen_42, m1) == 8, "offsetof struct gen_42.m1");
_Static_assert(__builtin_offsetof(struct gen_42, m2) == 32, "offsetof struct gen_42.m2");

union gen_43 {
	struct long_double_pair m0;	/* +0 */
	double m1;	/* +0 */
	long double m2;	/* +0 */
	unsigned short m3;	/* +0 */
};
_Static_assert(sizeof(union gen_43) == 16, "sizeof union gen_43");
_Static_assert(_Alignof(union gen_43) == 8, "_Alignof union gen_43");
_Static_assert(__builtin_offsetof(union gen_43, m0) == 0, "offsetof union gen_43.m0");
_Static_assert(__builtin_offsetof(union gen_43, m1) == 0, "offsetof union gen_43.m1");
_Static_assert(__builtin_offsetof(union gen_43, m2) == 0, "offsetof union gen_43.m2");
_Static_assert(__builtin_offsetof(union gen_43, m3) == 0, "offsetof union gen_43.m3");

union gen_44 {
	long m0;	/* +0 */
	struct bits_straddle_uint m1;	/* +0 */
	_Alignas(32) struct bits_straddle_int m2;	/* +0 */
	struct alignas_1 m3;	/* +0 */
	char m4;	/* +0 */
};
_Static_assert(sizeof(union gen_44) == 32, "sizeof union gen_44");
_Static_assert(_Alignof(union gen_44) == 32, "_Alignof union gen_44");
_Static_assert(__builtin_offsetof(union gen_44, m0) == 0, "offsetof union gen_44.m0");
_Static_assert(__builtin_offsetof(union gen_44, m1) == 0, "offsetof union gen_44.m1");
_Static_assert(__builtin_offsetof(union gen_44, m2) == 0, "offsetof union gen_44.m2");
_Static_assert(__builtin_offsetof(union gen_44, m3) == 0, "offsetof union gen_44.m3");
_Static_assert(__builtin_offsetof(union gen_44, m4) == 0, "offsetof union gen_44.m4");

struct gen_45 {
	long double m0;	/* +0 */
	_Alignas(32) unsigned char m1;	/* +32 */
	unsigned short m2;	/* +34 */
	long long m3[2];	/* +40 */
};
_Static_assert(sizeof(struct gen_45) == 64, "sizeof struct gen_45");
_Static_assert(_Alignof(struct gen_45) == 32, "_Alignof struct gen_45");
_Static_assert(__builtin_offsetof(struct gen_45, m0) == 0, "offsetof struct gen_45.m0");
_Static_assert(__builtin_offsetof(struct gen_45, m1) == 32, "offsetof struct gen_45.m1");
_Static_assert(__builtin_offsetof(struct gen_45, m2) == 34, "offsetof struct gen_45.m2");
_Static_assert(__builtin_offsetof(struct gen_45, m3) == 40, "offsetof struct gen_45.m3");

struct gen_46 {
	_Alignas(32) unsigned int m0;	/* +0 */
	_Alignas(16) long long m1;	/* +16 */
	signed char m2;	/* +24 */
	char m3 : 4;	/* bit 200 */
};
_Static_assert(sizeof(struct gen_46) == 32, "sizeof struct gen_46");
_Static_assert(_Alignof(struct gen_46) == 32, "_Alignof struct gen_46");
_Static_assert(__builtin_offsetof(struct gen_46, m0) == 0, "offsetof struct gen_46.m0");
_Static_assert(__builtin_offsetof(struct gen_46, m1) == 16, "offsetof struct gen_46.m1");
_Static_assert(__builtin_offsetof(struct gen_46, m2) == 24, "offsetof struct gen_46.m2");

struct gen_47 {
	struct alignas_over_int m0;	/* +0 */
	char m1[2];	/* +64 */
};
_Static_assert(sizeof(struct gen_47) == 96, "sizeof struct gen_47");
_Static_assert(_Alignof(struct gen_47) == 32, "_Alignof struct gen_47");
_Static_assert(__builtin_offsetof(struct gen_47, m0) == 0, "offsetof struct gen_47.m0");
_Static_assert(__builtin_offsetof(struct gen_47, m1) == 64, "offsetof struct gen_47.m1");

